### ISSUE TITLE
nvd3 tooltip changes in 1.8

### ISSUE THREAD

**Issue by bwinchester** [krispo/angular-nvd3#102]
Just a heads up, I'm working with this directive and using nvd3 1.8.1 beta and the changes they recently made to nvd3 tooltips causes this directive to not work because its calling an undefined function. The code 

    nv.tooltip.cleanup()

Breaks the directive in the clearElement object.

**Comment by anthonyettinger** [comment]
I'm having the same problem. Have you found a work around yet?

**Comment by mritchie712** [comment]
Change it to

                            if (typeof nv.tooltip.cleanup == 'function')
                                nv.tooltip.cleanup();

**Comment by anthonyettinger** [comment]
@mritchie712 where do I make that change?

**Comment by mritchie712** [comment]
line 192 of angular-nvd3.js

**Comment by anthonyettinger** [comment]
that just silences the error. I don't see this as a real fix.

**Comment by bwinchester** [comment]
Negative @anthonyettinger . It should only call tooltip.cleanup if you are using an older nvd3 chart model. Unfortunately, you could have a mix of old and new nvd3 models using old or new tooltip objects. The solution proposed calls tooltip.cleanup if using the old nvd3 tooltips, while the newer tooltips should clean themselves up better.

**Comment by anthonyettinger** [comment]
so there is no need to call it then? That's what I was wondering. Seemed like a necessary function was missing and you were just working out that fact.

**Comment by anthonyettinger** [comment]
It looks like someone already patched it...do you know if this has been released yet?

https://github.com/krispo/angular-nvd3/blob/master/src/angular-nvd3.js#L183

**Comment by krispo** [comment]
It's fixed in the latest versions. Thanks.
