### ISSUE TITLE
Use of custom colours in Pie Chart?

### ISSUE THREAD

**Issue by umayr** [krispo/angular-nvd3#107]
I couldn't find any way to use custom colours for pie chart using library's API either in documentation or in examples.

Is it possible with the current API?

**Comment by krispo** [comment]
Yes, use `color` option:
```js
//variable of custom colors 
var colors = ["red", "green", "blue"];
...
chart {
    color: function(d){
        return (d.data && d.data.color) || colors[i % colors.length]
    }
}
...
// or set custom colors directly in the data
data = [{
        key: "One",
        y: 5,
        color: "yellow"
    },{
        key: "Two",
        y: 2,
        color: "gray"
    },{
        key: "Three",
        y: 9
    },
     ...
];
```

**Comment by umayr** [comment]
@krispo Awesome. Thanks.

**Comment by shgattu** [comment]
The above code works for legend colors and not for the pie colors.

**Comment by krispo** [comment]
Hi @shgattu , check it please:
http://plnkr.co/edit/YVBBhE?p=preview

**Comment by shgattu** [comment]
Thanks Kripo. The plunker link works good.
http://plnkr.co/edit/f2gTjx?p=preview.

**Comment by martellaj** [comment]
For anyone who comes across this in the future, you can also use hex color codes to determine the color of a data point.

**Comment by PriyanshDwivedi** [comment]
Hi @martellaj, can you show an example of how to use hex codes for colors?

**Comment by debanjana** [comment]
Can we create a doughnut chart?

**Comment by naveenkumarkg** [comment]
How to change font colors in Pie chart for the label and for the legend
