### ISSUE TITLE
Pie Chart Label Issues

### ISSUE THREAD

**Issue by yuvaraj12u** [krispo/angular-nvd3#11]
Hi Krispo,,Thanks for your Reply in LinePlusBarChart,I am Using nvd3 pie chart,my labels are not aligning correctly inside the Pie..Can you hep me find out this..

![pie](https://cloud.githubusercontent.com/assets/5885990/3359750/a90f1f66-faeb-11e3-8e83-8c2c5ecc6c2a.jpeg)

Regards,
Yuvaraj..

**Comment by krispo** [comment]
Update to the latest version, and try to add `labelSunbeamLayout: true` option
