### ISSUE TITLE
The chart color is gray in MultiBarHorizontalChart Live Edit 

### ISSUE THREAD

**Issue by geaden** [krispo/angular-nvd3#112]
The live edit of MultiBarHorizontalChart shows gray bars (in Chrome). It seems it's a bug, as changing one of the options makes the chart to be multicolored.

**Comment by JamesMura** [comment]
I think this issue is relate to this https://github.com/novus/nvd3/issues/916

**Comment by krispo** [comment]
It's fixed in the latest version [1.0.4+].
