### ISSUE TITLE
yAxis formatting is not supported in v1.0

### ISSUE THREAD

**Issue by carpiediem** [krispo/angular-nvd3#115]
I've been trying to remove the decimal places from the numbers in my yAxis by changing the formatting sting to '0f' instead of '2f'.
```
d3.format(',.0f')(d);
```
You can see on [the demo page](http://krispo.github.io/angular-nvd3/#/stackedAreaChart) that this works with v0.1.1, but not in v1.0.0BETA.

**Comment by KurtPreston** [comment]
+1

**Comment by jlwerenskjold** [comment]
I've run into the same problem, has anyone found a fix?

**Comment by jee1mr** [comment]
+1

**Comment by jlwerenskjold** [comment]
If you have updated to the latest version of angular-nvd3 and nvd3 then you should be able to format the y-axis.

**Comment by krispo** [comment]
Please, update to the latest version [1.0.4+]. It should work fine.
