### ISSUE TITLE
Does this directive support all charts labelled in nvd3?

### ISSUE THREAD

**Issue by shgattu** [krispo/angular-nvd3#116]
Hi,
Does this charting directive allow us to have all the options that nvd3 is supporting like sunburst.
http://nvd3-community.github.io/nvd3/examples/site.html
Thanks,
sHWETHA

**Comment by shgattu** [comment]
This is not a bug with directive but a question to the author.

**Comment by krispo** [comment]
I will definitely add all additional charts soon! thanks.

**Comment by shgattu** [comment]
Do you know by when exactly?
