### ISSUE TITLE
how to make the y2Axis range

### ISSUE THREAD

**Issue by zhendong590** [krispo/angular-nvd3#117]
i want to change y2Axis value range. i saw the demo [line + Bar](http://plnkr.co/edit/f0QET0?p=preview/ "Title"),how to make the y2Axis range to [0 -- max],now it starts at $57.27

**Comment by krispo** [comment]
y2axis is line axis, so change ydomain in line options:
```js
chart: {
    lines: { //main chart
        yDomain: [0, 1000]
    },
    lines2: { //focus chart
        yDomain: [0, 1000]
    }
}
```
