### ISSUE TITLE
Quick question on line chart and cumulative line chart

### ISSUE THREAD

**Issue by shgattu** [krispo/angular-nvd3#118]
If we want to dispatch different events for different lines. How can we achieve this.
I tried below code but it didn't execute second lines1 event.
lines: {
									dispatch:{ elementClick: function (e) {
							     console.log("lines are clicked")
					      	}
									}
								},
								 lines1: {
									dispatch:{ elementClick: function (e) {
							     console.log("lines are clicked2")
					      	}
									}
								}

Your help will be appreciated.

console.log shows only lines are clicked always.

**Comment by krispo** [comment]
There is no `line1` options. Instead, you can get all necessary info about series from event object `e`:
```
lines: {
dispatch: {elementClick: function(e){
    e.point
    e.pointIndex
    e.pos
    e.series    
    e.seriesIndex
    ....
}
}
}
```

**Comment by shgattu** [comment]
Yes that worked.
I have one more question regarding stacked area chart, multibarchart, historical bar chart.
What would be the key value for these?
For instance lineChart it is lines :{ dispatch ...}

**Comment by NameFILIP** [comment]
how about `stacked`, `bars`?

**Comment by christiaanwesterbeek** [comment]
For a `multiBarChart` it is `multibar`. So , part of your chart configuration would be

```javascript
multibar: {
  dispatch: {
    elementClick: (e) => { console.log('elementClick', e) }
  }
}
```
