### ISSUE TITLE
Utils factory name collision

### ISSUE THREAD

**Issue by kamilbrk** [krispo/angular-nvd3#120]
Hi,

Could you prefix the name of your 'utils' factory to make it unique?

As far as I can tell, Angular does not handle the same names well, even if they are in separate modules and 'utils' could be popular in 3rd party modules or within user code.

Cheers!

Edit:
I used a workaround in my project for the time being - conditional gulp-replace within my Gulp task:

```javascript
  .pipe($.if(v.dir === 'angular-nvd3', $.replace('\'utils\'', '\'nvd3utils\'')))
```

**Comment by NameFILIP** [comment]
There are two PRs for this: https://github.com/krispo/angular-nvd3/pull/157 and https://github.com/krispo/angular-nvd3/pull/155 One of them will be merged soon.
