### ISSUE TITLE
legendPosition:'right' not working

### ISSUE THREAD

**Issue by VijetaH** [krispo/angular-nvd3#121]
In NVD3 library legendPosition: 'right' is working but using the directive it is not working

Link of nvd3
https://github.com/novus/nvd3/pull/951
https://gist.github.com/rreinhardt9/6b055863fcf41c76a5ce

**Comment by vineelal** [comment]
I'm also facing the same issue

**Comment by krispo** [comment]
It works with the latest version [1.0.4].
