### ISSUE TITLE
elementMouseover

### ISSUE THREAD

**Issue by olivierbeyler** [krispo/angular-nvd3#122]
lines: {
                            dispatch: {//container of event handlers
                                elementClick: function (e) {
                                    console.log('click' + e[0].point[0]);
                                },
                                elementMouseover: function (e) {
                                    console.log('MouseOver' + e[0].point[0]);
                                }
                            }

elementMouseOver seem not to be active even on your sample when I had a consolelog  on dispatch elementMouseover the function seem to be never called.

my aim is to capture the event mouse to have a real interactive behavior with the other part of my page : when I move the mouse on the graph i change other control into my page.

**Comment by sthum** [comment]
This problem is still present, mind having a look at it @krispo? I really need to get this `elementMouseover` working for a project. `elementMouseClick` is working. 
Unfortunately `elementMouseover` doesn't even work in the samples.

My options look like:
```
scope.options = {
        chart: {
            lines: {
                dispatch: { 
                    elementClick: function(e){ console.log('click') },
                    elementMouseover: function(e){ console.log('mouseover') },
                    elementMouseout: function(e){ console.log('mouseout') }
                }
            }
     }
```
appreciate your investigation

**Comment by krispo** [comment]
it's not working together with active `interactiveLayer` for some reason. If you turn it off `useInteractiveGuideline: false`, it should work. 

But with active interactiveLayer you can try to use its `elementMousemove` and `elementMouseout` events instead:
```js
chart: {
    useInteractiveGuideline: true,
    interactiveLayer: {
        dispatch: { 
            elementClick: function(e){ console.log('click') },
            elementDblclick: function(e){ console.log('double click') },
            elementMousemove: function(e){ console.log('mousemove') },
            elementMouseout: function(e){ console.log('mouseout') }
        }
    }
}
```

**Comment by sthum** [comment]
Thanks krispo.
In my case I need to find the corresponding element in the "original" datalist that is used for the chart.
The problem I am having with this approach is that the xValue in the event is interpolated as the event is thrown for every movement (like expected). That does make it hard to determine to which datapoint from the original dataliste the mouseOver belongs too. 

The workaround I am using now is to implement a custom tooltip to get my desired `elementMouseover` behavior. The `contentGenerator` Method is called for every mouse-over on a datapoint and provides the index of the series via `event.index`. In my case I am using this index to fetch the element from my original dataset, append additional info to the tooltip as well as highlighting a row in a table based on the hovered datapoint.

I created my tooltip based on the style of the original tooltip, like so:
```
 callback: function (chart) {
            var tooltip = chart.interactiveLayer.tooltip;
            tooltip.gravity('s');
            tooltip.fixedTop(65);
            tooltip.contentGenerator(function (event) {
                var rows = event.series.reduce(function (carryOver, series) {
                    return carryOver +
                        "<tr>" +
                        "<td class='legend-color-guide'><div style='background-color: " + series.color + ";'></div></td>" +
                        "<td class='key'>" + series.key + "</td>" +
                        "<td class='value'>" + series.value + "</td>" +
                        "</tr>";
                }, "");

                var header = "<thead><tr><td colspan='3'><strong class='x-value'>" + event.value + "</strong></td></tr></thead>";
                return "<table>" +
                        header +
                        "<tbody>"+rows+"</tbody>" +
                        "</table>";
            }
}
```

**Comment by shnigi** [comment]
@sthum thanks for the hint, managed to create tooltip with this, as the suggested content creator didn't get all the data points in my case.

**Comment by fiorila** [comment]
@sthum Hi, I am in the same case, I wan to highlight a row in the tooltip table base on the hovered datapoint. I tried to use the event.index but I am not getting the correct result. Would you mind to give a look, it's pretty similar to your code : 

```
      event.series.reverse().forEach(serie => {
        // the highlight class is defined by nvd3 in their stylesheet, it is used by the linechart
        // here we just reuse it with our custom tooltip generator
        let className = serie.value === event.index ? "highlight" : "no-highlight";

        content += `<tr class=${className}>`
          // + '<td class="key">' + opt[0].toUpperCase() + opt.slice(1) + '</td>'
          + '<td class="legend-color-guide"> <div style="background-color:' + serie.color + '"></div></td>'
          + '<td class="key">' + serie.key + '</td>'
          + '<td class="value">' + this.roundNum(serie.value, 1) + (forceUnit ? ` ${forceUnit}` : "") + '</td>'

```
