### ISSUE TITLE
Controller as vm syntax

### ISSUE THREAD

**Issue by ImranAhmed** [krispo/angular-nvd3#126]
Hi,

I am not using $scope in my solution but am instead using the following pattern:

    <div ng-controller="chart.Controller as vm"></div>

How do you bind to the nvd3 chart when using this pattern? I tried this but it does not work.

    <nvd3 options="{{vm.options}}" data="{{vm.data}}" class="with-3d-shadow with-transitions"></nvd3>

**Comment by krispo** [comment]
You should try to find a way to use $scope in the controller, because evaluated variables are unsuitable in directive (may be in the future).

**Comment by ImranAhmed** [comment]
Thanks,

I was able to get this working with the 'as' syntax. Just had to change my binding to following:
    
    <nvd3 options="model.options" data="model.data" class="with-3d-shadow with-transitions">/nvd3>
