### ISSUE TITLE
Long labels don't wrap

### ISSUE THREAD

**Issue by shgattu** [krispo/angular-nvd3#127]
Hi,
Is there a way I can wrap long titles labels except for using staggeringLabels true.
Some like defining it in x function
x : function(d){
      function to wrap d.text
}

**Comment by krispo** [comment]
Try this:
```
xAxis: {
    tickFormat: function(d){
        return wrapFn(d);
    }
}
```

**Comment by raghuveersp** [comment]
Are you suggesting to write our own wrapFn and then use it ? or is this wrapFn given already ? If its former case, what is the expected output of wrapFn ? Do I need to add tspans with the wrapped text ? Do I need to have "\n" appended to d.split which I want ? Please suggest.

**Comment by shgattu** [comment]
I have used foreignobject and wrapped the text in FF,Chrome.

 tickFormat: function(d){
                    //    console.log('text is'+d);
                       // d = null;
                      // console.log(angular.element(this))
                        d3.select(this.parentNode).append('foreignObject')
                        
							.attr('class', 'foreignobj').
							attr('x',0).attr('y',3).
							attr('width',30).attr('height',250)
							.append('xhtml:div')
							.attr('dy', '.75em')
							.html(function (d) {
								return d;
							})
							.attr('class', 'textdiv');
							d3.select(this).style('display','none');
                        return d;
                      }

**Comment by raghuveersp** [comment]
@shgattu  - Thanks for your response. Can you please shed some light on exactly how can you do this in angular directive given for nvd3 here? Also, as far as I know, foreignObjects does not work in IE, so how did you make them work there ? I am really stuck and any help is really appreciable.

**Comment by shgattu** [comment]
Hey Raghuveer,
I tried a lot for IE but it was tough. I have some hardcoded values working in plnkr.
http://plnkr.co/edit/4qsoSA?p=preview
Instead of hardcoded values you need to use text element's attribute dy and y.

**Comment by krispo** [comment]
Thanks, @shgattu.

**Comment by rakia** [comment]
to show a long label in the legend, you have to change the "maxKeyLength" in the "legend" object which has the default value 20.
`chart: {
...
legend: { maxKeyLength: 100 },
...
}`

**Comment by maddyjolly2112** [comment]
It worked like a charm,

` tickFormat: function(d){
							if (typeof this != 'undefined') {
								 var el = d3.select(this);
								 var p = d3.select(this.parentNode);
								 p.append("foreignObject")
										.attr('x', -25)
										.attr("width", 50)
										.attr("height", 200)
										.append("xhtml:p")
										.attr('style','word-wrap: break-word; text-align:center;')
										.html(d);    

									el.remove();
									return d;
							}
 }`

**Comment by maddyjolly2112** [comment]
It worked like a charm,

```
 tickFormat: function(d){
                            if (typeof this != 'undefined') {
                                 var el = d3.select(this);
                                 var p = d3.select(this.parentNode);
                                 p.append("foreignObject")
                                        .attr('x', -25)
                                        .attr("width", 50)
                                        .attr("height", 200)
                                        .append("xhtml:p")
                                        .attr('style','word-wrap: break-word; text-align:center;')
                                        .html(d);    

                                    el.remove();
                                    return d;
                            }
 }
```

**Comment by frankdoty** [comment]
This function works great for word-wrapping the label, but it removes the hover over display of the graph. Is there a way to incorporate both functionalities?

**Comment by sashberd** [comment]
Hey @krispo ,
I found that if `showMaxMin` is true, function that provided by @maddyjolly2112 not works since  `tickFormat `function scopes to **window** and to the `<text></text>`  element. On regular ticks it works brilliant. 
@maddyjolly2112 thanks for great solution.
How to fix it or you will fix it inside api?

**Comment by cyanzhqq** [comment]
Here is my working solution, which also combines with the customization of labels as long string.
http://jsfiddle.net/cyanzhang/ezb48oL4/3/

**Comment by KirillLogin** [comment]
> This function works great for word-wrapping the label, but it removes the hover over display of the graph. Is there a way to incorporate both functionalities?

Sorry for necroposting but maybe someone is keep struggling with that issue.
My solution is:

```
tickFormat: function(d) {
    d3.select(this)
        .attr('style', 'fill:transparent');
    if (this) {
        d3.select(this.parentNode)
            .append("foreignObject")
            .attr('x', -125)
            .attr('y', -8)
            .attr("width", 120)
            .attr("height", 100)
            .append("xhtml:p")
            .attr('style', 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:right;font-size:14px')
            .html(d);
    }
    return d;
}
```

**Comment by letsbecometechie** [comment]
In my case the text wrap was not working. so i wrote a custom function to ellipsis the word like the length is more than 14.
`tickFormat: function(d){ return d.length > 14 ? d.substring(0,13) + '..' : d; },`
