### ISSUE TITLE
UseInteractiveGuideline in lineWithFocusChart

### ISSUE THREAD

**Issue by yashutanna** [krispo/angular-nvd3#128]
Firstly, Thank you for an awesome library.

I notice that i cannot add the property ```useInteractiveGuideline: true``` when using LineWithFocusChart. Novus does support this since https://github.com/novus/nvd3/pull/928 

I wonder if it may just have been overlooked, or am i completely wrong?

Thanks

**Comment by jcq** [comment]
I was just wondering the same thing myself. Did anyone ever figure out a setting that enables that functionality in the current builds?

**Comment by krispo** [comment]
It works with the latest versions.
