### ISSUE TITLE
Trigger resize event programmatically

### ISSUE THREAD

**Issue by tft92** [krispo/angular-nvd3#134]
Hi,

i'm using this and gridster to build a dashboard. When I toggle my sidebar, the container of the chart resizes accordingly, but the chart itself doesn't. Is there a way to trigger the resize-event for the chart programmatically?

**Comment by Tyguy7** [comment]
+1

**Comment by pihomeserver** [comment]
+1

**Comment by krispo** [comment]
Check this gridster [dashboard](http://krispo.github.io/angular-nvd3/#/dashboard).

**Comment by krispo** [comment]
Check this [dashboard](http://krispo.github.io/angular-nvd3/#/dashboard)

**Comment by davepoleon** [comment]
Hi I am trying to create a dashboard similar to the one in the comment above i.e. http://krispo.github.io/angular-nvd3/#/dashboard

I am using Gridster2  and nvd3 in an Angular2+ application, the charts are not resizing and I don't know how to make them refresh when the grid items are re-sized.

Do you have an Angular2+ example of the dashboard?

Thanks in advance for your time.
