### ISSUE TITLE
multiBarHorizontalChart is not considering color from options

### ISSUE THREAD

**Issue by Black-Star** [krispo/angular-nvd3#139]
I am using below as my options.
1.multiBarHorizontalChart is not considering colors from options. Rather it is creating grayscale.
2.Is there a way to transform legend from radio buttons to checkboxes.

    $scope.options = {
            chart: {
                type: 'multiBarHorizontalChart',
                height: 450,
                margin : {
                    top: 20,
                    right: 20,
                    bottom: 60,
                    left: 65
                },
                color: d3.scale.category10().range(),
                transitionDuration: 300,
                useInteractiveGuideline: true,
                clipVoronoi: false,
                showControls:false,
                showLabels:true,

                xAxis: {

                    tickFormat: function(d) {
                        return d;
                    },
                    showMaxMin: false,
                    staggerLabels: false,
                    rotateLabels:0,
                    axisLabelDistance: 240

                },

                yAxis: {
                    axisLabel: 'Y Axis',
                    showMaxMin: false,
                    tickFormat: function(d){
                        return d3.format('.01f')(d);
                    },
                    axisLabelDistance: 40
                },
                legend: {
                    radioButtonMode:true,
                },
            }

**Comment by wmbutler** [comment]
Same Issue here.

**Comment by krispo** [comment]
Upgrade to the latest version, it should work. If not, remove `color` properties from data. As for checkboxes, think not.
