### ISSUE TITLE
title in the middle of donut doesn't appear

### ISSUE THREAD

**Issue by wsoubra** [krispo/angular-nvd3#140]
Hello,
The title doesn't appear. This is my code. 
$scope.options= {
      chart: {
        type: 'pieChart',
        height: 200,
        width: 200,
        donut: true,
        x: function(d){return d.label;},
        y: function(d){return d.value;},
        showLabels: true,
        pie: {
          startAngle: function(d) { return d.startAngle/2 -Math.PI/2 },
          endAngle: function(d) { return d.endAngle/2 -Math.PI/2 },
          title: true
      },
      showLegend: true,
        labelThreshold: 0.01,
        labelType: "percent",
        title: 'fae',
        
        legend: {
          margin: {
            top: 5,
            right: 35,
            bottom: 5,
            left: 0
          }
        }
      }
  };

Thank you for your help.
BR

**Comment by amalahussein** [comment]
Do we have any progress on this issue? B/c I am also experiencing the same thing.

**Comment by amalahussein** [comment]
So I was able to fix this issue by making sure I was on the latest verison of the library....v1.0.0-rc.2 works just fine. You just need to add title on the root of the chart object...and its a string.

**Comment by krispo** [comment]
Yes, it works in the latest versions.

**Comment by amalahussein** [comment]
Yup, thanks @krispo, I was able to resolve it by upgrading my version. I forgot to close this issue. Thanks for following up.

**Comment by VaibhavP17** [comment]
@krispo : Is there a way to provide the title in donut chart asynchronously ? As per my requirement, I actually want to show the 'total number' as the title which will be fetched from an ajax call. How can I provide a title in such scenario ? Kindly guide :)
