### ISSUE TITLE
update data issue when set $scope.data to a new data, not insert a value

### ISSUE THREAD

**Issue by Awakening-j** [krispo/angular-nvd3#143]
I'm working on a angular-nvd3 demo on plunker, the chart works fine when I push a new value into data.values, But failed to display any data when I set new data: $scope.data = newData;  

I've created the demo in plunker   
http://plnkr.co/edit/BfosBI?p=preview  
in app.js,  comment line 34, and uncomment line 35

Is there anything I miss?

**Comment by Awakening-j** [comment]
Is anyone here?

**Comment by krispo** [comment]
Try it with the latest release [1.0.4+], it should work fine.
