### ISSUE TITLE
Stacked options in Multi Bar chart does not work on Library beta version.

### ISSUE THREAD

**Issue by jerrybk108** [krispo/angular-nvd3#149]
Hi nvD3 development team,

First of all, I would like to say big thanks to you all for the great library.

When I use Multibar chart, I met an issue:
You can check here:
http://krispo.github.io/angular-nvd3/0.x/#/multiBarChart
When the chart is rendered, you can choose Library on top-left of the screen, then choose library version 0.1.1, then you check/unchech on Stacked option on right of the screen, the chart will change following your choosing. But when you choose library beta version, the chart will be nochange when you check/unchech on Stacked option.

Please help us fixing the issue.
Thanks in advance,
Hieu Tran

**Comment by NameFILIP** [comment]
Fixed by https://github.com/krispo/angular-nvd3/pull/101
