### ISSUE TITLE
Css line applied to different serie

### ISSUE THREAD

**Issue by brunifrancesco** [krispo/angular-nvd3#152]
How can I can edit a css belonging to specific series?
I'd like to make a dashed line but I cannot find any tip in docs/example.

**Comment by krispo** [comment]
Yes, check [this](http://plnkr.co/edit/lBKFld?p=preview).

**Comment by AlexandreDenis** [comment]
The `classed: 'dashed'` option doesn't exist anymore, isn't it? Because I don't manage to make it work and I don't find it in the documentation.

**Comment by krispo** [comment]
You specify the class name from your css
```css
.dashed {
    stroke-dasharray: 5,5;
}
```
in the data `classed`:
```js
var data = [{
    values: [...],
    key: 'Sine Wave', 
    color: '#ff7f0e', 
    strokeWidth: 2,
    classed: 'dashed'
}]
```

**Comment by AlexandreDenis** [comment]
Works like a charm ! Thank you krispo.

**Comment by AlexandreDenis** [comment]
@krispo I come back to you regarding the `dashed`CSS class.
As I said one month ago, it works well.
However I recently noticed a graphic bug on the highlight hover point when a plot has the `dashed`CSS class.

I let you see the result:

- without the `dashed` CSS class :

![Without the dashed class](http://image.noelshack.com/fichiers/2016/20/1463663671-angular-nvd3-without-dashed-class.png)

- with the `dashed` CSS class :

![With the dashed class](http://image.noelshack.com/fichiers/2016/20/1463663671-angular-nvd3-with-dashed-class.png)

It appears that the highlight hover points are incomplete with the `dashed` CSS class. Have you any idea to fix it ?

**Comment by krispo** [comment]
It's a bug in the latest nvd3 (1.8.2+). Need to dive into it..

**Comment by AlexandreDenis** [comment]
Ok, I will look that. Thanks
