### ISSUE TITLE
Pie chart height does nothing on Internet Explorer 11

### ISSUE THREAD

**Issue by petmat** [krispo/angular-nvd3#158]
If you load http://krispo.github.io/angular-nvd3/#/pieChart on IE 11 you will see that the chart is a lot smaller than e.g. on Chrome. And if you change the height property the chart still stays very small. Is this an issue with angular-nvd3, nvd3 or d3? I'm using angular-nvd3 on a production site and would really appreciate it if you could provide help for how to fix this issue on IE 11. Thanks.

**Comment by petmat** [comment]
Further investigation revealed that when the window is resized the pie chart returns to the correct size but bringing mouse cursor over the chart immediately shrinks it back to a tiny size. So the error must be in the way the resizing is initialized.

Also the error is only in angular-nvd3. Nvd3 does not have this issue.

**Comment by matzmz** [comment]
I have the same problem.
Using the style workaround (proposed by Inookl) the bug is fixed.

Thanks

**Comment by krispo** [comment]
Thanks, this issue will be fixed in the new release (1.0.3).
