### ISSUE TITLE
Not working properly in IE11, IE10

### ISSUE THREAD

**Issue by mohitjee15** [krispo/angular-nvd3#16]
http://krispo.github.io/angular-nvd3/#/lineChart

Try to check it in IE. The Y-axis is cutting in half.

It would be great if you could fix the issue as soon as possible. 

I found your demo really cool so I went with your library. 

Please help me out here :)

**Comment by ImranAhmed** [comment]
Hi,

Please could you update the package in NPM => https://www.npmjs.com/package/angular-nvd3

I coudl do with this fix but the NPM packaage is still on 1.0.0-beta.

Thanks,
Imran

**Comment by xkrabb** [comment]
In v1.0.0-rc.2 still have the issue, I overwrite ‘svg.nvd3-svg { height : ?px;}’ in style.css to make a simple fix in application.

**Comment by krispo** [comment]
This issue will be fixed in the new release (1.0.3).
