### ISSUE TITLE
Resizing event of the chart

### ISSUE THREAD

**Issue by raulgomis** [krispo/angular-nvd3#17]
In the examples page, when you change from an example to another and try to resize the graph, multiples exceptions are thrown in the console: Error: Invalid value for <g> attribute transform="translate(NaN,5)". Seems that the resize event is not properly deleted.

**Comment by raulcesar** [comment]
I know this is an old thread, but I just ran into this issue, so I'm guessing it hasn't been addressed. Upon checking the original nvd3 code (version 1.7.1), I found that the nv.utils.windowResize function actually returns an object with a clear() method that unregisters the  events . However, this object is never used by the angular directive.
I forked my own version and messed with the code for a possible solution (PR #79)

**Comment by NameFILIP** [comment]
This was merged
