### ISSUE TITLE
Tooltip gets stuck after refresh data (updateWithOptions: true)

### ISSUE THREAD

**Issue by miguelrincon** [krispo/angular-nvd3#172]
I am updating to 1.0.0-rc.2 with nvd3 1.8.1 an I am experiencing some problems with the tooltips.

My pie chart is refreshed every 10 seconds with new data from an ajax call, if I happen to to hover the chart so a tooltip is shown WHILE the refresh happens, the tooltip stays stuck in the same position and is never removed from the DOM.

In my setup `updateWithOptions` is `true`

![tooltips](https://cloud.githubusercontent.com/assets/1589102/8587620/0030eff6-2631-11e5-8eef-672823b453b2.png)

Since `nv.tooltip.cleanup` is removed from this version of nvd3, no cleanup happens on clearElement.

I am able to make things work normally by forcibly removing the tooltip in the clearElement function like this:

```js
// Fully clear directive element
clearElement: function (){
    /* ... */
    if (scope.chart && scope.chart.tooltip){
       d3.select("#" + scope.chart.tooltip.id()).remove();
    }
    /* ... */
    scope.chart = null;
},
```

Not sure if this is the right approach and also I hope not to have to hack this tool.

I am using angular v1.4.2 and I was not able to reproduce this issue on a lineChart.

**Comment by owaaa** [comment]
Having the same issue on discrete bar chart. Thanks for the workaround

**Comment by mikyladewitt** [comment]
I was also able to reproduce this issue using the donut chart. 
The workaround also worked for me, though it would be nice if the tooltip could refresh with the new values.

I am using:
Angular v1.3.16
angular-nvd3 v1.0.0-rc2
nvd3 v1.8.1
d3 v3.5.6

**Comment by yppeaxy** [comment]
Yup, same here. I am seeing this on the pie chart.

**Comment by Glebby** [comment]
Same here. Is there a fix expected?

**Comment by sararaslivres** [comment]
Same here... also removing them by hacking it.

**Comment by krispo** [comment]
@miguelrincon thanks, your approach is correct. In the latest releases [1.0.3+] all it's fixed.
