### ISSUE TITLE
Error in extended multibar example on browser window resize

### ISSUE THREAD

**Issue by dsine-de** [krispo/angular-nvd3#18]
If I switch this example chart http://krispo.github.io/angular-nvd3/#/multiBarChart to "Extended" and then resize the browser window, I get the following console error:

`Error: Invalid value for <g> attribute transform="translate(NaN,5)"`

**Comment by jmtorralvo** [comment]
You need to disabled nvd3 resize events and empty some properties:

window.nv.charts = {};
window.nv.graphs = [];
window.nv.logs = {};
// remove resize listeners
window.onresize = null;

**Comment by krispo** [comment]
Yes, this bug is fixed in the last version. 
but one notice, the only graph (for specific directive) is needed to be empty, while `window.nv.graphs = []`  will empty all nv graphs on a page.

**Comment by jmtorralvo** [comment]
Ok. Thanks!
