### ISSUE TITLE
grid tick interval

### ISSUE THREAD

**Issue by molnard** [krispo/angular-nvd3#182]
Hi,

Thank you for this great charting library! I would like to modify the interval of the grid lines on the xAxis. Is it poosible to make it more dense? 

Thank you in advance,
Dave

**Comment by gregor-srdic** [comment]
Have you tried setting ticks in xAxis property of the chart config?
```javascript
chart: {
         type: 'lineWithFocusTwoAxesChart',
         xAxis: {
               ticks:8
          }
}```
Or if I am not mistaken you can also use an array of exact x coordinates for the ticks for the same property.

**Comment by molnard** [comment]
Thank you for your answer. I have created a plunker of this
http://plnkr.co/edit/lNMBmo?p=preview

I am using lineChart I put 
         xAxis: {
               ticks:8
          }
looks like nothing changed.

**Comment by gregor-srdic** [comment]
Interesting. If you do the same here http://krispo.github.io/angular-nvd3/#/lineChart it works

**Comment by molnard** [comment]
my bower json looks like

{
  "name": "angular-seed",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-seed",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "~1.4.0",
    "angular-loader": "~1.4.0",
    "angular-mocks": "~1.4.0",
    "html5-boilerplate": "~5.2.0",
    "angular-gettext": "~2.1.0",
    "angular-xml": "~2.1.0",
    "angular-ui-router": "~0.2.15",
    "bootstrap": "~3.3.5",
    "angular-smart-table": "~2.1.0",
    "angular-nvd3": "~0.1.1",
    "toastr": "~2.1.1",
    "angular-cookies": "~1.4.3"
  }
}
I was using bower install angular-nvd3



2015-07-16 14:20 GMT+02:00 Gregor Srdic <notifications@github.com>:

**Comment by gregor-srdic** [comment]
I'm not using bower, but my project setup is
AngularJS-nvD3, v1.0.0-rc.2
nvd3 version 1.8.1
d3 version 3.5.6


V V čet., 16. jul. 2015 ob 14:38 je oseba Dávid Molnár <
notifications@github.com> napisala:

**Comment by molnard** [comment]
You are right the problem was I used old versions.

Manual install instructions on github: https://github.com/krispo/angular-nvd3#install
You should alwasy install nvd3 manually! (even if you are using bower: bower install nvd3)

I have changed my bower.json to looks like this:

{
  "name": "angular-seed",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-seed",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "~1.4.3",
    "angular-loader": "~1.4.0",
    "angular-mocks": "~1.4.0",
    "html5-boilerplate": "~5.2.0",
    "angular-gettext": "~2.1.0",
    "angular-xml": "~2.1.0",
    "angular-ui-router": "~0.2.15",
    "bootstrap": "~3.3.5",
    "angular-smart-table": "~2.1.0",
    "toastr": "~2.1.1",
    "angular-cookies": "~1.4.3",
    "angular-nvd3": "~1.0.0-rc.2",
    "nvd3": "~1.8.1"
  }
}
Important part is
    "angular-nvd3": "~1.0.0-rc.2",
    "nvd3": "~1.8.1"

Thank you for your help!
Now I can change the grid with ticks!

**Comment by molnard** [comment]
One more question. I would like to define exatly where to put gridlines in my chart
I tried this but it is not working

xAxis: {
ticks:[10,20,30]
}

Would you be so kind and solve this last problem for me? :-)

**Comment by gregor-srdic** [comment]
I was mistaken, try tickValues=[10,20,30] instead of ticks :)

V V čet., 16. jul. 2015 ob 15:05 je oseba Dávid Molnár <
notifications@github.com> napisala:

**Comment by molnard** [comment]
Works like hell! Thank you!

2015-07-16 15:15 GMT+02:00 Gregor Srdic <notifications@github.com>:

**Comment by gregor-srdic** [comment]
great, you're wellcome :)

>

**Comment by pkeller3** [comment]
I'm trying to do something similar but with a multibar chart. When I change the xAxis ticks value the number of ticks does not change from the default.

I've also tried to set tickValues with an array of integers and when I do that I only see the min and max values with no ticks between.

Thanks

**Comment by molnard** [comment]
Sorry for late answer I was on holiday. 
I tried to add tickValues to lineChart in plunker but it was not working because plunker uses older version of nvd3 so be careful with PLUNKER. Instead of plunker I would suggest the live Edit function which can be found here:
http://krispo.github.io/angular-nvd3/#/lineChart

Anyway I tried my solution ( which is working on linechart ) but on multichart unfortunately it does not. I cannot find a solution on your problem.
Dave

**Comment by pkeller3** [comment]
Thanks for looking into it. It doesn't seem like there is currently a solution available without making changes to nvd3.

**Comment by blandofgod** [comment]
There is a solution to this for a multipbarchart
yAxis: {
                            ticks:10,
                             ....
}

you can adjust the number, but this will display ticks

**Comment by Abhay07** [comment]
Hi,
I'm facing the same issue.
Here's the demo.
[Demo](https://plnkr.co/edit/7zg62ezs730i40U0GTHy?p=preview)

**Comment by Manaskumar119** [comment]
@blandofgod , is ticks value can be  greater than 10  ??  
I tried to do with  ticks: 30  , but it does not work , any suggestion ?
