### ISSUE TITLE
example of sunburst

### ISSUE THREAD

**Issue by manjoine** [krispo/angular-nvd3#184]
http://plnkr.co/edit/ppkFQyc9u32oiBNvtuYq?p=preview

is an example of a sunburst for your examples site.
also i noticed that the bower webjar is not correct for rc2 it is showing the files 
http://www.webjars.org/listfiles/org.webjars.bower/angular-nvd3/1.0.0-rc.2
and the file contained is the 1.0.0 file not the rc.2 I tried a new bower install to see if that will fix it so maybe tomorrow it will be correct.

**Comment by krispo** [comment]
Sunburst is now added. Thanks.
