### ISSUE TITLE
Add graph title

### ISSUE THREAD

**Issue by amolpatel** [krispo/angular-nvd3#186]
How do you add a graph title in the graph options?

**Comment by bubbleheadinc** [comment]
From what I can tell it is supposed to be like this, but it's not working for me...

```
title: {
  enable: true,
  text: "Title Text"
}
```

**Comment by Sheparzo** [comment]
Can the text of the title be dynamic?  Can it be bound to the data of the chart?  

    title: {
        enable: true,
        text: "Title Text " + $scope.chartData.dataElement
    }

**Comment by JesseDahl** [comment]
@bubbleheadinc , 
Something like this is working for me. It's not a child object of the chart object, it's a sibling.

```
vm.throughput.options = {
                chart: {
                    type: 'lineChart',
                    margin : {
                        top: 20,
                        right: 40,
                        bottom: 20,
                        left: 20
                    },
                    x: function(d){ return d.x; },
                    y: function(d){ return d.y; },
                    useInteractiveGuideline: true,
                    duration: 0,
                    showLegend: false,
                    yAxis: {
                        tickFormat: function(d) {
                            return d3.format(',d')(d);
                        }
                    },
                    rightAlignYAxis: true,
                    forceY: [0],
                    refreshDataOnly: true
                },
                title: {
                    enable: true,
                    text: "Message Throughput"
                }
            };
```

**Comment by JesseDahl** [comment]
@Sheparzo ,
If you put a scope variable as the value of the text attribute, it won't update the chart automatically, even if you don't set refreshDataOnly to true like I did above.

But you can place a watch on the scope variable you want to use as the title, and then explicitly set the text attribute (using my example above as a starting point). Let's assume your dynamic chart title is stored in vm.bla, then you can just do this.

```
$scope.$watch('vm.bla', function() {
            console.log('watch called');
            vm.throughput.options.title.text = vm.bla;
});
```

**Comment by Sheparzo** [comment]
Thanks @JesseDahl.  I see that your solution would work.  However I abandoned the angular-nvd3 title and instead just went with a straight up regular angular bound heading above the chart.
