### ISSUE TITLE
adding new chart data without redrawing the entire chart?

### ISSUE THREAD

**Issue by merrill77** [krispo/angular-nvd3#187]
This seems like a great lib, at first glance. Only took me a few minutes to get it integrated into our app. Great work!

I _think_ what I'm seeing is the the chart re-drawing entirely when I add new samples to the dataset (which we do every 2 seconds...so it is flashing constantly).

The docs seem to indicate support for real-time charts like this...specifically the "refreshDataOnly" option: "Refresh chart with data only, and without refreshing the full directive. It is especially useful for real-time updated charts."

I've set this option true both on the $scope.options and $scope.options.chart objects (thinking there it might be a more global setting), but the entire chart still flashes.

I forked the Line Chart plunker to provide an example:
  http://plnkr.co/edit/rotDuu

I've also tried pushing a separate chart data object (not in $scope) to the chart using $scope.api.updateWithData(chart_data), with no apparent change in behavior.

So I feel like either I'm doing something stupid or I'm missing a key concept in how this package operates. Any pointers would be much appreciated!

TIA,
Chris

**Comment by jlwerenskjold** [comment]
Easy Fix! In your html add ```config="{refreshDataOnly: true}"``` to your nvd3 tag. Your nvd3 tag would then look like this:
 ```<nvd3 options="options" data="data" class="with-3d-shadow with-transitions" config="{refreshDataOnly: true}"></nvd3>```

**Comment by krispo** [comment]
Yep. And also there is an example with real-time chart:
http://plnkr.co/edit/yKFROu?p=preview

**Comment by CautemocSg** [comment]
@merrill77 @krispo 

In case anyone has a situation like mine in which I have a donut chart and the data being returned is a whole new array instead of adding a single data point, here is an example of how to keep it real-time:

http://plnkr.co/edit/AwkX2FW0GGMzwplyTQMS?p=preview

If anyone has feedback on the method I'm using or know of a more efficient way, let me know.

**Comment by stenou** [comment]
@CautemocSg @merrill77 @krispo 

Modifying the scope.api.update function like below works for me.  This way when a new array is returned it will just update the chart with no animation.

    // Update chart layout (for example if container is resized)
    update: function() {
        //scope.chart.update();
        d3.select(element[0]).select("svg").datum(scope.data).call(scope.chart);
    },

**Comment by stenou** [comment]
Instead of calling scope.chart.update when the refreshDataOnly attribute is true I changed it to 

     d3.select(element[0]).select("svg").datum(scope.data).call(scope.chart);

This allows the data to be updated without the chart being redrawn.


Final code below
    
    //  Added a new function to make the code easier to read
    function myUpdateData() {
        d3.select(element[0]).select("svg").datum(scope.data).call(scope.chart);
    }

    // Replaced scope.chart.update in the watch data section
    if (!scope._config.disabled && scope._config.autorefresh) {
         scope._config.refreshDataOnly && scope.chart.update ? myUpdateData() : scope.api.refresh(); // if wanted to refresh data only, use chart.update method, otherwise use full refresh.
    }

**Comment by stenou** [comment]
I updated to the latest version 1.0.1 and this issue is fixed.  No workaround required.

**Comment by TrueMan777** [comment]
Since the version 1.0.2 you should also set deepWatchData as true. There was a commit on 15/09/2015 and this option now by default is false which means that Angular's watch expression will not track changes in array with data.

Now instead of:
```<nvd3 options="options" data="data" class="with-3d-shadow with-transitions" config="{refreshDataOnly: true}"></nvd3>```

should be:
```<nvd3 options="options" data="data" class="with-3d-shadow with-transitions" config="{refreshDataOnly: true, deepWatchData: true}"></nvd3>```

**Comment by anilkanike** [comment]
I tried with above options and did not help. My graph (lineChat) is not refreshing automatically. can someone please provide pseudo code with angularjs

**Comment by catiamatos1991** [comment]
I'm with the same problem with a pieChart:

controller

```
var options = {
				
chart: {
					type: 'pieChart',
					height: 500,
					width:1000,
					margin : {
						top: 20,
						right: 20,
						bottom: 50,
						left: 55
					},
					legend: {
                        rightAlign:false,
                    },
					valueFormat: function(d) {
						return d3.format('.2%')(d/totalValues); 
					},
					x: function(d){return d.label;}, 
					y: function(d){return d.value;},
					showValues: true,	//Display pie labels
					legendPosition: 'right',
					useInteractiveGuideline: true,
					labelType: 'percent',	//Configure what type of data to show in the label. Can be "key", "value" or "percent"
					
                    donut: true,		//Turn on Donut mode. Makes pie chart look tasty!			
					donutRatio: 0.35,     //Configure how big you want the donut hole size to be.
					duration: 500,
					xAxis: {
						axisLabel: ''
					},
					yAxis: {
						axisLabel: 'Total',
						axisLabelDistance: -10
					},
					legend: {
						updateState: true,
						dispatch: { 
							stateChange: function(e) {
								console.log('e: ' + e.disabled);
								console.log('e size: ' + e.disabled.length);
								var index=-1;
								for(var i=0; i<e.disabled.length;i++){
									if(e.disabled[i]==true){
										index=i;
									}
								}
								
								//resize pie slices
								
								var totalVal = 0;
								for(var i=0; i<$scope.data.length; i++){
									if(i == index){
										continue;
									}else{
										totalVal += $scope.data[i].value;
									}
								}
								
							$scope.dataConsNetfilter.types[0].options.chart.valueFormat = function (d){
									return d3.format('.2%')(d/totalVal);
								}
							}
						}
					}
				}
			}
```

View:

<center><nvd3 options='graph.options' data="graph.data" api="rc.api" config="{refreshDataOnly: true, deepWatchData: true}"></nvd3></center>


When i disable a label like in the example the percentage is not updated... anyone can help me? 

Image: https://i.stack.imgur.com/hY8X1.png
