### ISSUE TITLE
DiscreteBarChart YDomain display issue

### ISSUE THREAD

**Issue by edesr1988** [krispo/angular-nvd3#189]
When I set custom values for yDomain and I have both negative and positive values the bars for the positive values do not start at 0 but at the minimum of the y-axis.

Just add the following statement to this plunker (http://plnkr.co/edit/6t5bky?p=preview)
$scope.options.chart.yDomain = [-100,200];

and you'll get results like in the image attached.
![demo](https://cloud.githubusercontent.com/assets/6791999/8980706/f313df44-36b2-11e5-96db-8f5022de1c87.jpg)

**Comment by krispo** [comment]
It's a core nvd3 bug.
Try to use `forseY([-100, 200])` option instead of `yDomain[[-100, 200]]`.

**Comment by edesr1988** [comment]
okay forceY works. Is it already investigated on nvd3 side?

**Comment by edesr1988** [comment]
forceY works for me.
