### ISSUE TITLE
Interactive Guide Line tooltip header on stacked area chart not showing date (NaN--0NaN instead)

### ISSUE THREAD

**Issue by jsmanrique** [krispo/angular-nvd3#194]
I have a stacked area chart defined as:
```javascript
$scope.options = {
    chart: {
      type: 'stackedAreaChart',
      x: function(d){return d[0];},
      y: function(d){return d[1];},
      useInteractiveGuideline: true,
      xAxis: {
        tickFormat: function(d){
          return d3.time.format('%e-%b-%Y')(new Date(d*1000));
        }
      },
      yAxis: {
        tickFormat: function(d){
          return d3.format(',.0f')(d);
        }
      },
      controlOptions: ["Stacked", "Expanded"],
    }
  };
```

But, once I draw it, the tooltip header appears as `NaN--0NaN`. I think it is an issue with `tickFormat` function in `xAxis` but I haven't been able to get it.
![stacked-area-dates-issue](https://cloud.githubusercontent.com/assets/1178305/9088899/c1a1187a-3b92-11e5-825b-13928b4e72e2.jpg)

**Comment by scne** [comment]
@jsmanrique have you any solution? I have same problem

**Comment by kouddy** [comment]
I saw this problem on Firefox version 40.0.2

**Comment by kouddy** [comment]
Apparently this is a bug with nvd3.js
https://github.com/novus/nvd3/issues/1081

**Comment by sean-macfarlane** [comment]
Thanks to @kouddy directing me to the nvd3 issue I was able to discover that it passes the values as type String to tickFormat for displaying the Tooltips. 
Therefore I was able to come up with this solution: 

```
 xAxis: {
          axisLabel: 'Day',
          tickFormat: function (d) {
               if (typeof d === 'string') {
                   d = parseFloat(d);
               }
               return d3.time.format('%m/%d/%y')(new Date(d));;
          },
       },
```
This will prevent new Date(d) from returning NaN as new Date() requires a int/float type parameter
