### ISSUE TITLE
Line Chart Cropped on Internet Explorer 11

### ISSUE THREAD

**Issue by dacox** [krispo/angular-nvd3#200]
If I go to the official documentation site for v0.1.1 the Line Chart renders correctly.
http://krispo.github.io/angular-nvd3/0.x/#/lineChart
However, when I visit the site for v1.0.0-rc.2, the bottom half of the chart is missing.
http://krispo.github.io/angular-nvd3/#/lineChart
Here is an imgur album showing the problem:
http://imgur.com/a/NdQww

**Comment by krispo** [comment]
Thanks, this issue will be fixed in the new release (1.0.3).

**Comment by dacox** [comment]
Excellent, thanks!
