### ISSUE TITLE
How to draw the horizontal dashed line in the cumulative line chart ?

### ISSUE THREAD

**Issue by destiny1020** [krispo/angular-nvd3#201]
![image](https://cloud.githubusercontent.com/assets/1468925/9280281/daa53068-42ef-11e5-98e1-b36dab21f8f1.png)

Would you please teach me how to draw such dashed horizontal lines ?
Many many thanks !

**Comment by destiny1020** [comment]
I am sorry...
I have seen it in the code, defined as the average property... 
Thanks !

**Comment by JonKragh** [comment]
@destiny1020 do you have an example of this? I'm looking to do this on a horizontal bar chart.  Thanks!

**Comment by destiny1020** [comment]
@JonKragh  Do you mean the dashed horizontal line ?
If you mean this, can refer to: http://plnkr.co/edit/iIxJT3?p=preview
In the app.js file, there defined a function: average: function(d) { return d.mean/100; }
This is how to generate the dashed line.

Thanks !

**Comment by aargiriou** [comment]
hi,
If i want to use the same result, but for the box plot chart, how can i do so?

Thanks!
![original](https://cloud.githubusercontent.com/assets/8590753/18085602/7a7314ca-6eb4-11e6-882e-233ca0e352f2.jpg)
