### ISSUE TITLE
Custom Tool tip text

### ISSUE THREAD

**Issue by Sutikshan** [krispo/angular-nvd3#207]
How can we use custom toolTipContent to shos customized tool tip content. I am trying, but tooltipshow event is is not working, even if I set useInteractiveGuideline: false
My options are

    var toolTipContent = function() {..//returns html string.}
    $scope.options = {
        chart: {
            type: 'lineChart',
            height: 450,
            margin: {
                top: 20,
                right: 20,
                bottom: 40,
                left: 55
            },
            x: function(d) {
                return d.x;
            },
            y: function(d) {
                return d.y;
            },
            useInteractiveGuideline: false,                
            dispatch: {
                tooltipShow: function(e) {
                    console.log(e);
                    console.log("tooltipShow"); //not getting fired.
                    toolTipContent();
                },
                tooltipHide: function(e) {
                    console.log("tooltipHide");
                }
            },

            xAxis: {
                axisLabel: 'Date Time',
                tickFormat: function(d) {
                    return d3.time.format('%d-%b-%Y')(new Date(d));
                }
            },
            yAxis: {
                axisLabel: '', //todo
                tickFormat: function(d) {
                    return d3.format('.02f')(d);
                },
                axisLabelDistance: 30
            }
        }
    };

**Comment by Sutikshan** [comment]
These two thread helped me :- 
https://github.com/krispo/angular-nvd3/issues/77
https://github.com/krispo/angular-nvd3/issues/31

**Comment by ehartford** [comment]
can you please show how you made it work?  I have been trying all day

**Comment by krispo** [comment]
`contentGenerator` function is used for custom tooltips in the latest nvd3 version. Check also this #281.
Also I've created a [demo](http://plnkr.co/edit/gUf5Yx?p=preview).

**Comment by ehartford** [comment]
Thank you!  Works perfect!
