### ISSUE TITLE
Change color to a specific bar

### ISSUE THREAD

**Issue by MurphyHC** [krispo/angular-nvd3#208]
I tried  with this and callback 
``` $scope.options.chart.color = function (d) { ... ```  but didn't work !!
Now i'm trying  with  
```
d3.selectAll("rect.nv-bar").style("fill", function (d, i){
    console.log(d, i);               
    return i == 50 ? "#FF4500":"#0000FF";
}); 
```
It works for a moment, but, when i'm interacting with the chart, the colors change by default.
I'm using 'linePlusBarChart' with focus tool. I want to indicate that, the last bar is a result

Thanks!

**Comment by wmbutler** [comment]
Same issue here.

**Comment by MurphyHC** [comment]
Hey man, I solved the problem in this way. (I run that function into a successful request)

```
# 
$Api.summary.tower(params, function (r, status) {
   if (status === 200) {
       $timeout(function () {
           $scope.$apply(function () {
               // # 1. I feed my chart with data that must be displayed. 
               $scope.chart.data[0].values = r.summary_tower;
               
               // # 2. I put at the end an additional value, which will be the result column and have a different color. (I need in this way)
               $scope.chart.data[0].values.push({
                   end_timestamp: "1420106192.9213",
                   download_sum: response.result
                }); 
               
                // # 3. I do a for each to  fill column according to the condition.
                angular.forEach($scope.chart.data[0].values, function (value, index){
                    if (value.download_sum == response.result){
                        value.color = "#fa5524"; // 
                    } else {
                        value.color = "#0000FF";
                    }
                    $log.log("val : ",value)
                })
            });
       }, 0);
    }
});  

```

note that  "response.result"  is a value that I get from  another api request.

I hope it helps in something

**Comment by wmbutler** [comment]
@MurphyHC Can you show the d3 chart side of that? Specifically the `color:` attribute?

**Comment by MurphyHC** [comment]
![captura](https://cloud.githubusercontent.com/assets/6413024/10236518/1e145008-686c-11e5-9009-03421d92c5a7.JPG)
Here it is ! @wmbutler

**Comment by wmbutler** [comment]
Ah,

ok, so you had to apply the function to the 'fill' attribute of the chart instead of the color attribute...got it. Thanks. Was this the d3 code you ended up using?

```
d3.selectAll("rect.nv-bar").style("fill", function (d, i){
    console.log(d, i);               
    return i == 50 ? "#FF4500":"#0000FF";
}); 
```
