### ISSUE TITLE
Mouseover on scatterChart point + a $digest cycle causes the chart to refresh

### ISSUE THREAD

**Issue by EoinGriffin-AI** [krispo/angular-nvd3#210]
Mousing over any point on a scatter chart will trigger a $watch in angular-nvd3 that refreshes the chart, causing a very noticeable flicker as it re-renders.
This would go undetected until a $digest cycle runs, and then the chart will refresh (I found this issue by adding an ngClick directive to the `<nvd3>` element) .

![](http://i.stack.imgur.com/v1RK3.gif)

Here's the `$watch`:
https://github.com/krispo/angular-nvd3/blob/master/dist/angular-nvd3.js#L328

I've worked around this by using a config object like this: `{ deepWatchData: false }`
Check out this plunker here for a code example: http://plnkr.co/edit/c5k9L5axNzhgVSjJAPaV

angular-nvd3 : v1.0.0-rc.2
nvd3 : 1.8.1
d3 : 3.5.6

**Comment by krispo** [comment]
thanks, since v1.0.2 `deepWatchData` is `false` by default.
