### ISSUE TITLE
MultiChart - Invalid value for <g> attribute

### ISSUE THREAD

**Issue by staklau** [krispo/angular-nvd3#211]
My nvd3 multichart keep complaining about an invalid <g> attribute: 

Error: Invalid value for <g> attribute transform="translate(0,NaN)"

Even if I stringify the $scope.data from the example code and "re-use" it manually in the $scope.data, I get this error. Right now my code looks like this:

$scope.options = {
             chart: {
                 type: 'multiChart',
                 height: 450,
                 margin : {
                     top: 30,
                     right: 60,
                     bottom: 50,
                     left: 70
                 },
                 color: d3.scale.category10().range(),
                 //useInteractiveGuideline: true,
                 transitionDuration: 500,
                 xAxis: {
                     tickFormat: function(d){
                         return d3.format(',f')(d);
                     }
                 },
                 yAxis1: {
                     tickFormat: function(d){
                         return d3.format(',.1f')(d);
                     }
                 },
                 yAxis2: {
                     tickFormat: function(d){
                         return d3.format(',.1f')(d);
                     }
                 }
             }
         };

         $scope.data = [
           {
             key: "price",
             originalKey: "price",
             type: "line",
             yAxis: 1,
             seriesIndex: 0,
             values: [
               {
                 x:0,
                 y:1000,
                 index: 0,
                 seriesIndex: 0,
                 series: 0
               },
               {
                 x:1,
                 y:300,
                 index: 1,
                 seriesIndex: 0,
                 series: 0
               },
               {
                 x:2,
                 y:4000,
                 index: 2,
                 seriesIndex: 0,
                 series: 0
               },
               {
                 x:3,
                 y:5000,
                 index: 3,
                 seriesIndex: 0,
                 series: 0
               }
             ]
           }
         ];

Please help me solve this problem.

**Comment by krispo** [comment]
MultiChart should contain at least 2 charts, one for `yAxis: 1`, and one for `yAxis: 2`. If you want to use the only line chart, maybe it should be easier to use a simple line chart...

**Comment by AnthonyTsang** [comment]
@krispo It makes problems.
I have a chart which allows dynamically adding and remove lines on it. When there are 2 lines, one for `yAxis: 1` the other one for `yAxis: 2`. When the user removes the second line, the chart is not showing correctly.
