### ISSUE TITLE
Pie Chart & labelsOutside options

### ISSUE THREAD

**Issue by xingped** [krispo/angular-nvd3#215]
There's three different options for labelsOutside - labelsOutside, pieLabelsOutside, and donutLabelsOutside. On the pie chart in your sandbox: http://krispo.github.io/angular-nvd3/#/pieChart the labelsOutside option does absolutely nothing. Alternatively if you go into Extended mode, pieLabelsOutside ALSO does nothing, but instead donutLabelsOutside is the option to move labels outside the chart. This shouldn't happen as the chart in the data below is clearly defined as type: pieChart.

This is also all exactly the same on a donutChart. The labelOutside and pieLabelsOutside do nothing and donutLabelsOutside moves the labels outside the chart.

**Comment by krispo** [comment]
pieLabelsOutside and donutLabelsOutside are deprecated. `labelsOutside` is what you need. But in extended mode all these options affect on chart. If you define only `labelsOutside`, everything will be fine.
