### ISSUE TITLE
Zoom directive

### ISSUE THREAD

**Issue by tejaspathak** [krispo/angular-nvd3#216]
I am new to js programming and this project. I want to allow pan and zoom feature on scatter chart. It seems it is not possible to do currently with this project. Is that correct ?

Is community planning to expose d3 zoom behavior as directives ? 

Thanks

**Comment by kepler-42** [comment]
@krispo can you please let us know your views on this ?

**Comment by Jamby93** [comment]
+1

**Comment by tejaspathak** [comment]
feature is merged for scatterChart
