### ISSUE TITLE
Can I create chart which included 2 line + 1 bar by lineplusbarchart?

### ISSUE THREAD

**Issue by truyen93** [krispo/angular-nvd3#217]

**Comment by krispo** [comment]
Yes, just add an additional line element into data array, like:
```
$scope.data = [
    {
        "key" : "Bar Chart" ,
        "bar": true,
        "values" : [ ... ]
    },
    {
        "key" : "First Line Chart" ,
        "values" : [ ... ]
    },
    {
        "key" : "Second Line Chart" ,
        "values" : [ ... ]
    }
]
```

**Comment by truyen93** [comment]
hi krispo,
Thank for your help.
I added it to my code. the chart was added 1 more line but when I click to disable a line, 2 line disabled.  It's like 2 line is a object not twice.
One more question: Can I use only 1 yaxis and remove forcus bar?

Please help me :(
