### ISSUE TITLE
Repeated X axis Values

### ISSUE THREAD

**Issue by karthikSwaminithan** [krispo/angular-nvd3#218]
Line Chart
type: lineChart

I have to plot data in line chart from Sep 1 2015 to Sep 3 2015. The x axis should display Sep 1 , Sep 2 and Sep 3, but it displays each twice how to remove the repeated x axis values.

**Comment by karthikSwaminithan** [comment]
![image](https://cloud.githubusercontent.com/assets/6240879/9785821/d1976b6a-57d2-11e5-9cfa-b251efea20e8.png)

The graph contains data from july 2 to july 12 but the x axis shows only July 2 and one more issue is that i am getting an exception "Uncaught TypeError: Cannot read property 'data' of undefined".

[{"key":"Windows","values":[{"x":1435708800000,"y":8},{"x":1435795200000,"y":9},{"x":1435881600000,"y":8},{"x":1435968000000,"y":8},{"x":1436054400000,"y":9},{"x":1436140800000,"y":9},{"x":1436227200000,"y":8},{"x":1436313600000,"y":8},{"x":1436400000000,"y":9},{"x":1436486400000,"y":9},{"x":1436572800000,"y":7},{"x":1436659200000,"y":8}],"area":true,"color":"#0CB3EE"},{"key":"Android","values":[{"x":1435708800000,"y":8},{"x":1435795200000,"y":8},{"x":1435881600000,"y":8},{"x":1435968000000,"y":7},{"x":1436054400000,"y":8},{"x":1436140800000,"y":6},{"x":1436227200000,"y":8},{"x":1436313600000,"y":7},{"x":1436400000000,"y":6},{"x":1436486400000,"y":6},{"x":1436572800000,"y":8},{"x":1436659200000,"y":8}],"area":true,"color":"#93CB1E"},{"key":"IOS","values":[{"x":1435708800000,"y":8},{"x":1435795200000,"y":7},{"x":1435881600000,"y":8},{"x":1435968000000,"y":9},{"x":1436054400000,"y":7},{"x":1436140800000,"y":9},{"x":1436227200000,"y":8},{"x":1436313600000,"y":9},{"x":1436400000000,"y":9},{"x":1436486400000,"y":9},{"x":1436572800000,"y":9},{"x":1436659200000,"y":8}],"area":true,"color":"#383838"}]
this is my data please help in the same as soon as possible

**Comment by krispo** [comment]
I've create a plunk for your data, check it: http://plnkr.co/edit/x8tt97?p=preview
also, use `ticks` option for setting the number of ticks on axis

**Comment by karthikSwaminithan** [comment]
Thanks. The library is great but the problem is how to utilize the properties. Small suggestion is to have a detailed document of all properties in all charts.

**Comment by krispo** [comment]
some piece of documentation [here](http://nvd3-community.github.io/nvd3/examples/documentation.html)
