### ISSUE TITLE
Error when updating to Angular 1.3 (multiple directives asking for isolated scope)

### ISSUE THREAD

**Issue by dsine-de** [krispo/angular-nvd3#22]
I just tried to use angular-nvd3 with Angular 1.3 and I got this error (it worked with angular 1.2):

```
Error: [$compile:multidir] Multiple directives [ngController, nvd3] asking for new/isolated scope
```
- Is this caused by a problem in my code which needs to be changed for 1.3 or in the angular-nvd3 directive?
- Should I use the rewrite branch (2.0) of the "nvd3" library / is this issue already addressed there?

**Comment by Mokeponi** [comment]
Has anyone come up with a solution to this? I experience the same issue when going from upgrading to angular1.3
