### ISSUE TITLE
Which Version to use?

### ISSUE THREAD

**Issue by karthikSwaminithan** [krispo/angular-nvd3#221]
We have an issue with the tooltip, Which version we should use for an error free charts.

**Comment by krispo** [comment]
Currently, use `v1.0.1` (for nvd3 v1.8.1), or `v0.1.1` (for old nvd3 v1.1.15-beta)

**Comment by karthikSwaminithan** [comment]
Thanks and can you give a solution for #218 issue. Since we are stuck in this issue.
