### ISSUE TITLE
Consider defaulting deepWatchData to false

### ISSUE THREAD

**Issue by DefinitelyCarter** [krispo/angular-nvd3#225]
deepWatchData comes with a huge performance impact as it makes a copy of the data. I noticed #75 had the same finding and added config option.  It seems that 99% of the time you would want to default this to false.

**Comment by krispo** [comment]
Thanks! It makes sense. I'll change it.

**Comment by krispo** [comment]
In the latest release [1.0.4+] we came back to `deepWatchData=true` by default, since agility is a major feature for most of the cases. But performance we can regulate now using `deepWatchDataDepth` config, or via `api` as it was before.

**Comment by DefinitelyCarter** [comment]
Thank you for the heads up :+1:
