### ISSUE TITLE
multichart + scatter

### ISSUE THREAD

**Issue by pierrearb** [krispo/angular-nvd3#227]
nvd3 allows to use scatter plot with multibar chart (https://github.com/novus/nvd3/blob/master/src/models/multiChart.js), it would be great to update this functionnality in angular-nvd3

**Comment by krispo** [comment]
Scatter chart appeared in the current development version of nvd3 (v1.8.1-dev). After release, this functionality will be added. Thanks.

**Comment by pierrearb** [comment]
thanks!

**Comment by 4tuneTeller** [comment]
Is this feature has been added yet? Tried to replace some 'bar' charts with 'scatter' in your plnkr for the multiChart but that had no intended effect. Or maybe I am missing something? Thank you in advance.
