### ISSUE TITLE
legend positions and size issue with pieChart in particular and example of workaround to solve the issue

### ISSUE THREAD

**Issue by azatoth** [krispo/angular-nvd3#229]
Had to make a pie graph over some values, and certain labels where pretty long.
The demand was for the chart to be around 200px of height and the legend to be on the right side.
Sadly I hit issue here with nvd3 due to some funky issues with linebreaks (or more the lack of them); Thus I decided to make a hack to circumvent the issue and make something that was OK for the customer.

Following is a plunker which shows the issue, and how I solved the issue in this instance. It might be better ways to do it, but I felt it looked nice with the tooltip. Sadly the tooltip isn't as smooth as when you see it on the graph (probably due to debounching).

http://embed.plnkr.co/TJqjjkHaD2S0VjsGmN3c/preview

Regards,

Carl

**Comment by krispo** [comment]
Hey, it looks awesome! I'll add this to examples.

**Comment by ankit1329** [comment]
Is there anyway that I can decrease size of furious legends?
Legends look very large as my pie chart size is small.
