### ISSUE TITLE
Allow x values as array

### ISSUE THREAD

**Issue by jocluz** [krispo/angular-nvd3#230]
Hello. I want to create a simple line chart, with x values binded to xArray and y values bindid to an array of objects with key, value. I mean:

x = [1,2,3,4]
y = [
        { 'Key': 'Serie1', Values:[y1,y2,y3,y4] }
       { 'Key': 'Serie2', Values:[y5,y2,y8,y9] }
]
Is any way to achieve this?

Can I create 3d charts?

Thank you in advance,
Josefina.

**Comment by krispo** [comment]
Hi, if you want to use just an indices for x values, you can use the data format as you provided:
```js
$scope.data = [
    { key: 'Serie1', values:[y1,y2,y3,y4] }
    { key: 'Serie2', values:[y5,y2,y8,y9] }
]
```
and using options you can define the way how to get x and y values:
```js
x: function(d, i){ return i; },
y: function(d){ return d; },
```
format for your axes is specified also via options:
```js
yAxis: {                  
    tickFormat: function(d){ return d3.format('.02f')(d); }
},
```

If the data has specific x and y values, then you should define it in a single array and specify the corresponding options, for example:
```js
$scope.data = [
    { key: 'Serie1', values:[{x: x1, y: y1}, {x: x2, y: y2}, ...] }
    { key: 'Serie2', values:[{x: x1, y: y5}, {x: x2, y: y3}, ...] }
]
```
and options:
```js
x: function(d){ return d.x; },
y: function(d){ return d.y; },
```

**Comment by krispo** [comment]
and.. 3d charts currently not supported.
