### ISSUE TITLE
Increase scatter chart points size

### ISSUE THREAD

**Issue by tcheymol** [krispo/angular-nvd3#235]
Hi ! 
In the previous version of angular nvd3, i was able to increase the size of every point in my scatter chart. Is there a way to reproduce the same behaviour in the 1.0.2 version ?

Thanks

**Comment by krispo** [comment]
Yes, nvd3 community renamed some options in the newer nvd3 version:

`size` -> `pointSize`, `shape` -> `pointShape`, `sizeRange` -> `pointRange`, `sizeDomain` -> `pointDomain`.

so currently, you should use smth like:
```js
chart: {
    pointSize: function (d) { return d.size || 1}, //by default
    pointRange: [10, 100]
}
```

**Comment by raugaral** [comment]
Doesn't work

**Comment by Stegoo** [comment]
Hey Krispo :), any update about this ? I can't get to set a size (nothing seems to change it beside Math.random() )

**Comment by krispo** [comment]
Try to play with `pointSize`, `pointRange`, `pointDomain`:
```js
chart: {
    pointSize: 20,
    pointDomain: [0, 10]
}
```
or even set range without variation
```js
chart: {
    pointRange: [200, 200]
}
```

**Comment by Stegoo** [comment]
You are right, I was able to get it work using  pointRange only. Cheers :)

**Comment by jatin-optimus** [comment]
Hello @krispo, @tcheymol  and @Stegoo,

I am working on real time updation of scatterchart.I want to clarify some points as follows:

    I have few bubbles on 1 chart and each of the bubbles have diiferent size property which gets filled into values array.

Bubble having size:0 is not behaving properly.

Can you please provide something .like i have 5 bubbles each of them having size 10,20,0,40 and 50 respectively

I am unable to produce significant difference among 5 bubbles on the basis pf size propert.

Please provide the solution/guide how can i produce the significant difference among the bubble sie value updation.

Bubble size value updation is on basis of realtime values but i am unable to see the significant difference among the bubble having sixe:0 and bubble having size:5.

Please guide.

Looking forward to your reply.

Thanks

**Comment by garretwilson** [comment]
In the [live edit for Angular-nvD3](https://krispo.github.io/angular-nvd3/#/lineChart), none of the suggestions worked for me. :(
