### ISSUE TITLE
DiscreteBar Chart x-axis overlap

### ISSUE THREAD

**Issue by xavierortiz** [krispo/angular-nvd3#237]
I am attempting to implement a bar chart that has string values on the x-axis. For the sake of an example let's assume the value is a person's firstIntial.lastName, they are differentiated in the data by an id and have a value like so:
``` 
$scope.data = [{
  values: [{ 
    id: 1,
    label: 'J. Doe',
    value: 5
  }, {
    id: 2,
    label: 'J. Smith',
    value: 13
  }, {
    id: 3,
    label: 'J. Doe',
    value: 7
  }]
}];
 ```
Is there a way to have x display the string value but the bars display separately and not overlayed like here: (just a quick change from the plunker for the chart example to give you a visual)
![image](https://cloud.githubusercontent.com/assets/9794160/10112133/74519cd2-639e-11e5-8a0a-6ae0c555faf3.png)

**Comment by krispo** [comment]
can you please provide the code of options, or plunker?

**Comment by xavierortiz** [comment]
This can be closed. Setting the xAxis tickformat as follows worked.

```
xAxis:{
  tickFormat: function (d, i) {
    var label = $scope.data[0].values[i].label;
    return label;
  }
}
```

**Comment by Vinayak1893** [comment]
Can you please provide the code of the solution.
I am having the same issue
