### ISSUE TITLE
Javascript error with Bullet Chart when resizing browser 

### ISSUE THREAD

**Issue by aaronbc** [krispo/angular-nvd3#239]
I get the following error when re-sizing the browser when a Bullet Chart is present on the page:

    SCRIPT5007: Unable to get property '1' of undefined or null reference
    File: d3.min.js, Line: 5, Column: 12736

You can recreate this on the example page:
http://krispo.github.io/angular-nvd3/#/bulletChart

**Comment by skalidindi** [comment]
Any update on this issue?

**Comment by krispo** [comment]
it's fixed in the latest version (1.0.3).
