### ISSUE TITLE
Charts no longer automatically resize/update since 1.0.2

### ISSUE THREAD

**Issue by fgladisch** [krispo/angular-nvd3#241]
Hi,

First of all: thank you for building this library!

I'm using the charts in resizable components and since the update from 1.0.1 to 1.0.2 charts no longer update when I add new data or resize the container.

angular-nvd3 1.0.1:
![screenshot from 2015-10-01 09 42 29](https://cloud.githubusercontent.com/assets/9800065/10215416/9cc1ddee-6821-11e5-8191-1e2401df6238.png)

angular-nvd3 1.0.2:
![screenshot from 2015-10-01 09 41 19](https://cloud.githubusercontent.com/assets/9800065/10215430/b5ef4266-6821-11e5-8337-1ba99d712b94.png)

Edit: I should add that setting deepWatchData to true didn't solve the problem.

**Comment by jakepens71** [comment]
I have also noticed the same since 1.0.2. I use Gridster displaying charts in widgets.

**Comment by fgladisch** [comment]
I'm using gridstack. But i doubt it's related to these grid libs, because resizing the window has no effect, either.

**Comment by berendberendsen** [comment]
Good that I checked this after having reused code from 1.0.1 with 1.02 and pulling my (increasingly turning grey) hair out because it wasn't working.

**Comment by sirago** [comment]
Any ideas on how to fix this? Trying to use this with gridster.

**Comment by the-james-burton** [comment]
I concur. I have the same problem with 1.0.2 but my symptoms are slightly different in that the chart is blank from the outset, I think because I am populating my data asynchronously with a promise.

**Comment by krispo** [comment]
Versions 1.0.2 & 1.0.3 brought much pain for people, sorry for that... In the new release v1.0.4 we found a way to get around some performance issues, and backed again to dynamic charts by default. Details in the [docs](http://krispo.github.io/angular-nvd3/#/quickstart). Thanks!
