### ISSUE TITLE
Y-Axis still displays when setting show values to false

### ISSUE THREAD

**Issue by jakepens71** [krispo/angular-nvd3#245]
scope.options = {
    chart: {
										type: 'discreteBarChart',
										x: function(d){ return d.label; },
										y: function(d){ return d.value; },
										showValues: true,
										valueFormat: function(d){
										    return d3.format('0.0f')(d);
										},
										transitionDuration: 500,
										xAxis: {
										    axisLabel: 'Year',
										    showValues: true
										},
										yAxis: {
										    axisLabel: 'Quantity of Year',
										    showValues: false,
										    color: 'transparent'
										},
										discretebar: {
											dispatch: {
												  chartClick: function(e) {},
												  elementClick: function(e) {
																
																},
												  elementDblClick: function(e) {},
												  elementMouseover: function(e) {},
												  elementMouseout: function(e) {}            
											      }
											}
									    }
									};

						

									scope.data2 = [{key: "cumulative", values: []}];
	
									

									for (var i = 0; i < data.length; i++)
									{
										//var date = moment(data[i].year, 'YYYY');
										scope.data2[0].values[i] = ({"label": data[i].year, "value": data[i].total });
									}
		

					scope.bar = function() {

						$(".nv-bar").click( function() {
		

						 	console.log($(this)); 

						});
					};
			

However, the Y-Axis values still shows up. Any ideas?

**Comment by mikyladewitt** [comment]
I don't think the `yAxis` config has a `showLabels` field. 

When I don't want the yAxis labels to show, I set `chart.yAxis.tickValues` to `0` and `chart.yAxis.showMaxMin` to `false`. I don't know if that is the proper way to do it, but it at least works as a work around.

**Comment by jakepens71** [comment]
Thank you! 

That worked perfectly I really appreciate it.
