### ISSUE TITLE
Weird Issue: angular nvd3 line chart with ionic

### ISSUE THREAD

**Issue by srbh** [krispo/angular-nvd3#249]
@krispo , I have added line chart in web and ionic both. In web chart is working fine, but same chart not showing properly in ionic. It cuts vertically in ionic not showing higher values.
I have tried lot but not able to fix.
You can see in image there are higher values like 150,100,200etc. but not able to see those values.
![bp 2015-10-08 21-12-52](https://cloud.githubusercontent.com/assets/2160978/10393986/b6ea5886-6eb1-11e5-9fc7-7f9893b901a5.png)

**Comment by srbh** [comment]
anyone there to help. I have tried a lot, but not able to fix.

**Comment by srbh** [comment]
I found something, "<g> tag inside <svg> tag getting more height than given" I think that is creating this issue. I dont know why is it happening? same code is working on web application.

**Comment by srbh** [comment]
@krispo Please help me facing weird issue

**Comment by krispo** [comment]
It's maybe resize issue.. Which ionic platform are you trying to use? I tested a simple example in ionic 'browser' platform, it works fine for me.
Can you please put some code to demonstrates this issue.

**Comment by srbh** [comment]
@krispo Thanks for response and for this wonderful directive.

my chart options:

```javascript
$scope.options = {
		    chart: {
		        type: 'lineChart',	
		        height: 350,
		        transitionDuration: 500,
		        margin : {
		            top: 10,
		            right: 20,
		            bottom: 10,
		            left: 55
		        },
		        x: function(d){ return d.label; },
		        y: function(d){ return d.value; },
		        showValues: true,		
		        useInteractiveGuideline: false,
		        xAxis: {
		            axisLabel: 'Time',
		            tickFormat: function(d) {
                        return d3.time.format('%b %e, %Y')(new Date(d))
                    },
                    showMaxMin: false,
                    staggerLabels: true
		        },
		        yAxis: {
		            axisLabel: 'Values',		            
		            axisLabelDistance: 30,
		            tickFormat: function(d) {
                        return d
                    },
		            showMaxMin: false,
		        },
		        tooltipContent:function(key, x, y, e, graph){
		        	return '<div class="graphTooltip"><h5>' + d3.time.format('%b %e, %I:%M %p')(new Date(e.point.label)) + '</h5>' +
		               '<p>' +  key + ' : <strong>' + y + '</strong></p></div>';
                },
                useVoronoi: false
		    }
		};
```


adding values in chart  
```
$scope.data[val.code].values.push({label: val.observationAddedAt, value: val.value});
```

Same thing I have used in Web application, it is working fine.

**Comment by krispo** [comment]
html code please. and what platform?

**Comment by srbh** [comment]
```html
<ion-view view-title="{{currentJournal.prompt}}">
  	 <ion-scroll zooming="true" direction="xy" style="width: 100%;height:100%;margin-top:50px">
	  	<div>
			<nvd3 options='options' data='newData'></nvd3>
		</div>
	</ion-scroll>
	
</ion-view>
```

tested in browser platform

**Comment by krispo** [comment]
also which nvd3 and directive versions?

**Comment by srbh** [comment]
/*! nvd3 - v0.0.1 - 2014-08-18 */ 

Dont know about directive version. I got file from your git repo.

Angular directive from src/ folder
and other files from lib/ folder

**Comment by krispo** [comment]
try with the recent versions:
https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.css
https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.1/nv.d3.js
https://rawgit.com/krispo/angular-nvd3/v1.0.2/dist/angular-nvd3.js

**Comment by srbh** [comment]
Same issue.

**Comment by krispo** [comment]
I couldn't catch this issue from my side...

Try to update or refresh the chart directive after adding data:
```js
$scope.data[val.code].values.push({label: val.observationAddedAt, value: val.value});
$scope.api.update(); //or $scope.api.refresh();
```
it may need `$timeout(function(){ /*code with data manipulation and chart updating*/ }, 50)` wrapping.

add api to html:
```html
<nvd3 options='options' data='newData' api='api'></nvd3>
```

**Comment by srbh** [comment]
Thanks for your time. Let me try

**Comment by srbh** [comment]
No luck with refresh and update. Same issue

**Comment by srbh** [comment]
@krispo can you provide your test code ?? So I can try exactly same.

**Comment by krispo** [comment]
here [live example](http://plnkr.co/edit/e3HZQN?p=preview).

**Comment by srbh** [comment]
Finally got solution. Its really very weird. 

In values object, You have to make sure values are going as int OR float not string.
With string, values are being plotted on page but it creates this issue only in ionic platform, I think.

Because on web application, it always works fine.

Thanks @krispo for your time.

**Comment by ungular** [comment]
Hi, I'm new to ionic, can you suggest me a basic chart system that can be implemented in ionic 2(+typescript+html+scss) ?
or can you help me to convert this nvd3 line chart to ionic 2(typescript)? Because I tried this but don't works for me.
