### ISSUE TITLE
d3 remove not used during refresh?

### ISSUE THREAD

**Issue by bryanvb** [krispo/angular-nvd3#25]
It appears that the following happens during refresh():
updateWithOptions() calls clearElement() which calls element.empty()

This removes the svg element and later updateWithData() tries to remove that same svg element using d3 but the element no longer exists. Could this be a potential problem or is it working as expected?

Thanks,
Bryan

**Comment by krispo** [comment]
I think element.empty() is a suitable way for this case, since it completely remove the content of the element including svg.
