### ISSUE TITLE
xAxis on multiChart

### ISSUE THREAD

**Issue by livingstonedell** [krispo/angular-nvd3#250]
I can't seem to be able to configure my xAxis on a multiChart.
I try to specify
```javascript
ticks: 9
````
or
```javascript
xDomain: [0, 9]
```
in several different placer (chart, chart.xAxis, chart.lines, chart.lines1, chart.lines1.xAxis...), but none of them work.

Even by using the live multiChart exemple on the website, I can't seem to be able to manage it.
Most of the time, I end up with no xAxis ticks at all! I have no idea what's going on anymore.

Anybody got a working example of such a thing?
Are there restrictions on the multiChart type when setting scales?

If there are, I suppose I shouldn't use multiChart, but, in that case, is there a way to have two yAxis on a cumulativeLineChart (that's why I'm using the multiChart)?

**Comment by krispo** [comment]
this is [example](http://plnkr.co/edit/Djotlu?p=preview) of using ticks. note, the number of ticks may be differ from specified value, since d3 always recalculates this value.
also, cumulativeLineChart doesn't support the second yAxis.

**Comment by singhvivekanand** [comment]
How to set x axis range in multiChart?

**Comment by cmorgant** [comment]
You can't force xAxis range in a multiChart although you can do with other types of chart.

I faced the same issue and as a workaround, I had to add a 'fake' point with a null value at the beginning of each serie and do the same at the end with respectively the min value and the max value.
