### ISSUE TITLE
v1.0.1 in npm

### ISSUE THREAD

**Issue by ImranAhmed** [krispo/angular-nvd3#251]
Would it possible to add v1.0.1 to the npm registry, please?

**Comment by krispo** [comment]
Done!

**Comment by ImranAhmed** [comment]
Are you sure v1.0.1 got published? I am still only seeing the follwoing two versions. Thanks.

$ npm view angular-nvd3 versions
[ '1.0.0-beta', '1.0.2' ]

**Comment by krispo** [comment]
yes, i got:
[ '1.0.0-beta', '1.0.1', '1.0.2-dev', '1.0.2' ]
