### ISSUE TITLE
How to get current chart options?

### ISSUE THREAD

**Issue by akuznetsov-gridgain** [krispo/angular-nvd3#252]
For example, I add a multiBarChart with "showControls: true".

This will show chart with two radio buttons "grouped" and "stacked".

And user can click on them and change chart appearance.

I need somehow to get current chart options and save them to database to restore then when user will comeback. 

Any ideas?

**Comment by krispo** [comment]
You can get chart object that contains all available options via `api`:
```html
<nvd3 options="options" data="data" api="api"></nvd3>
```
and in js:
```js
var chart = $scope.api.getScope().chart;
var isStacked = chart.stacked(); //if true - stacked, if false - grouped
```

**Comment by akuznetsov-gridgain** [comment]
Thanks! It works.
