### ISSUE TITLE
Sunburst chart is not updated when the data is updated

### ISSUE THREAD

**Issue by nounla** [krispo/angular-nvd3#254]
Hi,
I am using NVD3 sunburst chart and we will get the chart dynamically by selecting some parameters and time range.
if we change the time range and parameters, we are getting latest data but the chart is not rendering new data or chart is not updated.
any suggestions to render chart with new data?

**Comment by timdockins** [comment]
I get the new data, but no tooltips.

**Comment by quantoid** [comment]
Are you replacing the $scope property used as 'data' with a new object to force a refresh?

If you just modify the contents of the data object, the chart will not refresh. It only has a $watch on the property reference, not a deep watch on it's contents.

**Comment by maruiz93** [comment]
I've tried by calling api.update() and api.updateWithData() by changing the object reference and mantaining it but I couldn't refresh the chart.

With the pieChart I had no problems bu refreshing.
Any ideas of what could cause this behaviour?

**Comment by maruiz93** [comment]
I'm sorry, I forgot to give data as the argument of api.updateWithData().
It works for me even if I totally change the object data or if I modify the content and not the reference.

Nevertheless, update() method doesn't work.

**Comment by krispo** [comment]
Please, upgrade with the latest version [1.0.4]. It brings many updates and fixes, check the [docs](http://krispo.github.io/angular-nvd3/#/quickstart) for details. Now the charts are dynamic by default again. 
For sunburst chart, the suitable behavior is
```html
<nvd3 options="options" data="data" config="{refreshDataOnly: false}"></nvd3>
```
Note that `refreshDataOnly: false` means that the chart is automatically refreshed, while `refreshDataOnly: true` means that the chart is automatically updated (it's by default).
