### ISSUE TITLE
version 1.0.2 fails where 1.0.1 is working

### ISSUE THREAD

**Issue by the-james-burton** [krispo/angular-nvd3#255]
Hi, this library is great and is working well for me. However, version 1.0.2 has stopped working. 1.0.1 was fine for me. The symptoms are a blank area where there used to be a chart when viewing this page:
https://github.com/the-james-burton/atacama/blob/master/app/scripts/controllers/direct.js 

Sorry this is a bit vague but I don't have much more information at this stage.

A rollback to 1.0.1 (as the only change) and it starts working again.

**Comment by wesley-harding** [comment]
I'm having a similar issue. Looking at the release notes, it looks like this might be causing it:

> Set deepWatchData to false by default
> Added deepWatchOptions and deepWatchConfig properties

**Comment by wesley-harding** [comment]
I should add, that I went to 1.0.3 and solved this by re-enabling full refresh 

    <nvd3 data="..." options="..." config="{refreshDataOnly: false}" />

**Comment by the-james-burton** [comment]
Interesting. I will give it a go, thanks.

**Comment by the-james-burton** [comment]
Yes, I got on to 1.0.3 with your help, thanks! For me it was this in the config that did it...

```javascript
    $scope.config = {
      deepWatchData: true,
      refreshDataOnly: false
    };
```
