### ISSUE TITLE
how to make lineChart xAxis label auto newlines

### ISSUE THREAD

**Issue by larryyangsen** [krispo/angular-nvd3#256]
Hi,
I'm use the line Chart to create like the plnkr  http://plnkr.co/edit/nq5sqg?p=preview
the part of my data is 

    {
      values: [{
        x: 0,
        "label": "All Allow",
        y: 50
      }, {
        x: 1,
        "label": "Has Some ",
        y: 25
      }, {
        x: 2,
        "label": "Eat all You want",
        y: 12
      }],
      key: 'Line', //key  - the name of the series.
    }

in my options,
I make xAxis  tickValues follow the data's length 
     
    tickValues:function(d){
          var values=[];
          $scope.data[0].values.map(function(v,i){
            values.push(i);
          })
          return values
        }
and xAxis   tickFormat returns break line string

        tickFormat:function(d){
          var labels= $scope.data[0].values[d].label.split(' ');
          return labels.join('\r\n');
        }

but When it render , the xAsix tick  can not break the line
![image](https://cloud.githubusercontent.com/assets/2285928/10723817/c2679732-7bf9-11e5-93b2-495aa5924e40.png)

Is there any way to break the line??

thanks..

**Comment by mjoyce91** [comment]
What was your solution for this?

**Comment by larryyangsen** [comment]
@mjoyce91 https://github.com/krispo/angular-nvd3/issues/127
