### ISSUE TITLE
v1.0.2 and nvd3  1.8.1 version not match

### ISSUE THREAD

**Issue by kamalpatel125** [krispo/angular-nvd3#257]
Hi,

v1.0.2 should have nvd3 1.8.1 but in source it is 1.5.x. Could you please update the nvd3 version for angular-nvd3 v1.0.2 ?

Thanks 

Kamal

**Comment by krispo** [comment]
what source does have 1.5.x?

**Comment by kamalpatel125** [comment]
https://github.com/krispo/angular-nvd3/tree/v1.0.2/lib

**Comment by krispo** [comment]
it's a modification of old nvd3 lib with some fixes (v1.1.15b). Currently this folder removed since it's not relevant.
