### ISSUE TITLE
Stacked Area Chart - TypeError: Cannot read property 'y' of undefined

### ISSUE THREAD

**Issue by RichOren** [krispo/angular-nvd3#260]
There seems to be a bug in the Stacked Area Chart - TypeError: Cannot read property 'y' of undefined.

You can test it here on the Demo site.

http://krispo.github.io/angular-nvd3/#/stackedAreaChart

If you try to Click one of the stacks it doesn't do the expected behavior of displaying only the selected stack. In the console it gives you the above error.

The older demo site works correctly:

http://krispo.github.io/angular-nvd3/0.x/#/stackedAreaChart

**Comment by krispo** [comment]
I suppose it should be addressed to nvd3 core.
#169, [#1093](https://github.com/novus/nvd3/issues/1093)
