### ISSUE TITLE
scope.options.chart.transitionDuration - doesn't work 

### ISSUE THREAD

**Issue by gunlee01** [krispo/angular-nvd3#263]
Stacked area chart - I'm using it as realtime chart.

I debug on angular-nvd3.js directly, but not work.

svg.datum(data)
                .transition().duration(1)
                .call(scope.chart);

svg.datum(data)
                .transition().duration(1000)
                .call(scope.chart);

the same result
(latest version I downloaded today on master branch)

**Comment by hhoechtl** [comment]
I tested it with this Plunker: http://plnkr.co/edit/yKFROu?p=preview and it seems, that it's not an issue of angular-nvd3, but of NVD3 itself. If I switch back to version v1.2.1 of NVD3 it works and since 1.7.1 (which is the next one and currently used by angular-nvd3) it is broken.

**Comment by hhoechtl** [comment]
Ah, I found it, it's called duration now, not longer transitionDuration.
See https://github.com/novus/nvd3/commit/5412443f64b21bfff9c29db30ad3d7412f8db1a2

**Comment by krispo** [comment]
@hhoechtl , thanks, it's correct.

**Comment by gunlee01** [comment]
Thank you.
