### ISSUE TITLE
Subtitle is not rendered

### ISSUE THREAD

**Issue by mylegco** [krispo/angular-nvd3#266]
Although it works well on [the repository demo](http://krispo.github.io/angular-nvd3/#/lineChart), subtitle is not rendered by [the plunker example](http://plnkr.co/edit/lBKFld?p=preview) or any chart I build.  Any idea why that might be?

**Comment by mylegco** [comment]
It appears that

    element.find('.title')

is returning an empty array, even though a div.title is visible on-screen.

**Comment by mylegco** [comment]
Because angular's find is [limited to lookups by tag name](https://docs.angularjs.org/api/ng/function/angular.element).  The code on the repository demo must be enhanced by jQuery or something similar.  If I change the code to

    element.find('div')

The subtitle displays as expected.

**Comment by krispo** [comment]
Subtitle is fixed in the latest version. I've updated demo, thanks.

**Comment by mylegco** [comment]
I upgraded to v1.0.3, but suddenly my charts are no longer refreshing when $scope.data changes.  Any idea what that might be related to?

**Comment by krispo** [comment]
Please, upgrade to v1.0.4
in 1.0.2 and 1.0.3 charts are static by default, and it turned to be a bad idea..
from 1.0.4 we are back to default dynamic.
