### ISSUE TITLE
¿Asked dashboard tab on the official website?

### ISSUE THREAD

**Issue by juancol88** [krispo/angular-nvd3#268]
I found very interesting the way you create dynamic dashboard so let me know if you are on github the source of this or a tutorial code as performed.

Thank you for your attention.

![dashboard - angular-nvd3](https://cloud.githubusercontent.com/assets/5742495/11005341/2cd8afea-848b-11e5-9a93-d2c5acd391aa.png)

**Comment by krispo** [comment]
I added links on the page at the bottom.
