### ISSUE TITLE
Graph not showing up in Ionic when using code from Plunker demo

### ISSUE THREAD

**Issue by cmivxx** [krispo/angular-nvd3#271]
Ok, so this is probably going to be difficult to diagnose as I can't really show the code (copyrights and all), but I'm trying to use the NVD3 module for an Ionic app.  Right now I'm simply trying to use the Plunker Ionic demo to shove a temporary graph in my app.  At the moment, Inspecting the actual NVD3 tag in chrome just shows ![screen shot 2015-11-09 at 5 23 07 pm](https://cloud.githubusercontent.com/assets/2914978/11049801/93f78214-8706-11e5-9026-010dd3d92015.png) (NVD3 0px x 0px). 

I have console.log's in the different controllers and sections, and the functions from the demo both get called, the setup gets called, but it still doesn't show.  I have manually screwed with the CSS to force a 100px x 100px size with a HUGE z-index, and nothing.  

I have no idea what I am doing wrong.  Can anyone help?

**Comment by cmivxx** [comment]
Little more info:  

I completely copied your code over from plunker and it does not work on current Ionic 1.7.7/1.7.8.  I get the same result as I stated above.

Guess I'm off to do this the old angular way.

**Comment by krispo** [comment]
current ionic version is 1.1.1, [check it](http://code.ionicframework.com/) please.

**Comment by cmivxx** [comment]
$ ionic -version
1.7.7

Maybe that's the CLI?  Is it different?

**Comment by krispo** [comment]
yes it's cli...
is there any errors in console?
try to refresh chart after creation:
```html
<nvd3 options="options" data="data" api="api"></nvd3>
```
```js
$scope.options = ...;
$scope.data = ...;
$timeout(function(){
    $scope.api.refresh();
},500)
```

**Comment by cmivxx** [comment]
I'm getting an error on the refresh potion of your code.  My HTML looks like this:

```
<nvd3 options="options"  data="data"  config="config"  events="events"  api="api"></nvd3>
```

And the error is coming through in the screenshot:
![screen shot 2015-11-10 at 1 35 20 pm](https://cloud.githubusercontent.com/assets/2914978/11073405/192e599a-87b0-11e5-87c9-bd0f4a424cbf.png)

I don't have an "api" section defined at the moment, I was just running the basics off your plunker demo:
http://plnkr.co/edit/e3HZQN?p=preview

I'm sure this is both my inexperience with D3 and a bit with Angular as well.  But I really appreciate your help!

**Comment by cmivxx** [comment]
Here's the entire controller:

```
.controller('graphCtrl', function($scope, $timeout) {
	console.log("in graphCtrl");
	/* Graph Options */
	$scope.options = {
		chart: {
			type: 'discreteBarChart',
			height: 450,
			margin : {
				top: 20,
				right: 20,
				bottom: 60,
				left: 55
			},
			x: function(d){ return d.label; },
			y: function(d){ return d.value; },
			showValues: true,
			valueFormat: function(d){
				return d3.format(',.4f')(d);
			},
			transitionDuration: 500,
			xAxis: {
				axisLabel: 'X Axis'
			},
			yAxis: {
				axisLabel: 'Y Axis',
				axisLabelDistance: 30
			}
		}
	};

	/* Graph Data */
	$scope.data = [{
		key: "Cumulative Return",
		values: [
			{ "label" : "A" , "value" : -29.765957771107 },
			{ "label" : "B" , "value" : 0 },
			{ "label" : "C" , "value" : 32.807804682612 },
			{ "label" : "D" , "value" : 196.45946739256 },
			{ "label" : "E" , "value" : 0.19434030906893 },
			{ "label" : "F" , "value" : -98.079782601442 },
			{ "label" : "G" , "value" : -13.925743130903 },
			{ "label" : "H" , "value" : -5.1387322875705 }
	    ]
	}];

	$timeout(function(){
    		$scope.api.refresh();
	},500);

	$scope.config = {
	    visible: true, // default: true
	    extended: false, // default: false
	    disabled: false, // default: false
	    autorefresh: true, // default: true
	    refreshDataOnly: true, // default: true
	    deepWatchOptions: true, // default: true
	    deepWatchData: false, // default: false
	    deepWatchConfig: true, // default: true
	    debounce: 10 // default: 10
	};
})
```

**Comment by cmivxx** [comment]
and the entire HTML block:

```
        <div class="graph_sect" id="graph" ng-controller="graphCtrl">
            <nvd3 options="options"  data="data"  config="config"  events="events"  api="api"></nvd3>
        </div>
```

**Comment by cmivxx** [comment]
And the references in index.html:
```
    <link href="css/ionic.app.css" rel="stylesheet">
    <link href="lib/nvd3/build/nv.d3.min.css" rel="stylesheet">

    <script src="lib/ionic/js/ionic.bundle.js"></script>
    <script src="lib/d3/d3.min.js"></script>
    <script src="lib/nvd3/build/nv.d3.min.js"></script>
    <script src="lib/angular-nvd3/dist/angular-nvd3.min.js"></script>
     <script src="js/index.js"></script>
```

**Comment by krispo** [comment]
It seems like you are trying to define ng-controller twice. Try to remove
```html
<div class="graph_sect" id="graph">
    <nvd3 options="options"  data="data"  config="config"  events="events"  api="api"></nvd3> 
</div>
```

**Comment by krispo** [comment]
it's like there are no any definitions for `options` and `data` in the controller you trying to use...

**Comment by cmivxx** [comment]
Yeah, that didn't seem to fix it...   

So basically here's what's going on.  This started as a standard Ionic demo app (identical to the Plunker Demo), but I added a few sections to the tabs control.  Basically the tabs template now also has a div in it that sticks to the top while the tabs themselves are hidden and then there's a 3rd div set at the bottom that is an actual navigation.  Here's the file (template/tabs.html):

```
<div class="graph_pulldown">
    <div class="graph_block" ng-show="showGraph">
        <div class="graph_sect" id="graph">
            <nvd3 options="options"  data="data"  config="config"  events="events"  api="api"></nvd3>
        </div>
        <div class="temp_sect" id="temp">128&deg;</div>
    </div>
    <div class="graph_bar"></div>
    <div class="graph_controls" ng-click="showGraph = ! showGraph">
        <div class="graph_controls_temp" ng-show="!showGraph">128&deg;</div>
        <div class="graph_controls_button" ng-class="{true: 'flipUp', false: 'flipDown'}[showGraph == true]"><img src="img/white-down-arrow.svg"></div>
    </div>
</div>

<ion-tabs class="tabs-icon-only tabs-positive">

    <ion-tab icon="ion-home" href="#/tab/home">
        <ion-nav-view name="home-tab"></ion-nav-view>
    </ion-tab>

    <ion-tab icon="ion-ios-information" href="" ng-click="openModal()">
        <ion-nav-view name="ingredients-tab"></ion-nav-view>
    </ion-tab>

    <ion-tab icon="ion-home" href="#/tab/recipe_view">
        <ion-nav-view name="recipe_view-tab"></ion-nav-view>
    </ion-tab>

    <ion-tab icon="ion-home" href="#/tab/recipe_step">
        <ion-nav-view name="recipe_step-tab"></ion-nav-view>
    </ion-tab>

</ion-tabs>

<div class="navigation" ng-show="!navState()">
    <ul class="nav_control">
        <li><a href="#/tab/home"><img src="img/home-icon.svg" class="home_ico"></a></li>
        <li ng-controller="ModalCtrl" ng-click="openModal('ing')"><img src="img/white-ingredients-icon.svg" class="ingredients_ico"></li>
    </ul>
</div>
```

The top div is a "shade" that can be pulled down by selecting the control.  This section contains the graph and a temperature reading.

The second portion is the ion-tabs-class which is perpetually hidden as we don't want ALL the pages shown in the nav.

The 3rd portion is a replacement nav.  

The Nav's are showing correctly as we needed, but the graph above is where the issue lies.

I moved all of the data and options code to the MasterTabCtrl and removed the call to the controller like you had specified and still have the same result.

(index.js - Controller for tabs)
```
.controller('MasterTabCtrl', function($scope, $ionicModal, Scopes) {
  	console.log('MasterTabCtrl');
  	Scopes.store('MasterTabCtrl', $scope);
  	$scope.showGraph = true;
  	var navHidden;
  	$scope.hideNav = function() {
  		console.log("Hiding Main Nav...");
  		navHidden = true;
  	};
  	$scope.showNav = function() {
  		console.log("Showing Main Nav...");
  		navHidden = false;
  	};
  	$scope.navState = function() {
  		return navHidden;
  	};

  	/* Graph Options */
	$scope.options = {
		chart: {
			type: 'discreteBarChart',
			height: 450,
			margin : {
				top: 20,
				right: 20,
				bottom: 60,
				left: 55
			},
			x: function(d){ return d.label; },
			y: function(d){ return d.value; },
			showValues: true,
			valueFormat: function(d){
				return d3.format(',.4f')(d);
			},
			transitionDuration: 500,
			xAxis: {
				axisLabel: 'X Axis'
			},
			yAxis: {
				axisLabel: 'Y Axis',
				axisLabelDistance: 30
			}
		}
	};

	/* Graph Data */
	$scope.data = [{
		key: "Cumulative Return",
		values: [
			{ "label" : "A" , "value" : -29.765957771107 },
			{ "label" : "B" , "value" : 0 },
			{ "label" : "C" , "value" : 32.807804682612 },
			{ "label" : "D" , "value" : 196.45946739256 },
			{ "label" : "E" , "value" : 0.19434030906893 },
			{ "label" : "F" , "value" : -98.079782601442 },
			{ "label" : "G" , "value" : -13.925743130903 },
			{ "label" : "H" , "value" : -5.1387322875705 }
	    ]
	}];

	$scope.config = {
	    visible: true, // default: true
	    extended: false, // default: false
	    disabled: false, // default: false
	    autorefresh: true, // default: true
	    refreshDataOnly: true, // default: true
	    deepWatchOptions: true, // default: true
	    deepWatchData: false, // default: false
	    deepWatchConfig: true, // default: true
	    debounce: 10 // default: 10
	};
})
```

Also as I stated previously, the exact same thing happens when I try to load your demo by hand. Here's a zip of the Ionic Demo app you have in Plunker if you care to give it a shot.
https://www.dropbox.com/s/eb6m9umkttyzzvw/d3-ionic-test.zip?dl=0

**Comment by cmivxx** [comment]
Oh and here's the state call for the tabs controller:

```

  $stateProvider
    .state('tabs', {
      url: "/tab",
      abstract: true,
      templateUrl: "templates/tabs.html",
      controller: 'MasterTabCtrl'
    })
```

**Comment by cmivxx** [comment]
As a side note, I'd be happy to pay you for your help if you would like to help me dig through the actual app, I just can't post the code here for privacy reasons, though it's not like it's anything terribly special right now.  Drop me a message with your email address if you like and I will figure out how to get you the code.

**Comment by cmivxx** [comment]
Wow, this turned out to be something entirely stupid.  I had moved the code from another branch and forgot to include the nvd3 in the app creation.  I'm dumb.  Sorry for the trouble.
