### ISSUE TITLE
Hide Legend on all charts (mainly stackedArea or culmulativeLine) and change colors?

### ISSUE THREAD

**Issue by cmivxx** [krispo/angular-nvd3#274]
I know that you added a section to certain charts to hide the legend on them by defining a .config() piece, however it doesn't work with all charts.  Can you tell me how to hide the legend on stackedArea and possibly others as well?

Also, how do I define colors for the lines/areas?

Thanks a ton for your help. This is a great library!

**Comment by cmivxx** [comment]
Oh, on the stacked chart, this includes the view controls as I only want it to stay in the default "stacked" mode.

**Comment by cmivxx** [comment]
bump?

**Comment by krispo** [comment]
use options:
```js
chart {
    showLegend: false, // to hide legend
    showControls: false // to hide controls
}
```

**Comment by cmivxx** [comment]
Ahh, stupid me..   I put that code in the $scope.config{...} section which didn't seem to do diddly squat.  Worked great in the chart: {...} section tho.  

Thanks again for the help!
