### ISSUE TITLE
I am using multibar chart , the bar loses color when data is changed, pls help

### ISSUE THREAD

**Issue by chhayas** [krispo/angular-nvd3#275]
I am using multibar chart , the bar become gray if the data is updated for the bar charts .Pls help

**Comment by rcluke** [comment]
The demo has the same issue in extended mode when you click on the refresh button.
http://krispo.github.io/angular-nvd3/#/multiBarHorizontalChart

**Comment by krispo** [comment]
It's fixed in the latest release. Thanks.
