### ISSUE TITLE
Create api Registration Function Invoked When api is Set

### ISSUE THREAD

**Issue by mikyladewitt** [krispo/angular-nvd3#278]
It would be great if there were a way to set a function that was invoked once the `api` is available/set.
Right now, users often have to set timeouts to ensure the angular-nvd3 object and therefore the` api` has been created before they start to access it. 

Creating an an `onApiRegistration` method that users could set in the directive would eliminate this need as they could just wait for the registration method to be called. 

I realize that if you have the scope, you can just watch for the api variable to be set, but I often create my nvd3 charts in services that don't have access to the scope. This would provide an easy, global way for everyone to have access to the api and know exactly when the api is available.

Here's an example of what I had in mind:
###### Example Setting on Directive:
```html
<nvd3 options="options" data="data" on-register-api="apiCallback"></nvd3>
```

###### Example Directive Implementation
```javascript
.directive('nvd3', ['nvd3Utils', function(nvd3Utils) {
    return {
        restrict: 'AE',
        scope: {
        data: '=',      //chart data, [required]
        options: '=',   //chart options, according to nvd3 core api, [required]
        api: '=?',      //directive global api, [optional]
        events: '=?',   //global events that directive would subscribe to, [optional]
        config: '=?',    //global directive configuration, [optional]
        onRegisterApi: '&?' //callback function that is called with the grid api object [optional]
    },
    link: function(scope, element, attrs){
        ...
        scope.api = {...}
        scope.onRegisterApi(scope.api)
        ...
    }
```

**Comment by krispo** [comment]
Thanks, great idea! We added `on-ready` attribute in the latest release.
