### ISSUE TITLE
scope.chart.update does not refresh data, updateWithData works instead

### ISSUE THREAD

**Issue by miguelrincon** [krispo/angular-nvd3#279]
In version 1.0.3 the default of `refreshDataOnly` is `true`, which leads to trying to call `scope.chart.update()`. In line 382:

    if (!scope._config.disabled && scope._config.autorefresh) {
        scope._config.refreshDataOnly && scope.chart.update ? scope.chart.update() : scope.api.refresh();
    }
But `scope.chart.update()` does is not update my chart after is called. However `updateWithData` does work:

    if (!scope._config.disabled && scope._config.autorefresh) {
        scope._config.refreshDataOnly ? scope.api.updateWithData() : scope.api.refresh();
    }
I am using the `'stackedAreaChart'`.

**Comment by mvl0** [comment]
Can you give some examples how you resolved the refresh issue? My scatter plot only updates the first time. Every time new data are loaded, still the previous are shown. 
I use the following:

[html]
 <nvd3 options="options" api="api" data="paretoData" width="700" height="400" tooltips="true"></nvd3>

[javascript]
$http.get(url).then(function(response) {
            $scope.paretoData   = response.data;
            $scope.api.updateWithData($scope.paretoData);
        });

**Comment by krispo** [comment]
Versions 1.0.2 & 1.0.3 brought much pain for people, sorry for that... In the new release v1.0.4 all it's fixed. Now the charts are dynamic by default again. In addition, we can specify the data change detection strategy, to avoid some performance issue. Details in the [docs](http://krispo.github.io/angular-nvd3/#/quickstart).
