### ISSUE TITLE
How to set tooltipContent

### ISSUE THREAD

**Issue by eastany** [krispo/angular-nvd3#28]
Thank you for this job.
Now i try to use it define the tooltip_content, but not work.
            <pre>type: 'lineChart',
                height: 450,
                margin : {
                    top: 20,
                    right: 20,
                    bottom: 40,
                    left: 55
                },
                x: function(d){ return d.x; },
                y: function(d){ return d.y; },
                useInteractiveGuideline: true,
                tooltipContent:function(key, x, y, e, graph){
                  return '<b>TestA</b>';
                },
                dispatch: {
                    stateChange: function(e){ console.log("stateChange"); },
                    changeState: function(e){ console.log("changeState"); },
                    tooltipShow: function(e){ console.log("tooltipShow"); },
                    tooltipHide: function(e){ console.log("tooltipHide"); }
                },
                xAxis: {
                    axisLabel: '时间',
                    tickFormat: function(d){
                        return d3.time.format('%m/%d/%y %H:%M:%S')(new Date(d))
                    }
                },
                yAxis: {
                    axisLabel: 'QPS',
                    tickFormat: function(d){
                        return d3.format('.02f')(d);
                    },
                    axisLabelDistance: 30
                },
                callback: function(chart){
                    console.log("!!! lineChart callback !!!");
                }</pre>

**Comment by rosscdh** [comment]
Having a strange occurrence with the tooltips. Any advice would be appreciated.

```
chart: {
              type: 'lineChart',
              height: 250,
              margin : {
                  top: 100,
                  right: 40,
                  bottom: 100,
                  left: 90
              },
              x: function(d){
                return d[0];
              },
              y: function(d){
                return d[1];
              },
              clipEdge: true,
              useInteractiveGuideline: false,
              xAxis: {
                  showMaxMin: false,
                  axisLabel: "Date range",
                  tickFormat: function(d) {
                      //moment(d).format('LLLL');//
                      return d3.time.format('%x %X')(new Date(d));
                  }
              },
              yAxis: {
                  axisLabel: "Value"
              },
              zoom: {
                  // enabled: true,
                  // scale: 1,
                  scaleExtent: [1, 100],
                  //useFixedDomain: true,
                  useNiceScale: true,
                  // horizontalOff: false,
                  verticalOff: false,
                  // unzoomEventType: 'dblclick.zoom'
              }
          }
```


<img width="541" alt="screen shot 2016-01-05 at 08 39 54" src="https://cloud.githubusercontent.com/assets/397106/12110005/0fb6c056-b388-11e5-915c-fe528186209d.png">
