### ISSUE TITLE
Saving Selected Legend Settings

### ISSUE THREAD

**Issue by ninjatron** [krispo/angular-nvd3#287]
I was wondering if there is a way to prevent default selected legends from being applied everytime the data updates. For example if I have following lines/legends: "x, y, z" and the user selects y and z, and then updates the chart data, how can I prevent x from being visible again?

Also, would it be possible to connect legend click events to the buttons outside the chart? For example:

-----------x-y-z
-=-=--=||i-__
------------------
[CLICK THIS]

When Click This is clicked, I want a legend to be clicked. Is this possible?

Thanks.

**Comment by ninjatron** [comment]
Is there something unclear about the question?

**Comment by krispo** [comment]
Each series in data has property `disabled`, that is used for legend. You can get/set this property value from your data to manipulate the legend behaviour.
```js
$scope.data = [
    {
        values: [...],
        key: 'Sine Wave',
        color: '#ff7f0e',
        disabled: true
    },
    {
        values: [...],
        key: 'Cosine Wave',
        color: '#2ca02c',
        disabled: false
    }
];
```
If you change this data property by the button outside the chart, the legend also will be changed.

**Comment by ninjatron** [comment]
Thanks a lot my friend.
