### ISSUE TITLE
Looks like there's an issue with your index.js file?

### ISSUE THREAD

**Issue by andy-dorman** [krispo/angular-nvd3#288]
So our builds are now breaking due to a require('dist/angular-nvd3.js') which is fixed by changing to require('./dist/angular-nvd3.js') - anyone got any ideas? is it your problem, is it mine?

**Comment by krispo** [comment]
damn.. it's mine. Thanks! it will be fixed in the next release.

**Comment by andy-dorman** [comment]
Great, any idea when that will be? Days, weeks, hours?

Thanks,

Andy

**Comment by krispo** [comment]
I just released 1.0.4... So I will wait a little for community feedback on this, and in the coming days will be new release.
