### ISSUE TITLE
scope object returned in onReady callback does not have 'chart' or 'svg' property

### ISSUE THREAD

**Issue by tbartel** [krispo/angular-nvd3#290]
Based on the 1.0.4 documentation, I should be able to access the chart and accompanying SVG element directly by registering a callback like so:

```
<nvd3 options="options" data="data" on-ready="callback"></nvd3>

$scope.callback = function(scope){
    // this code will be applied once directive has been created
    // scope - is the directive internal scope
    var api = scope.api;
    var chart = scope.chart;
    var svg = scope.svg;
    // ... do smth
};
```

Actually attempting to do so results in the chart/svg variables being undefined.  See the following example:

http://plnkr.co/edit/1r2O2NLGEbJmNgpIXCx3

**Comment by krispo** [comment]
It's a bug, thanks! 
Will be [fixed](https://github.com/krispo/angular-nvd3/commit/2f5d0ccc045f0d6812e716bb3802ef4567b59df1) in the next release.

**Comment by DeoluA** [comment]
Hi @krispo 

Ran into this issue today too. _This time_, however, the `chart` and `api` could be accessed, but `svg` kept returning `undefined`.

I fixed it by adding a `setTimeout`:

```
$scope.callback = function(scope, element){
     console.log(scope.api);     //shows up fine
     console.log(scope.chart);     //shows up fine too
     console.log(scope.svg);     //shows 'undefined' here...

     setTimeout(function(){
          console.log(scope.svg);     //...but shows up fine here
     }, 2000)
})
```

Was not sure if this is a bug or not (is it?), so I'm adding this comment in case this wasn't peculiar to me...
