### ISSUE TITLE
Update NPM with fix for index.js

### ISSUE THREAD

**Issue by simonsayscode** [krispo/angular-nvd3#291]
The latest 1.0.4 from npm is still showing the following code.

require('dist/angular-nvd3.js');
module.exports = 'nvd3';

Can you update the latest copy there so that we can move from 1.0.3 to 1.0.4?

**Comment by xogeny** [comment]
:+1:
I ran into this when I tried to `webpack` with `angular-nvd3`.  I see this is fixed in the GitHub repo, but it still needs to be republished to `npm`.

**Comment by krispo** [comment]
Done, thanks. 
index.js is fixed in v1.0.5 (since npm don't allow to change old releases).
