### ISSUE TITLE
Can we color the graph area of a line chart ?

### ISSUE THREAD

**Issue by nvurgaft** [krispo/angular-nvd3#302]
I've walked the API and didn't found any way to custom color the area of a graph in a line chart, just the line itself. is it even supported ?

**Comment by krispo** [comment]
Use `color` option in data object:
```js
$scope.data = [{
    values: [...],
    key: 'Area',
    color: '#2ca02c',
    area: true
}]
```

**Comment by nvurgaft** [comment]
Thanks for responding so fast, but no, what I meant is to have both he line color and the area colors different. by default the directive colors the area in a lighter hue than that of the line. what I'm trying to achieve is to have a dark bluish line color and a light gray area.

**Comment by krispo** [comment]
You can change styles in css directly for a specific series:
```css
.nvd3 .nv-group.nv-series-0 {
  fill: lightgray!important; /* color for area */
}
```
`nv-series-i` corresponds to series with `i`-index in data object.
For line color is used `color` data property as above, but it also can be change with css.

**Comment by nvurgaft** [comment]
Thanks, it works :+1:  , maybe we should have something like this in the API ?!
