### ISSUE TITLE
custom tooltip instead of guideline one

### ISSUE THREAD

**Issue by vlenivenko** [krispo/angular-nvd3#31]
How can I create a custom tooltip and show it instead of default guideline tooltip in stackedareachart

Is it possible ? 

Thanks !

**Comment by ehartford** [comment]
I cannot get this to work in a multibar chart, is this correct?

    $scope.countsChart.options = {
      deepWatchData: false,
      chart: {
        type: 'multiBarChart',
        margin: {
          top: 20,
          right: 20,
          bottom: 45,
          left: 45
        },
        clipEdge: true,
        duration: 500,
        stacked: true,
        showControls: false,
        xAxis: {
          showMaxMin: false,
          tickFormat: d => $scope.countsChart.selectedGranularity().tickFormat(d)
        },
        yAxis: {
          axisLabelDistance: -20,
          tickFormat: d => parseInt(d).toLocaleString()
        },
        useInteractiveGuideline: false,
        interactive: true,
        tooltips: true,
        tooltipContent: function(key, x, y, e, graph) { //return html content
          return '<h3>HELLO WORLD</h3>';
        }
      }
    };

**Comment by cmorgant** [comment]
`tooltipContent` has been deprecated according to http://nvd3-community.github.io/nvd3/examples/documentation.html#multiBarChart

You should use:

```
tooltip: {
  contentGenerator: function(d) { return '<h3>HELLO WORLD</h3>'; }
}
```

**Comment by IreneArgolloDelgadillo** [comment]
I use this, but when I want to recover the value of a .json, the tooltip shows: branch name undefined, how could fix it?? help

chart: {
                type: 'discreteBarChart',
                height: 450,
                margin:
                        {
                            top: 20,
                            right: 20,
                            bottom: 50,
                            left: 55
                        },
                x: function (d) {
                    return d.label;
                },
                y: function (d) {
                    return d.value;
                },
                showValues: true,
                duration: 500,
                tooltip: {
                    contentGenerator: function(d) { 
                        return 'branch name: '+ d.branch; 
                    }
                }
            }

**Comment by cmorgant** [comment]
Your data is wrapped in the `d` object, so to access to the `branch` property, you need to go through `d.data.branch`.

**Comment by IreneArgolloDelgadillo** [comment]
true! thank you cmorgant . once more question please , is possible override the tooltip function, to adjust the color or figure of the tooltips

**Comment by cmorgant** [comment]
The `contentGenerator` function returns the html code that will be used in the tooltip.
