### ISSUE TITLE
How can I get no area filling??

### ISSUE THREAD

**Issue by GerhardKreuzer** [krispo/angular-nvd3#314]
Hi,
tried to follow the example (which I have done with nd-d3 before, but without Angular, but this time I aways get area: true and dots on my line and no grid lines. The config is the same as in my older sample, and here everything works ??
Here my code for drawing a series:

$scope.getEnergyData = 
                function () 
                {
                  infoService.fetch('energyusage/data')
                    .then(// success
                          function (data) 
                               {                           
                                 $scope.data = [
                                                {
                                                    key   : "Energy",
                                                    values: data,
                                                    area  : false
                                                }];
                               },
                          // error
                          function ()    
                               {
                                   console.log("Energy-Usage fetch failed");
                                   $scope.data = [{
                                              key    : "-------",
                                              values : []
                                            }]
                               });
                };
Whats wrong with that?

I include a screenshot of the result

With best regards

Gerhard
![area is always on](https://cloud.githubusercontent.com/assets/4210407/12356197/852f3220-bba1-11e5-8214-47ddd67bda89.PNG)

**Comment by krispo** [comment]
What nvd3 version do you use?

**Comment by GerhardKreuzer** [comment]
.. sorry. Fixed.
Forget to link the nvd3 CSS file, so some defaults were in place I guess. Working now fine.

With best regards

Gerhard
