### ISSUE TITLE
Hierarchical Bar Chart - D3

### ISSUE THREAD

**Issue by sfdeveloperhub** [krispo/angular-nvd3#321]
Does this library support the hierarchical bar chart implementation at http://bl.ocks.org/mbostock/1283663 ? As far as I reviewed the docs, couldn't find it.

**Comment by ehartford** [comment]
Angular-nvd3 is an Angular wrapper for nvd3.  Any chart that isn't provided by nvd3 will not be provided by angular-nvd3.
Here is the list of charts supported by nvd3:  http://nvd3.org/examples/index.html
