### ISSUE TITLE
tooltipContent is not working in multiBarChart

### ISSUE THREAD

**Issue by ehartford** [krispo/angular-nvd3#323]
I cannot get this to work in a multibar chart

    $scope.countsChart.options = {
      deepWatchData: false,
      chart: {
        type: 'multiBarChart',
        margin: {
          top: 20,
          right: 20,
          bottom: 45,
          left: 45
        },
        clipEdge: true,
        duration: 500,
        stacked: true,
        showControls: false,
        xAxis: {
          showMaxMin: false,
          tickFormat: d => $scope.countsChart.selectedGranularity().tickFormat(d)
        },
        yAxis: {
          axisLabelDistance: -20,
          tickFormat: d => parseInt(d).toLocaleString()
        },
        useInteractiveGuideline: false,
        interactive: true,
        tooltips: true,
        tooltipContent: (key, x, y, e, graph) => '<h1>Test</h1>'
      }
    };

Instead of my custom tooltip, the default tooltip still shows.

![image](https://cloud.githubusercontent.com/assets/1117701/12497012/17b96cb8-c04e-11e5-983e-2b841c2fdd95.png)

**Comment by ehartford** [comment]
https://www.bountysource.com/issues/30097517-custom-tooltip-is-not-working-in-multibar-chart

**Comment by ehartford** [comment]
Thank you @krispo for the answer:

    $scope.countsChart.options = {
      deepWatchData: false,
      chart: {
        type: 'multiBarChart',
        margin: {
          top: 20,
          right: 20,
          bottom: 45,
          left: 45
        },
        clipEdge: true,
        duration: 500,
        stacked: true,
        showControls: false,
        xAxis: {
          showMaxMin: false,
          tickFormat: d => $scope.countsChart.selectedGranularity().tickFormat(d)
        },
        yAxis: {
          axisLabelDistance: -20,
          tickFormat: d => parseInt(d).toLocaleString()
        },
        useInteractiveGuideline: false,
        interactive: true,
        tooltips: true,
        tooltip: {
          contentGenerator: function(e) {
            return '<h1>Test</h1>';
          }
        }
      }
    };

**Comment by krispo** [comment]
ref: answer here #207 .

**Comment by atav32** [comment]
my saviors
