### ISSUE TITLE
duration property for MultyChart

### ISSUE THREAD

**Issue by romanpopov** [krispo/angular-nvd3#325]
Hi everyone
Thanks a lot for the library.

I try to change duration property for multiChart but It does not work.
It is your example
http://plnkr.co/edit/zsNxBJ?p=preview

**Comment by ehartford** [comment]
MultiChart doesn't have Duration per the nvd3 docs
http://nvd3-community.github.io/nvd3/examples/documentation.html#multiChart

**Comment by romanpopov** [comment]
Thanks

**Comment by pavel-blagodov** [comment]
you should update your nvd3 https://github.com/novus/nvd3/pull/1635
