### ISSUE TITLE
Historical Bar With Focus Chart

### ISSUE THREAD

**Issue by sazary** [krispo/angular-nvd3#33]
Hi  
From what I've unserstood till now, it may be possible to have a historical bar with focus chart. How can I do that? Is it possible only using the `config`? If not, can you guide me to change the code to achieve it?  
The reason I need it is to show status of a relay (on/off) over an extended period. So since technically it is possible to be shown with line chart, it is more convenient using bars.  
Thanx ;)

**Comment by amolpatel** [comment]
Is there any way we can just do this for bar graph data instead of "turning off" the line part?
