### ISSUE TITLE
How to remove gridlines in multi chart ? 

### ISSUE THREAD

**Issue by venomous9** [krispo/angular-nvd3#34]
I am working with multicharts but i did not find anything to remove gridlines of multibar chart. please help.

**Comment by HectorAnadon** [comment]
@krispo is it possible to remove only the vertical gridlines?

**Comment by raunakmali** [comment]
If you want to remove all grid lines in x-axis, use

.nv-x .tick line { display: none; }

**Comment by lynnic26** [comment]
This is helpful to me
