### ISSUE TITLE
Unable to display multiple traces on chart 

### ISSUE THREAD

**Issue by jakow** [krispo/angular-nvd3#343]
Hello,

I am having an issue, which I don't know if is related to angular-nvd3 or nvd3 itself. I am unable to display two traces of data simultaneously on a line chart with or without focus bar. Although it appears on the legend and deselecting one chart reveals another, the two charts are not visible at the same time when they are both selected in legend. Please see the plunk to see exactly what I mean:

http://plnkr.co/edit/fhsLpLy6pNC79UKYBT40?p=preview

Help would be really appreciated!

Thanks,
jakow

**Comment by krispo** [comment]
Series should have different `key` in your data: {key: "test1",..}, {key: "test2"}
