### ISSUE TITLE
data from CSV returns "No Data Available"

### ISSUE THREAD

**Issue by seansimilla** [krispo/angular-nvd3#346]
Hello,
I try to use data from CSV for a chart.

I have created a simple function to format csv data into array of objects.
When I run this the chart appears only when I resize a window.
I have tried with the api.refresh but I cannot debug this.

Here is the demo: http://plnkr.co/edit/z7bPRLQoJ5x82YA0rnlY?p=preview

Many thanks for any hint 
all the best 
Sean

**Comment by krispo** [comment]
If you want to use `setTimeout`, then just wait more time for data loaded, and then use only `$scope.$apply()`:
```js
setTimeout(function(){
    $scope.$apply();
}, 400);
```

but the more accurate is to define an empty data, and then update it in d3.csv function after loading (without setTimeout):
```js
$scope.data = [];
csvData();

function csvData(){
  d3.csv("demo.csv", function(error, data) {   

    var lineAlpha = [], lineBeta = []; 

    data.forEach(function(d) {
            d.bucket = +d.bucket,
            d.lineA = +d.lineA,
            d.lineB  = +d.lineB,       	

            lineAlpha.push({"x": d.bucket,"y": d.lineA});
            lineBeta.push({"x": d.bucket,"y": d.lineB});
        });
    
    $scope.data = [
      {
        values: lineAlpha,
        key: 'Alpha',
        color: 'blue'
      },
      {
        values: lineBeta,
        key: 'Beta',
        color: 'green'
      }
    ]; 
    $scope.$apply();
  });
}
```

**Comment by seansimilla** [comment]
Dear,
Thank you very much indeed. This of course works.
Generally I am new to many things (this was my first post ever in Github). I always trying to solve problems myself but after 2 days I have given up and decided to ask hoping to get any help.

I appreciate this so much. I am a beginner but already love the work you have done.
best 
Sean

**Comment by krispo** [comment]
Welcome!
