### ISSUE TITLE
multiChart default tooltip not taking from xAxis.tickFormat

### ISSUE THREAD

**Issue by jkandasa** [krispo/angular-nvd3#347]
I using `multiChart` to different charts. xAxis timestamp. When I change `xAxis.tickFormat` is changing in xaxis but not in tooltip.

change in http://plnkr.co/edit/zsNxBJ?p=preview line# 19 (example: `return d3.format(',f')(d)+" Test";`)

**Comment by krispo** [comment]
Add `tooltip.headerFormatter` option respectively:
```js
tooltip: {
    headerFormatter: function(d){
        return d3.format(',f')(d)+" Test";
    }
}
```
