### ISSUE TITLE
box plot with Dates

### ISSUE THREAD

**Issue by asdkalluri** [krispo/angular-nvd3#350]
Hello - I'm trying to get a box plot going where my Y axis is going to be Dates. I have tried to strip dows to the bare minimum and I only see "No Data Available".
Here is the plunk : http://plnkr.co/edit/dLBxEU?p=preview 
I just want to see some Dates and I can go forward from there.

Thanks!

**Comment by krispo** [comment]
It requires `Q1`, `Q2`, `Q3`. Don't know if it's what you want or not, but check this:
http://plnkr.co/edit/ICRdDI?p=preview

**Comment by Dhiraj1411** [comment]
Hi, @krispo is it possible to replace Q1, Q2, Q3 with anything like A, B, C?
