### ISSUE TITLE
Question: How can I get the chart object?  

### ISSUE THREAD

**Issue by jduprey** [krispo/angular-nvd3#36]
Hello,

How can I get the chart object back after it has been created by the directive..

I would like to attach to the stacked chart event 
chart.interactiveLayer.dispatch.on('elementMousemove.gp', function(e) {
var xValue = chart.xAxis.tickFormat()(e.pointXValue);
...
})

Also, do you have a full example of how to hook into the chart events?
It looks like this describes it to some degree..
https://github.com/krispo/angular-nvd3/issues/32

Thank you!

-John

**Comment by soumya2080** [comment]
My scenario is on single click it should fetch data from db and update another graph and on dbl click it should navigate to a link.
But when I'm providing both single and double click events, Only single click event is working. I think it is not detecting Double Click at that time.
```
elementClick: function(e) {
                              $log.info("Single Click Event");
                          },
elementDblclick: function (e) {
                              $log.info("Double Click Event");
                          }
```

Any suggestion?
