### ISSUE TITLE
Sunburst Chart - Size makes no difference

### ISSUE THREAD

**Issue by psmod2** [krispo/angular-nvd3#369]
Hi,

I'm using a Sunburst chart however find that size is not making any difference.

To help describe this I've made this plunkr:
https://plnkr.co/edit/MdKPwDRr7UWESk46dTzH?p=preview

So if you look at the chart's last ring all are of equal even though I have different values in the size
```
"name": "Cluster1",
     "children": [
          {"name": "AgglomerativeCluster", "size": 10},
          {"name": "CommunityStructure", "size": 3},
          {"name": "HierarchicalCluster", "size": 1},
          {"name": "MergeEdge", "size": 1}
     ]
```

I want that size to effect to make a partiucalr segment bigger or smaller.

**Comment by krispo** [comment]
add `mode: 'size'` option.

**Comment by psmod2** [comment]
Awesome! Thank you.

**Comment by psmod2** [comment]
And for my future knowledge where can i see what attributes exists and what each do as i couldnt find this option?

**Comment by krispo** [comment]
There is [nvd3-community docs](http://nvd3-community.github.io/nvd3/examples/documentation.html#sunburst), and also you can look through an option tree on [Live Edit](http://krispo.github.io/angular-nvd3/#/sunburstChart) page in extended mode.
