### ISSUE TITLE
Refresh the view on data  change

### ISSUE THREAD

**Issue by vayias** [krispo/angular-nvd3#37]
Hi krispo,

I was wondering if a simple view for a line chart like :
    <div ng-controller="chartCtrl">
        <nvd3 options="options" data="data"></nvd3>
    </div>

would refresh(redraw new graph) if the data changes.

If no, is there is any way to do it?

**Comment by firoze** [comment]
I wonder if this is what you're looking for:

```
            if (nv && nv.graphs) {
                nv.graphs.forEach(function(nvGraph) {
                    nvGraph.update();
                });
            }
```

If I understood correctly, you want the refresh itself after you tweaked something in the data for the chart? Normally it updates itself but in the event it doesn't, this little snippet does the trick for me.

**Comment by house9** [comment]
@krispo :+1: for the great explanation, this helped us out big time!

**Comment by Sutikshan** [comment]
I am doing the same, but not getting chartApi variable in $scope. here is my .html - 
 <nvd3 options="options" data="data" class="with-3d-shadow with-transitions" api="chartApi"></nvd3>

There are dropdown in my page, when user changes the date-range of x Axis, it should update the chart with new date-range, in following code, block inside if never get called 

   $scope.options.forceX = [$scope.fromDate.getTime(), $scope.toDate.getTime()];
            $scope.moptions.forceX = [$scope.fromDate.getTime(), $scope.toDate.getTime()];
            if ($scope.chartApi) {
                $scope.chartApi.refresh();
                //$scope.chartApi.updateWithOptions($scope.options)
                console.log($scope.fromDate.getTime());

            }

**Comment by Tyguy7** [comment]
For anyone who might need this, I had many charts in one view, and I wanted to redraw them all when a CSS change took place.  There was no window resize event to trigger the redraws so I appended all charts' apis to a $scope.apis object, 

(my charts are created by an ng-repeat, so I have access to an $index)
```
<nvd3 options="someChart.options" data="someChart.data" api="apis['api'+$index]"></nvd3>
```

...and then called this function programmatically
```
$scope.updateCharts = function(){
    $timeout(function(){
      for(api in $scope.apis){
        $scope.apis[api].update();
      }
    }, 50);
  };
```

**Comment by chhayas** [comment]
I am facing an strange issue , in multibar chart when the data is changed , all the bar looses there color.

**Comment by fayyazurrehman** [comment]
Hi krispo,

I trying to develop a multi series line chart, the chart is not updating with updated data. Unless, until i have to refresh the whole page.

**Comment by krispo** [comment]
@fayyazurrehman , currently try to use `deepWatchData: true` in config (for the latest versions). We set this to false by default due to some performance issues, so the charts are static by default. But I find that a lot of people suffer from this and got another questions.. So, we are likely to go back to dynamic charts by default. I'm working on this.

**Comment by fayyazurrehman** [comment]
i have tried .. this is my example code; Please guide me what i am doing wrong

<!DOCTYPE html>
<head>
<meta charset="utf-8">  
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/d3/d3.js"></script>
<script src="bower_components/nvd3/build/nv.d3.js"></script> 
<script src="bower_components/angular-nvd3/dist/angular-nvd3.js"></script>
<link rel="stylesheet" href="bower_components/nvd3/build/nv.d3.css">
<script >
var model = [{ "date": "2012-01-12", "europe": "45", "asia": "40", "america": "60" },
            { "date": "2012-01-19", "europe": "20", "asia": "35", "america": "70" },
            { "date": "2012-01-25", "europe": "40", "asia": "45", "america": "62" },
            { "date": "2012-02-12", "europe": "52", "asia": "40", "america": "65" }
            ];
angular.module('myApp', ['nvd3'])
    

    .controller('MainCtrl', function($scope) {
        $scope.datalist = model;
        $scope.RETRIEVE_DEFAULT_NR = 50;
        $scope.state = {};
        $scope.state.confList = [];
        $scope.retrieveNr = $scope.RETRIEVE_DEFAULT_NR;
        
        $scope.options={};
         $scope.options1 = {
            //d3.select("#nvd3").selectAll("svg").remove();
            chart: {
                type: 'lineChart',
                height: 450,
                margin : {
                    top: 20,
                    right: 20,
                    bottom: 40,
                    left: 40
                },
                //var parseDate = d3.time.format("%d-%b-%y").parse;
                x: function(d){ return d.x; },
                y: function(d){ return d.y; },
                useInteractiveGuideline: true,
                dispatch: {},
                xAxis: {
                    axisLabel: 'Date (day-month-year)',
                    tickFormat: function(d) {
                        return d3.time.format('%d-%m')(new Date(d))
                    },
                    staggerLabels: false
                },
                yAxis: {
                    axisLabel: 'Attendees (a)',
                    tickFormat: function(d){
                        //console.log(d);
                        return d3.format('40')(d);
                    },
                    axisLabelDistance: -30
                },
                callback: function(chart){
                    console.log("!!! lineChart callback !!!");
                }
            },
            title: {
                enable: true,
                text: 'Continent-wise Attendees list'
            }
        };
        
        $scope.retrieveLastNItems = function(n) {
            
          $scope.data = datAndAttendees($scope.datalist);
        };
        
        $scope.setAndRetrieveLastNItems = function(n) {
            $scope.state.retrieveNr = n;
            $scope.retrieveLastNItems($scope.retrieveNr);
        };
      
        $scope.addNewItem = function(datetxt,europetxt,asiatxt,americatxt) {
          $scope.datalist.push({ date: datetxt, europe: europetxt, asia: asiatxt, america: americatxt});
          
          var sdata=$scope.datalist;
          console.log(sdata);
          $scope.data = datAndAttendees(sdata);


          };
      console.log($scope.data);
      $scope.options = $scope.options1;

      //$scope.data = datAndAttendees($scope.datalist);

      /*Random Data Generator */
      function datAndAttendees(adata) {
          //console.log(adata);
          var europedata=[];
          var asiadata=[];
          var americadata=[];

          var parseDate = d3.time.format("%Y-%m-%d").parse;

          //Data is represented as an array of {x,y} pairs.
          for ( var i in adata) {
              var ddate = parseDate(adata[i].date);

              var deurope = adata[i].europe;
              var dasia = adata[i].asia;
              var damerica = adata[i].america;

              //var dattendee = adata[i].attendee;
              //d.date = parseDate(d.date);

              //date.push({x:i, y:ddate});
              europedata.push({x:ddate, y:deurope});
              asiadata.push({x:ddate, y:dasia});
              americadata.push({x:ddate, y:damerica});
              
          }
          
          //Line chart data should be sent as an array of series objects.
          return [
                {
                  values: americadata,
                  key: 'America',
                  color: '#7777ff',
                  area: true 
                },
                {
                  values: asiadata,
                  key: 'Asia',
                  color: '#2ca02c',
                  area: true
                },
                {
                  values: europedata,
                  key: 'Europe',
                  color: '#ff7f0e',
                  area: true
                }

                ];
      }

    })
</script

</head>

<body ng-app="myApp" ng-controller="MainCtrl">

<div ng-init="setAndRetrieveLastNItems(15)" style="margin: auto;">

    <div  class="col-md-2">
    </div>
      <div style=" margin: auto;" class="col-md-8">
  
    
      <nvd3 options="options" data="data" api="api" config="{deepWatchData: true}"></nvd3>
  
          
        <form ng-submit="addNewItem(datetxt,europetxt,asiatxt,americatxt)">
          <fieldset>
            <input type="text" placeholder="Add date" size=10 ng-model="datetxt" />
            <input type="text" placeholder="Add europe" size=5 ng-model="europetxt" />
            <input type="text" placeholder="Add asia" size=5 ng-model="asiatxt" />
            <input type="text" placeholder="Add america" size=5 ng-model="americatxt" />
            <button class="btn btn-primary">Add item</button>
          </fieldset>
        </form>
    
        <table class="table table-striped" >
          <thead>
            <tr>Date</tr>
            <tr>Europe</tr>
            <tr>Asia</tr>
            <tr>America</tr>
          </thead>
          <tbody>
            <tr ng-repeat="item in datalist">
              <td>{{ item.date }}</td>
              <td>{{ item.europe }}</td>
              <td>{{ item.asia }}</td>
              <td>{{ item.america }}</td>
            </tr>
          </tbody>
        </table>
  
    </div>
  <div  class="col-md-2">
  </div>
</div>


</body>

**Comment by fayyazurrehman** [comment]
i have tried . this is my example code

<!DOCTYPE html>
<head>
<meta charset="utf-8">
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/d3/d3.js"></script>
<script src="bower_components/nvd3/build/nv.d3.js"></script> 
<script src="bower_components/angular-nvd3/dist/angular-nvd3.js"></script>
<link rel="stylesheet" href="bower_components/nvd3/build/nv.d3.css">
<script >
var model = [{ "date": "2012-01-12", "europe": "45", "asia": "40",
"america": "60" },
            { "date": "2012-01-19", "europe": "20", "asia": "35",
"america": "70" },
            { "date": "2012-01-25", "europe": "40", "asia": "45",
"america": "62" },
            { "date": "2012-02-12", "europe": "52", "asia": "40",
"america": "65" }
            ];
angular.module('myApp', ['nvd3'])


    .controller('MainCtrl', function($scope) {
        $scope.datalist = model;
        $scope.RETRIEVE_DEFAULT_NR = 50;
        $scope.state = {};
        $scope.state.confList = [];
        $scope.retrieveNr = $scope.RETRIEVE_DEFAULT_NR;

        $scope.options={};
         $scope.options1 = {
            //d3.select("#nvd3").selectAll("svg").remove();
            chart: {
                type: 'lineChart',
                height: 450,
                margin : {
                    top: 20,
                    right: 20,
                    bottom: 40,
                    left: 40
                },
                //var parseDate = d3.time.format("%d-%b-%y").parse;
                x: function(d){ return d.x; },
                y: function(d){ return d.y; },
                useInteractiveGuideline: true,
                dispatch: {},
                xAxis: {
                    axisLabel: 'Date (day-month-year)',
                    tickFormat: function(d) {
                        return d3.time.format('%d-%m')(new Date(d))
                    },
                    staggerLabels: false
                },
                yAxis: {
                    axisLabel: 'Attendees (a)',
                    tickFormat: function(d){
                        //console.log(d);
                        return d3.format('40')(d);
                    },
                    axisLabelDistance: -30
                },
                callback: function(chart){
                    console.log("!!! lineChart callback !!!");
                }
            },
            title: {
                enable: true,
                text: 'Continent-wise Attendees list'
            }
        };

        $scope.retrieveLastNItems = function(n) {

          $scope.data = datAndAttendees($scope.datalist);
        };

        $scope.setAndRetrieveLastNItems = function(n) {
            $scope.state.retrieveNr = n;
            $scope.retrieveLastNItems($scope.retrieveNr);
        };

        $scope.addNewItem = function(datetxt,europetxt,asiatxt,americatxt) {
          $scope.datalist.push({ date: datetxt, europe: europetxt, asia:
asiatxt, america: americatxt});

          var sdata=$scope.datalist;
          console.log(sdata);
          $scope.data = datAndAttendees(sdata);


          };
      console.log($scope.data);
      $scope.options = $scope.options1;

      //$scope.data = datAndAttendees($scope.datalist);

      /*Random Data Generator */
      function datAndAttendees(adata) {
          //console.log(adata);
          var europedata=[];
          var asiadata=[];
          var americadata=[];

          var parseDate = d3.time.format("%Y-%m-%d").parse;

          //Data is represented as an array of {x,y} pairs.
          for ( var i in adata) {
              var ddate = parseDate(adata[i].date);

              var deurope = adata[i].europe;
              var dasia = adata[i].asia;
              var damerica = adata[i].america;

              //var dattendee = adata[i].attendee;
              //d.date = parseDate(d.date);

              //date.push({x:i, y:ddate});
              europedata.push({x:ddate, y:deurope});
              asiadata.push({x:ddate, y:dasia});
              americadata.push({x:ddate, y:damerica});

          }

          //Line chart data should be sent as an array of series objects.
          return [
                {
                  values: americadata,
                  key: 'America',
                  color: '#7777ff',
                  area: true
                },
                {
                  values: asiadata,
                  key: 'Asia',
                  color: '#2ca02c',
                  area: true
                },
                {
                  values: europedata,
                  key: 'Europe',
                  color: '#ff7f0e',
                  area: true
                }

                ];
      }

    })
</script

</head>

<body ng-app="myApp" ng-controller="MainCtrl">

<div ng-init="setAndRetrieveLastNItems(15)" style="margin: auto;">

    <div  class="col-md-2">
    </div>
      <div style=" margin: auto;" class="col-md-8">


      <nvd3 options="options" data="data" api="api" config="{deepWatchData:
true}"></nvd3>


        <form ng-submit="addNewItem(datetxt,europetxt,asiatxt,americatxt)">
          <fieldset>
            <input type="text" placeholder="Add date" size=10
ng-model="datetxt" />
            <input type="text" placeholder="Add europe" size=5
ng-model="europetxt" />
            <input type="text" placeholder="Add asia" size=5
ng-model="asiatxt" />
            <input type="text" placeholder="Add america" size=5
ng-model="americatxt" />
            <button class="btn btn-primary">Add item</button>
          </fieldset>
        </form>

        <table class="table table-striped" >
          <thead>
            <tr>Date</tr>
            <tr>Europe</tr>
            <tr>Asia</tr>
            <tr>America</tr>
          </thead>
          <tbody>
            <tr ng-repeat="item in datalist">
              <td>{{ item.date }}</td>
              <td>{{ item.europe }}</td>
              <td>{{ item.asia }}</td>
              <td>{{ item.america }}</td>
            </tr>
          </tbody>
        </table>

    </div>
  <div  class="col-md-2">
  </div>
</div>


</body>




Best Regards,

Fayyaz Ur Rehman,

**Comment by fayyazurrehman** [comment]
ok i have solved it .. don't know if its the good solution but by defining

var europedata=[];
var asiadata=[];
var americadata=[];

globally it solves the issue. Any suggestion from your side to improve the code will be very heighly appreciated.
