### ISSUE TITLE
graph issue with small Y numbers

### ISSUE THREAD

**Issue by sRockx** [krispo/angular-nvd3#370]
Hi,
I'm facing an issue with drawing the line chart graph with small number in Y axis (less than 90), I've described the issue in this [Plunker](https://plnkr.co/edit/TVcqBqUK9HYjMjCw5IhA?p=preview)
I'm stuck with this for couple of days now :-(
I'll be so thankful if you could help me,
thanks in advance,
sRockx

**Comment by krispo** [comment]
The only thing you need is to convert y-values to numbers:
```js
y: function(d){ return +d.y; }
```

**Comment by sRockx** [comment]
That worked, THANKS a lot :)
