### ISSUE TITLE
Graph displays compacted until window resize

### ISSUE THREAD

**Issue by grug** [krispo/angular-nvd3#371]
Hey there,

If I have an nvd3 element in my markup with the following code:
`<nvd3 ng-show="someFlag" options="options" data="data"></nvd3>`

Assume that  `someFlag` is initialised to a false value, so my graph does not display on my screen - this is expected. However, when `someFlag` becomes true, my graph displays but is very compacted:
http://puu.sh/nxrKx/e457f43828.png <-- shows the compacted graph

The graph only displays correctly when i perform any resize on my browse window:
http://puu.sh/nxruP/11eebb8571.png <-- shows the correct size graph after resize

If I remove the flag altogether like this:
`<nvd3 options="options" data="data"></nvd3>`

The graph displays perfectly fine.

Is there a way to hide and show the graph with it keeping it's correct size?

Thanks,
Dave

**Comment by krispo** [comment]
Try to use `ng-if` instead of  `ng-show`.

**Comment by grug** [comment]
@krispo that worked - I'm just trying to work out why that worked. `ng-if` destroys the DOM element and recreates it as necessary whereas `ng-show` controls visibility with the `display` css property. It feels like you should be able to have the same outcome with either of these directives in conjunction with the `nvd3` directive. Is this a bug in nvd3 or intended behaviour?

**Comment by krispo** [comment]
check #259  and also #40 discussions
