### ISSUE TITLE
Creating a small pieChart with absolute size

### ISSUE THREAD

**Issue by johnmccabe** [krispo/angular-nvd3#372]
Hi,
I'm trying to create a small pie chart with an absolute size (40x40 px) (diameter 40px) but can't figure out how to avoid the scaling/translating thats going on.

For example - http://plnkr.co/edit/nuAI0h?p=preview

In this case the pie chart is rendered beyond the extents of the svg, if you up the width/height to say 150x150 then the chart appears in the svg but its scaled way down and doesn't fill the extents of the svg.

I'd like to be able to render the chart to fill the full 40x40 (turning off growOnHover so no extra space would be required).

Is this achievable with angular-nvd3, and are there any examples which would be useful in figuring out how to achieve this?
Thanks,
John

**Comment by krispo** [comment]
Set all margins to `0`:
```js
width: 40,
height: 40,
margin: { top: 0, right: 0, bottom: 0, left: 0 },
```

**Comment by johnmccabe** [comment]
Thanks @krispo thats **much** better, its still not perfect tho, the svg is set to 40x40, but the pie chart is a few pixels short of that (and slightly off-center).

Is there anything else that can be disabled to allow it to use the full extents?

![screen shot 2016-03-07 at 14 18 53](https://cloud.githubusercontent.com/assets/83862/13571940/a124db5a-e46f-11e5-9fbf-057be64e725e.png)

![screen shot 2016-03-07 at 14 21 14](https://cloud.githubusercontent.com/assets/83862/13572003/e4b290ce-e46f-11e5-9e83-02ff617f0385.png)

**Comment by krispo** [comment]
maybe it relates to styles.. don't know. Try with all margins = -5.

**Comment by johnmccabe** [comment]
That does the trick (plunkr in previous comment shows the update). Closing.

Thanks @krispo :+1:
