### ISSUE TITLE
tickFormat does not format the displayed values

### ISSUE THREAD

**Issue by rakia** [krispo/angular-nvd3#373]
Hello everybody,
I'm using a 'discreteBarChart' with:
`showValues: true,
 yAxis: {
				tickFormat: function(d) {
					return myLocale.numberFormat('.,4f')(d);
				}
			}`
'myLocale' has the following attributes:
`var myLocale = d3.locale({
        decimal: ',',
        thousands: '.',
        ...
    });`
The values on the yAxis are well formated and displayed with ',' as decimal separator, but the Y values on the top of the bars are not formatted and displayed with '.' as decimal separator and ',' as thousands separator.
Do you have an idea how can I get the Y values on the top of the bars formatted as I want?
Thank you!
![unformatted y values on the top of the bars](https://cloud.githubusercontent.com/assets/1866918/13633464/7abbd320-e5ef-11e5-89ec-234a02fd1d11.png)

**Comment by krispo** [comment]
add one more option
```js
chart: {
  valueFormat: function(d){
    return myLocale.numberFormat('.,4f')(d);
  }
}
```

**Comment by rakia** [comment]
Thank you very much @krispo, you've saved my life :)

**Comment by rakia** [comment]
Hi krispo,
however my defined locale "myLocale" has indicate ',' as decimal separation and '.' as thousands separation, I receive the values on the yAxis and tooltip only with the decimal separation ','. What should I do to get the format I want?
`
yAxis: {
				axisLabel: '',
				axisLabelDistance: -10,
				tickFormat: function(d) {
					return localeDE.numberFormat('.,4f')(d);
				}
			},
tooltip: {
				contentGenerator: function (e) {
				    var series = e.series[0];
                    if (series.value === null) { return; }

                    var header = '<thead>' + 
                                    '<tr>' +
                                        '<td class="legend-color-guide"><div style="background-color: ' + series.color + ';"></div></td>' +
                                        '<td class="key">' + e.data.name + '</td>' +
                                    '</tr>' + 
                                '</thead>';
				    var rows =  '<tr>' +
                                    '<td class="key">' + 'Wert: ' + '</td>' +
                                    '<td class="x-value"><strong>' + localeDE.numberFormat('.,4f')(series.value) + '</strong></td>' + 
                                '</tr>';
                    return  '<table>' +
                                header +
                                '<tbody>' + 
                                    rows + 
                                '</tbody>' +
                            '</table>';
                }
			}`
thx

**Comment by krispo** [comment]
should be `',.4f'` instead of `.,4f`!

**Comment by rkdhanyakula** [comment]
Dear @krispo 
Here I am trying to remove the decimals every where on the chart.
I tried the above , But I Cannot.

For Example : 11.0000 to only 11

Here is my Code :
<pre>
$scope.regUsersChartOptions = {
			            chart: {
			                type: 'pieChart',
			                height: 500,
			                x: function(d){return d.monthName;},
			                y: function(d){return d.monthFreq;},
			                showLabels: true,
			                "showLegend": false,
			                duration: 500,
			                labelThreshold: 0.01,
			                labelSunbeamLayout: true,
			                legend: {
			                    margin: {
			                        top: 5,
			                        right: 35,
			                        bottom: 5,
			                        left: 0
			                    }
			                }
			            }
			        };
</pre>

<img src="https://cloud.githubusercontent.com/assets/8548516/26240690/754ddf06-3cb4-11e7-8aba-0f6b9b398ba8.png"/>
