### ISSUE TITLE
Remove space between ticks

### ISSUE THREAD

**Issue by moshfeu** [krispo/angular-nvd3#378]
When I have no data for one day (or more) the graph "save" a place for the missing day. I want to avoid it.

![mbs6x](https://cloud.githubusercontent.com/assets/3723951/13780064/85ce40dc-eac6-11e5-842d-849b5182a369.png)

[plnkr](http://plnkr.co/edit/42uzlu4AjnHJpI7o41l3?p=preview)

**Comment by krispo** [comment]
Use indices instead of values in data: `x: function(d, i){return i; }`.

All options will be:
```js
$scope.options = {
    chart: {
      type: 'lineChart',
      height: 500,
      useInteractiveGuideline: true,
      x: function(d,i){ return i},
      xAxis: {
        tickFormat: function(d) {
          var data = $scope.graphData[0].values[d].x;
          return d3.time.format('%H %d/%m')(new Date(data));
        },
        rotateLabels: -45,
        tickValues: function(values) {
          var a =  _.map(values[0].values, function(v,i) {
            return i
          });
          return a;
        },
        showMaxMin: false
      }
    }
  };
```

**Comment by moshfeu** [comment]
Thanks! It's a nice solution. But now, the problem is that when I hover on the graph, the tooltip "stick" on the first column.

I was updated the [plunk](http://plnkr.co/edit/42uzlu4AjnHJpI7o41l3?p=preview) with your suggestion.

**Comment by krispo** [comment]
it seems like guideline is bound to data.. just add indices to data:
```js
values.push({
  i: j,
  x: data[j][0], // x is date
  y: data[j][i] // y is value
});
```
and change `x` option:
```js
x: function(d){ return d.i}
```

**Comment by moshfeu** [comment]
Works like charm ;) Thanks!

**Comment by Manaskumar119** [comment]
@krispo  , can the xaxis tick value be increased to 30 ? 
I think the max value is 10 .. 
Can you help me ?
