### ISSUE TITLE
Tooltips cannot be disabled

### ISSUE THREAD

**Issue by im1dermike** [krispo/angular-nvd3#381]
I am unable to disable tooltips from appearing when hovering over a chart.  This appears to be the same case in the line chart demo as well: http://krispo.github.io/angular-nvd3/#/lineChart

My expectation is that the following will disable tooltips:

    $scope.options = {
        chart: {
            tooltips: false
        }
    };

**Comment by krispo** [comment]
add also `useInteractiveGuideline: false`

**Comment by im1dermike** [comment]
Still no.  FWIW, this is a `discreteBarChart` chart.

**Comment by whittssg** [comment]
Hello, is there any other way to get tooltips disabled? I really need to disable them on one of my projects. Thanks

**Comment by krispo** [comment]
Sorry, to disable tooltip use `enabled: false` option:
```js
chart: {
  tooltip: {
    enabled: false
  }
}
```

**Comment by krysthian** [comment]
I have multiChart,  I tried what did you write here but it disable the tooltip of all charts (it's three), but I'd like to disable the tooltip of just 2 charts, how can I do it?
