### ISSUE TITLE
Line chart requires x and y axis values to be numbers?

### ISSUE THREAD

**Issue by im1dermike** [krispo/angular-nvd3#382]
I'm having trouble getting line charts to work.  I would expect to be able to switch the chart type between a bar chart and a line chart and have it work with the same data, but apparently not.  

I made a [Plunker](http://plnkr.co/edit/OjQpy6?p=preview).  As you can see, my x-axis values are strings (months).  I'm only able to get it to work if my x-axis values are numbers (ints or decimals).  This can't be the case, right?

**Comment by krispo** [comment]
x-values should be numbers, so use data indices and replace it with labels via `tickFormat`
```js
x: function(d) { return d.i; },
xAxis: {
  tickFormat: function(i){
    return $scope.data[0].values[i].label;
  },
},
```
and add indices to data
```js
var sin = [{
  "label": "Mar",
  "value": 1.4760812076162926
}, 
...
];
sin.forEach(function(d,i){
  d.i = i;
  return d;
});
```

**Comment by im1dermike** [comment]
Is there no way to access the entire data point in the `tickFormat` function rather than accessing the data set in the $scope?  I have a bunch of charts on my page and really don't want to have custom options for each chart.

**Comment by krispo** [comment]
I know it's ugly.. unfortunately `tickFormat` knows only the resulting x-value, not data object..

**Comment by meenu1** [comment]
When y-axis values are zero line chart is showing -1 on axis. It should not show. 
![line-chart](https://user-images.githubusercontent.com/4106497/79838240-51617880-83d0-11ea-830d-529b4a9c41c2.PNG)
