### ISSUE TITLE
linePlusBarChart: why are the bars directly on the y-axis

### ISSUE THREAD

**Issue by im1dermike** [krispo/angular-nvd3#383]
http://plnkr.co/edit/IqR3w8?p=preview

Why are the first and last bars of a `linePlusBarChart` chart directly on the left and right y-axes when the bars of a `discreteBarChart` chart spaced off the axes like this: (http://plnkr.co/edit/6t5bky?p=preview)?

**Comment by krispo** [comment]
There is `bars.padData` option for this, but it seems to be with a bug..
```js
bars: {
  padData: true
}
```

**Comment by im1dermike** [comment]
@krispo : Any timeline on a fix?

**Comment by krispo** [comment]
I think it should be adressed to [nvd3](https://github.com/novus/nvd3) maintainers.
