### ISSUE TITLE
angular-nvd3 and browserify

### ISSUE THREAD

**Issue by lebolo** [krispo/angular-nvd3#387]
Has anyone gotten angular-nvd3 to work with Browserify? I installed via `npm install angular-nvd3 --save` then used the following to create my module.

```javascript
require('angular').module('myApp', [require('angular-nvd3')]);
```

My controller is something like

```javascript
require('angular')
  .module('myApp')
  .controller('MyCtrl', function() {
    var ctrl = this;

    ctrl.nvd3Options = {
        chart: {
            type: 'discreteBarChart',
            height: 450,
            margin : {
                top: 20,
                right: 20,
                bottom: 60,
                left: 55
            },
            // ...other options from demo...
        }
    };

    ctrl.nvd3Data = [{
        key: "Cumulative Return",
        values: [
            { "label" : "A" , "value" : -29.765957771107 },
            // ...other data from demo...
        ]
    }];
  });
```

And my HTML would look like

```html
<div ng-app="myApp" ng-controller="MyCtrl as ctrl">
  <nvd3 options='ctrl.nvd3Options' data='ctrl.nvd3Data'></nvd3>
</div>
```

But I get the error `ReferenceError: nv is not defined` @ [angular-nvd3.js:250](https://github.com/krispo/angular-nvd3/blob/v1.0.5/dist/angular-nvd3.js#L250) (using v1.0.5).

I would think that installing and requiring angular-nvd3 would handle all the dependencies (i.e. nvd3 and d3). But these files aren't being loaded for some reason.

### Possible Solution

I'm not sure how other modules do it, but it might be that _index.js_ needs

```javascript
require('d3'); // Missing
require('nvd3'); // Missing
require('./dist/angular-nvd3');
module.exports = 'nvd3';
```

and I'm not sure if these packages should move into the `dependencies` parameter of _package.json_ (instead of `devDependencies`)?

**Comment by lebolo** [comment]
I also asked [SO](http://stackoverflow.com/q/36335714/1370556) for help.

**Comment by krispo** [comment]
You have actually already answered )
If you use browserify/common/require/.. you should import all dependent modules 
```js
require('d3');
require('nvd3');
```
into your app (your main.js file), and then create a single bundle file with all dependencies.
Or you can include each dependent modules in html directly with `<script>` tag.

If you use `d3` and `nvd3` in `dependencies`, it guarantees that these modules will be automatically installed in your app if it were not installed before, otherwise you should install in manually. `devDependencies` is only needed for development of the current lib.

**Comment by lebolo** [comment]
Thanks @krispo, I tried your suggestion and I get

```
nv.d3.js:16 Uncaught ReferenceError: d3 is not defined
```

I assume this is because `d3` is no longer a global variable (because of Browserify), but nvd3 assumes and *depends on it being global*. For now, I use `global.d3 = require('d3');` as a [workaround](http://stackoverflow.com/a/23497788/1370556) in my main.js.

We can make angular-nvd3 [work with CommonJS](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support), but I think it'll take some effort to make nvd3 work this way.
