### ISSUE TITLE
d3 and nvd3 dependency 

### ISSUE THREAD

**Issue by alonbez** [krispo/angular-nvd3#391]
hi,

i'm using jspm to install packages in my project.
'd3' and 'nvd3' are devDependencies in your 'package.json', so when i'm installing the package these 2 dependencies will not be installed in my project even though they are required, so i need to install them separately.

is it possible to change the dependencies so these 2 will be installed when im installing your package?

thanks!

**Comment by krispo** [comment]
My bad.. sure, I'll change it!
