### ISSUE TITLE
Interactive guideline hidden

### ISSUE THREAD

**Issue by AlexandreDenis** [krispo/angular-nvd3#400]
Hello,

I am using angular-nvd3 with angular-pageslide, so all my graphes are in my pageslide. The thing is when I set `useInteractiveGuideline` to false, the part of the tooltip outside the pageslide is well shown while when I set `useInteractiveGuideline` to true, the part of the tooltip outside the pageslide is hidden.

I tried to modify the `nvtooltip` class by setting a high value to the `z-index` attribute but in vain.

I don't know if this is an angular-nvd3 issue but the thing weird is the behavior is the good one with the tooltip for only one line while it isn't with the interactive guideline.

**Comment by AlexandreDenis** [comment]
Here is some screenshots of the issue :

- With the `useInteractiveGuideline` to true

![Interactive guildeline to true](http://image.noelshack.com/fichiers/2016/15/1460532301-angular-nvd3-interactive-guildeline-true.png)

- With the `useInteractiveGuideline` to false

![Interactive guildeline to false](http://image.noelshack.com/fichiers/2016/15/1460532300-angular-nvd3-interactive-guildeline-false.png)

**Comment by krispo** [comment]
The problem is that single tooltip is appended to the end of the `<body>` tag, while `interactiveGuideline` tooltip is inserted after `<svg>` element. It's nvd3 itself issue.
For you, try to find and change `z-index` of the parent element (.pageslider, or where directive is created)..

**Comment by AlexandreDenis** [comment]
First of all thanks for your answer. I tried what you suggest but without success. But you gave me a clue by telling me to modify the style of the `#pageslide`. Actually, by default, it has the `overflow` attribute setted to `hidden`. Change this attribute to `visible` fixed my problem.
