### ISSUE TITLE
Is there an easy way to enable the use of ISO datetime format and not just timestamp?

### ISSUE THREAD

**Issue by PxSonny** [krispo/angular-nvd3#404]
Hi, 

I think everything is in the title. 
I have data from influx that displays like this ["2016-04-12T10:57:06Z",5377] 
And the module doesn't handle the datetime, is there an easy to fix that?

@krispo Thanks for you great module :+1:

**Comment by PxSonny** [comment]
Fixing the data manually for now:

`for(var i = 0; i < values.length; i++)
        values[i][0] = d3.time.format.iso.parse(values[i][0]);`

**Comment by krispo** [comment]
Parse data in `x` option, and then the parsed values are used in `tickFormat` option to display the right format on xAxis:
```js
{
  x: function(d){return d3.time.format.iso.parse(d[0]),
  xAxis: {
    tickFormat: function(d) {
      return d3.time.format('%x')(new Date(d))
    }
  }
}
```

**Comment by PxSonny** [comment]
Thanks that feels more of a proper way.
