### ISSUE TITLE
"Duration" property of "Pie-chart" and "Doughnut Chart" is not working

### ISSUE THREAD

**Issue by VaibhavP17** [krispo/angular-nvd3#405]
Hi,

I need to provide some duration to animate the Pie/Doughnut charts. But it doesn't seem to work according to the [demo](http://krispo.github.io/angular-nvd3/#/pieChart) provided on the website.

Am I doing something wrong ?

**Comment by VaibhavP17** [comment]
@krispo : Is there a workaround to provide animation for donut charts ?

**Comment by krispo** [comment]
It's definitely a core nvd3 bug. I think it will be easier to fix it directly in the core.
1. In `pieChart.js`, replace this line: https://github.com/novus/nvd3/blob/v1.8.3/src/models/pieChart.js#L147 with
```js
d3.transition(pieWrap).duration(duration).call(pie.duration(duration));
```
2) In `pie.js`, replace this line:
https://github.com/novus/nvd3/blob/v1.8.3/src/models/pie.js#L42 with
```js
var renderWatch = nv.utils.renderWatch(dispatch, duration);
```
and also add default definition at the top: 
```js
duration = 250
```
and also add getter/setter at the bottom:
```js
duration: {get: function(){return duration;}, set: function(_){
  duration = _;
  renderWatch.reset(duration);
}}
```
3) Also there are `mouseover` and `mouseout` durations, that you can also change
https://github.com/novus/nvd3/blob/v1.8.3/src/models/pie.js#L164
https://github.com/novus/nvd3/blob/v1.8.3/src/models/pie.js#L177

**Comment by andrekosak** [comment]
i have tried the solution from previous post and i got the error:

```
TypeError: d3.transition(...).duration is not a function
```

Why could it be?
