### ISSUE TITLE
How to apply log scale to stacked area chart

### ISSUE THREAD

**Issue by stripathix** [krispo/angular-nvd3#406]
Hi,
If there is a large difference between data point then graph drawn is not looking good.

Sample : [Plunker](http://plnkr.co/edit/T9fkFZI7XDBd9tpkyXSN?p=preview)

In above plunker one value in "north America" is set to 500, due to which other data points are not marked nicely.

How to use d3.scale.log() in angularjs-nvd3 directive to draw graph nicely?

**Comment by krispo** [comment]
Use `yScale` option. Note that we should also ensure that y domain is >0. So use `yDomain` option to specify it.
```js
{
  yScale: d3.scale.log(),
  yDomain:[1,1000]
}
```

**Comment by stripathix** [comment]
Thanks @krispo for pointing out yDomain, I did tried yScale but was getting the error about yDomain missing. It works :+1:

**Comment by NathanManning** [comment]
Why doesn't this work for 'multiBarChart'? I keep getting 'd3.min.js:5 Error: <rect> attribute height: Expected length, "NaN".'.
Eg. [Plunker](http://embed.plnkr.co/4O7ByRHu2LL7pygrFD8U/)
