### ISSUE TITLE
setting useInteractiveGuideline to false throws errors when users interacts with line chart.

### ISSUE THREAD

**Issue by facultymatt** [krispo/angular-nvd3#41]
I noticed this behavior on the line chart. When I set `"useInteractiveGuideline": false,` errors are thrown when the user mouses over the chart, clicks it, etc.

```
Uncaught TypeError: Cannot read property 'x' of null d3.js:5133
2Uncaught TypeError: Cannot read property 'data' of undefined nv.d3.js:11190
Uncaught TypeError: Cannot read property 'x' of null d3.js:5133
7Uncaught TypeError: Cannot read property 'data' of undefined 
```

**Comment by dan2k3k4** [comment]
If we need to use interactive - how can we use it with lineChart ? I get the property 'x' of null error...
