### ISSUE TITLE
Enhance for debounce when update option in a loop

### ISSUE THREAD

**Issue by AtronachIX** [krispo/angular-nvd3#412]
Hello,

i have a loop that updates the data in the chart and enlarges it to see it better, it widens in proportion of how much data contains the array of Data.
The data, however, are get by a call Ajax

This is the code:

forEach (listFruitions, function (item) {
 callToserver (item.id) .then (
   function (element) {
     updateChart (element)
   })}

function updateChart (elementToPlot) {
....
$ Scope.data [0] .values.push ({.....});
$ Scope.options.chart.width = 75 + 80 * $ scope.data [0] .values.length;
....

}

So in my code, no update at the end of the loop and potentially no last timeout to update the graph via API.

The problem is the Width parameter

Since it is an Options, it is triggered the Debounce when modifing it,
but as it is written the library code, it will only pass the first of the Width "change", and no other, until the end of the Debounce timer, you can not turn it off (i have try with change in Config debounce to 0 , 1 or -1, but don't work), also i can't act on the Immediate parameter in any way, the result is that debounce block only the updates, and the timeout expires never do nothing.
I think that in the applied of the function Later, you must consider the Immediate parameter, only if CallNow was precedently set to true (so potentially avoid to call the same function twice), a second call to Debounce, that have a timeout set (and then no callnow possible), should in any case it is invoked later in function Later and not discarded in my opinion.

What do you think about it? Is there a possible malfunction?
Maybe you have suggestions on how to better manage my loop update?

Thanks so much

And sorry for my poor english
A

**Comment by krispo** [comment]
You always can trigger `refresh` manually via `api`
```html
<nvd3 ... api="api"></nvd3>
```
and in js
```js
$scope.data [0] .values.push ({.....});
$scope.options.chart.width = 75 + 80 * $ scope.data [0] .values.length;
$scope.api.refresh()
```
And also you can turn off the `$watch` at all using config (if you don't want any extra `refresh` or `update`)
```js
<nvd3 ... api="api" config="{deepWatchOptions: false, deepWatchData: false}"></nvd3>
```

**Comment by AtronachIX** [comment]
Thanx for the answer,

Off course i can manually refresh, but for the asyncronous nature of my update, the risk is that i update the chart 1000 time for nothing, i must elaborate a very complex logic to manage it, when there is the debounce function, that it sames is think for it.


The Immediate flag is always true for Option update, so in the later function, the if statement of the Later function is always skipped and never do nothing, is logically correct?
Even a config parameter would be perfect fo Immediate flag, i prefer the Immediate flag set to false.
If i have a set of update rapidly (t_of_update < debounce) , i prefer to discard the first one "obsolete" update and not the last "most recente"



Thanks so much
A

**Comment by krispo** [comment]
I think we can add `Immediate` flag to config in the next release. I left it as `true` since it's the most common behavior for directive.

**Comment by AtronachIX** [comment]
Ok wonderfull

Thank you again.

A
