### ISSUE TITLE
Data holes in line charts

### ISSUE THREAD

**Issue by AlexandreDenis** [krispo/angular-nvd3#422]
Hello,

I guess the question has already been asked but I can't find any answer on internet. (Perhaps my english keywords are wrong, I don't know). In my opinion, it must be a common issue : How to display data holes in a line chart ?

For example, let's assume that I have some pressures data that I want to plot. So on the x axis, I would have my timestamp and on my y axis, my pressure values.

Now let's assume that there isn't any data during a time range which could be 15 minutes for example. I want the user knows that there is no data available during this time range. So my question is how to represent such a phenomenon on a line chart ?

The first dumb solution would be to draw several plots like you can see on this plunker : [https://plnkr.co/edit/69mJsaC9RYNqcrBgKSGM?p=preview](https://plnkr.co/edit/69mJsaC9RYNqcrBgKSGM?p=preview)

Unfortunately such a solution isn't enough. nvd3 doesn't seem to well manage this kind of data (the tooltip seems lost). Moreover, since we draw several plot, there are several legends. So it's clearly not an appropriate solution.

Another idea would be to color some sub part of the plot with a transparent color (I don't know if it's even possible). So i'm stuck here with no appropriate solution to represent data holes in my line charts drawn with angular-nvd3. Have you any solution to do that ? Or nvd3 doesn't manage such mecanism?

**Comment by AlexandreDenis** [comment]
I just find a post in stackoverflow which seems to be what I need : [http://stackoverflow.com/a/15259739/3511736](http://stackoverflow.com/a/15259739/3511736)

It talks about a `line.defined()` function. Does any `line.defined()` method exists with angular-nvd3?

**Comment by krispo** [comment]
Yes, there is an option `defined`:
```js
chart: {
  defined: function(d,i){
    return !isNaN(d.y) && d.y !== null }
  }
}
```

**Comment by AlexandreDenis** [comment]
Thanks for your reply @krispo. However I managed to do it without `defined` but using directly the `y` function. I return `null` when I don't want my plot to be display. It seems to work well that way. Do you advice me to use `defined` instead ?

**Comment by krispo** [comment]
Use what you think more comfortable and easier.

**Comment by ranjitkumarpalanisamy** [comment]
Option defined: is not working in nvd3 line graph
![temperature_nan](https://user-images.githubusercontent.com/20296945/34830014-9303153e-f708-11e7-818f-f7bd4b5ad170.png)

Here I attach the code below,

    this.options = {
        chart: {
            type: 'lineChart',
            height: 450,
            margin: {
                top: 100,
                right: 20,
                bottom: 50,
                left: 55
            },
            defined: function(d){
                console.log("******inside graph"+"x: "+d.x+"y: "+ d.y +" "+ !isNaN(d.y) );
                return !isNaN(d.y) && d.y !== null;
            },
            x: function(d) {
                return d.x;
            },
            y: function(d) {
                return d.y;
            },
            showValues: true,
            duration: 500,
            xAxis: {
                axisLabel: 'Time (days)',
                tickFormat: d3.format(',f')
            },
            yAxis: {
                axisLabel: 'Temperature (°C)',
                tickFormat: d3.format(',.1f'),
                axisLabelDistance: -10
            },

            useInteractiveGuideline: false,
            interactive: true,
            tooltips: true,
            tooltip: {
            contentGenerator: function (e) {  
              var series = e.series[0];
              if (series.value === null) return;
                
              var rows = 
                "<tr>" +
                  "<td class='key'>" + 'Date: ' + "</td>" + 
                  "<td class='x-value'>" +e.value+ "</td>" +
                "</tr>"+
                "<tr>" +
                  "<td class='key'>" + 'Temperature(°C): ' + "</td>" +
                  "<td class='x-value'><strong>" +series.value+ "</strong></td>" +
                "</tr>";

              var header = 
                "<thead>" + 
                  "<tr>" +
                    "<td class='legend-color-guide'><div style='background-color: " + series.color + ";'></div></td>" +
                    "<td class='key'><strong>" + series.key + "</strong></td>" +
                  "</tr>" + 
                "</thead>";
                
              return "<table>" +
                  header +
                  "<tbody>" + 
                    rows + 
                  "</tbody>" +
                "</table>";
            } 
          }

        }
Input Data : [ {"x":1,"y":21},{"x":2,"y":22},{"x":3,"y":23},{"x":4,"y":null},{"x":5,"y":null},{"x":6,"y":25},{"x":7,"y":null},{"x":8,"y":25},{"x":9,"y":21},{"x":10,"y":23},{"x":11,"y":25.5} ]
