### ISSUE TITLE
problem converting multichart svg to canvas

### ISSUE THREAD

**Issue by absarora** [krispo/angular-nvd3#426]
Here is the plnkr for the same:
http://plnkr.co/edit/iWGabn97y7qIMIZb8Gws?p=preview

The canvas image shows partial graph only. Any help would be great. Thank you!

**Comment by krispo** [comment]
Increase interval to `1000`, thanks for the demo!

**Comment by ajay-cd** [comment]
Yes, I did the same and it works flawlessly. Thank you!
