### ISSUE TITLE
dispatch `tooltipShow` event not firing

### ISSUE THREAD

**Issue by facultymatt** [krispo/angular-nvd3#43]
The tooltipShow event doesn't appear to fire on linechart.

**Comment by Sutikshan** [comment]
How can we use custom toolTipContent to shos customized tool tip content. I am trying, but tooltipshow event is is not working, even if useInteractiveGuideline: false
My options are 

        var toolTipContent = function() {...}
        $scope.options = {
            chart: {
                type: 'lineChart',
                height: 450,
                margin: {
                    top: 20,
                    right: 20,
                    bottom: 40,
                    left: 55
                },
                x: function(d) {
                    return d.x;
                },
                y: function(d) {
                    return d.y;
                },
                useInteractiveGuideline: false,                
                dispatch: {
                    tooltipShow: function(e) {
                        console.log(e);
                        console.log("tooltipShow"); //not getting fired.
                        toolTipContent();
                    },
                    tooltipHide: function(e) {
                        console.log("tooltipHide");
                    }
                },
                
                xAxis: {
                    axisLabel: 'Date Time',
                    tickFormat: function(d) {
                        return d3.time.format('%d-%b-%Y')(new Date(d));
                    }
                },
                yAxis: {
                    axisLabel: '', //todo
                    tickFormat: function(d) {
                        return d3.format('.02f')(d);
                    },
                    axisLabelDistance: 30
                }
            }
        };


$scope.options.chart.toolTipContent = toolTipContent; //also tried but not sure if it is required.

**Comment by krispo** [comment]
For the latest versions (nvd3 1.8.1) use `tooltip.contentGenerator` option:
```js
chart: {
    tooltip: {
        contentGenerator: function(d) { 
            return 'custom tooltip content';
        }
    }
}
```
