### ISSUE TITLE
update bower.json

### ISSUE THREAD

**Issue by awashbrook** [krispo/angular-nvd3#432]
@krispo thanks for a simply awesome api, I upgraded much belatedly from the older `angular-nvd3-directives` template based library...the JSON API approach is so much more robust!

when installing, bower warns that `bower.json` is `"version": "1.0.6-dev"` not your latest release 1.0.7. i do sympathise that it is an extra burden to update your json every time you push a new release. bower pulls the latest release anyway ultimately :)

Andy

**Comment by krispo** [comment]
Thanks, 
I will try to be more attentive next time  ;)
