### ISSUE TITLE
Tooltip doesn't hide when legend is uncheck in linePlusBarChart.

### ISSUE THREAD

**Issue by umair-khanzada** [krispo/angular-nvd3#433]
Hi,
    i spend to much time for hiding tooltip in lineplusbarchart but after checking official demo of lineplusbarchat it has same issue. that i am facing. 
![tooltip-issue](https://cloud.githubusercontent.com/assets/8782817/15295755/6784d97c-1bab-11e6-8696-29ae2ab443b4.png)

**Comment by krispo** [comment]
It's definitely nvd3 bug. I found that if we completely refresh the chart with uncheck, it's gone. (`update` is not working)
Try to use `stateChange` event and `api` for this:
```js
dispatch: {
  stateChange: function(){
    $scope.api.refresh()
  }
}
```
and in html
```html
<nvd3 options="options" data="data" api="api"></nvd3>
```
I don't know whether you will be satisfied with this hack.

**Comment by umair-khanzada** [comment]
@krispo +1 it's work.
