### ISSUE TITLE
multiBarChart y-axis tick interval changes based on number of bars in chart.  Shows no ticks at all when plotting 2 bars.

### ISSUE THREAD

**Issue by jalipert** [krispo/angular-nvd3#442]
When plotting two bars, for example, the y axis displays 0 ticks in some cases.  But if you just add more data points (with the same value), the ticks start to appear.  

See this plunkr example:
http://plnkr.co/edit/fncZTnsJuImRIFQdd38P?p=preview

I've confirmed that this issue isn't present on the standard nvd3 library.

**Comment by krispo** [comment]
I suppose it's due to ticks [calculations](https://github.com/novus/nvd3/blob/v1.8.3/src/utils.js#L431) depended on data..
Try to just specify an approximate number of ticks with `ticks` option:
```js
yAxis: {
  ticks: 10
}
```

**Comment by jalipert** [comment]
that works for me, I didn't realize you could do that.  Thanks!
