### ISSUE TITLE
How can I select the SVG element?

### ISSUE THREAD

**Issue by lorenzogm** [krispo/angular-nvd3#445]
Hello everyone, maybe I just have a noob question but I can't find any solution after a long time.

I have a directive with some options and data and it's working perfectly:
`<nvd3 options="vm.chart.options" data="vm.chart.data"></nvd3>`

Now I want to select the SVG element to make a few changes in the design of the chart. But I don't know how can I select it.

In my controller I try to remove the nvd3 directive and the SVG (as an example to see how can I select the SVG)
```
this.chart = SomeService.getChart();

// This is working. the nvd3 is removed
d3.select('nvd3').remove(); 

// Those are not working, I can't remove the SVG because is not selected
d3.select('svg').remove(); 
d3.select('nvd3').select('svg').remove(); 

```

**Comment by HectorAnadon** [comment]
`<nvd3 options="options"
      data="data"
      config="config"
      events="events"
      api="api"
      on-ready="callback"></nvd3>

$scope.callback= function(scope) {
        $scope.chart = scope.chart;
        $scope.svg = scope.svg;
        $scope.api = scope.api;
      };`

I hope it helps.
