### ISSUE TITLE
LineChart : extended options : interactiveLayer.tooltip.valueFormatter is not taken into account.

### ISSUE THREAD

**Issue by izy-izzy** [krispo/angular-nvd3#453]
See plunker to: All values in interactive tooltip should be equal : "Anything".
The interactiveLayer.tooltip.valueFormatter function is not passing to chart.

I have this:

```
chart.config.extended = true;

...

chart.options: {

   ...

   interactiveLayer: {
      tooltip: {
          valueFormatter: function (d,i) {
              return 'Anything';
          }
      }
  },

  ...

}
```

http://plnkr.co/edit/Zelhs8?p=preview

**Comment by krispo** [comment]
It's a bug. In the latest nvd3 version (1.8.3) it seems to be fixed.

**Comment by izy-izzy** [comment]
Confirmed. Fixed in 1.8.3. nvD3.

**Comment by krispo** [comment]
Ok, I close it.

**Comment by krispo** [comment]
hmm.. 1.8.3 has even worse tooltip bugs..

**Comment by izy-izzy** [comment]
Yeah See that: 
https://github.com/novus/nvd3/issues/1698

:)
