### ISSUE TITLE
display months name as string in angular NVD3 multicharts

### ISSUE THREAD

**Issue by mnaouali** [krispo/angular-nvd3#456]
'm trying to display the months name to make a multi-chart graph that will analyze the data for this year and the previous one. I was trying to do that using ticks. here is a [punker](http://plnkr.co/edit/Ie4SCZ?p=preview) where i'm trying to do that, but I'm not able to display months name, it shows always January. is there a way to do it differently? which is the best way and how to fix that?

xAxis: {
    axisLabel: 'Months',
    showMaxMin: true,
    tickFormat: function(d) {
      return d3.time.format('%B')(new Date(d))
    },
    ticks:12,
    tickValues:['Jan','Fev','Mars','Avr','Mai','Juin','Juil','Aout','Sept','Oct','Nov','Dec']
  },

**Comment by mnaouali** [comment]
solution found

**Comment by HectorAnadon** [comment]
@mnaouali Can you post your solution?

**Comment by mnaouali** [comment]
@HectorAnadon here is an example in [plunker](http://plnkr.co/edit/Ie4SCZ?p=preview)

I'm really sorry for the delay
