### ISSUE TITLE
Zoom feature fails on api.updateWithData(data)

### ISSUE THREAD

**Issue by juja** [krispo/angular-nvd3#461]
After updating chart data, the zoom feature stopped working.

Config: = "{refreshDataOnly:true, deepWatchData: false}"

Plunker:
http://plnkr.co/edit/LIErhrTbpy8iLbJjSvb4?p=preview

**Comment by krispo** [comment]
Thanks! It will be fixed in the next release.

**Comment by juja** [comment]
Amazing response time, thanks to you!

**Comment by juja** [comment]
still it fails when data are not assigned at initialization
http://plnkr.co/edit/ujaif5DwLrCHi8jc6KvQ?p=preview

**Comment by krispo** [comment]
Thanks! I hope it is fixed now )
