### ISSUE TITLE
lineChart broken on api.updateWithOptions(options)

### ISSUE THREAD

**Issue by juja** [krispo/angular-nvd3#463]
lineChart disapears after call api.updateWithOptions(options)  on this context:

* Chart initialized whith no data
* api.updateWithData() was called previously

If new options include zoom:

 `angular-nvd3.js:558 Uncaught TypeError: scope.chart.update is not a function`

Plunker:
http://plnkr.co/edit/1i2ZdNEWZUuv2IM4Bl4L?p=preview

**Comment by krispo** [comment]
I've added important changes to api, that fix this issue. Now it should be tested on previous examples..
It's actually not a zooming, but api itself issue. Thanks for pointing to this!

**Comment by krispo** [comment]
Fixed in the latest version (1.0.8+).
