### ISSUE TITLE
How to trigger tooltips of all data points

### ISSUE THREAD

**Issue by stripathix** [krispo/angular-nvd3#469]
Hi,
I want to implement tracking line like this.
https://www.wunderground.com/weather-forecast/MN/KBTP.html?MR=1

Need single tracking line for multiple graphs.
I have created a single tracking line for all the graphs, but how to trigger tooltips of all data point that are near to tracking line.
![singletracking line](https://cloud.githubusercontent.com/assets/8480351/16687545/e85cc10e-4536-11e6-8216-af44330e7213.png)

I would have triggered the tracking line of all charts at mouseX position like this but I want to customize the tooltip HTML also so that it look like the above weather chart.
![tracker](https://cloud.githubusercontent.com/assets/8480351/16687539/de5a0f0e-4536-11e6-9861-c6f204d1a5ac.png)

**Comment by stripathix** [comment]
I have migrated from  nvd3 to pure D3 implementaion to get more control over tooltip and design.

Works perfectly now. Thanks to angular-nvd3 which helped me to start with D3.

**Comment by swapnasavant** [comment]
Hi,
I have the exact same requirement. Any pointers regarding how did you solve your issue using D3?

**Comment by stripathix** [comment]
@swapnasavant
Steps 
1) Create tracking area
2) Bind mousemove event on that tracking area
3) Now you can find nearest data point to mouse using d3.bisector()
Ref: [Bisector in action](https://bl.ocks.org/mbostock/3902569)

[Example](https://bl.ocks.org/larsenmtl/e3b8b7c2ca4787f77d78f58d41c3da91)
 Good luck 👍 
<img width="392" alt="screen shot 2017-02-06 at 11 30 34 pm" src="https://cloud.githubusercontent.com/assets/8480351/22659617/4dfbb300-ecc4-11e6-9c9a-ba446ffbcc2f.png">
