### ISSUE TITLE
Force X/Y Min/Max values.

### ISSUE THREAD

**Issue by ktstowell** [krispo/angular-nvd3#47]
Is there a way to force the range of a graph?

Use case: 

  If I know my chart has an X range of -1, 1 and a Y range of 0, 1, is there a way I can force the axes to show those values, even if a data point doesn't reach it?

The inserted image shows a chart with the aforementioned range, however the X axis stops at 0.83 as that is the highest data point that is available. Is there a way I can always have the axes show the min/max that I want?

Thanks!

![screen shot 2014-10-02 at 4 41 23 pm](https://cloud.githubusercontent.com/assets/1407046/4500223/fd6f1196-4a8d-11e4-97c1-ddd915c14acc.png)

**Comment by Andi24** [comment]
The above mentioned fix with the x & y domain works fine in the live edit (for line+bar with focus chart), but when I specify the option in my javascript like so:
yDomain: [0,100]

It doesn't have any effect. I also tried it in the plunker for the graph and still no effect.
Any suggestions?

**Comment by simeonkessler** [comment]
for multiChart try:

yDomain1: [0,100]

This worked for me
