### ISSUE TITLE
MultiChart Interactive tooltip headerFormatter doesnt work

### ISSUE THREAD

**Issue by D4vx** [krispo/angular-nvd3#470]
Versions:
d3 : 3.5.17
nvd3 : 1.8.4
angular-nvd3 : 1.0.7

This appears to not be working when I use a multiChart. Works as expected when the chart type is set to lineChart.

![image](https://cloud.githubusercontent.com/assets/8399630/16705340/b88c75b0-45da-11e6-9e8a-026b24ab8c0f.png)

$scope.options : 

                useInteractiveGuideline: true,
                duration: 300,

                xAxis: {
                    tickFormat: function (d) {
                        return moment(d).format('hh:mm:ss A');
                    }
                },
                yAxis1: {
                    axisLabel: 'Degrees °C',
                    axisLabelDistance: -20
                    
                },
                yAxis2: {
                    axisLabel: 'Humidity %RH',
                    axisLabelDistance: -20
                    
                },

                interactiveLayer: {
                    tooltip: {
                        enabled: true,
                        
                        headerFormatter: function (d) {
                            return moment(d).format('dddd, MMM Do YYYY, hh:mm:ss A');
                        }
                    }
                }
            }

**Comment by D4vx** [comment]
It appears the the headerFormatter isnt being hit when using this chart type.

Workaround is to use the contentGenerator for the tooltip to achieve the same result.

interactiveLayer: {
                    
                    tooltip: {
                        enabled: true,
                        contentGenerator: function(d) {
                            var header = moment(d.value).format('dddd, MMM Do YYYY, hh:mm:ss A');
                            var headerhtml = "<thead><tr><td colspan='3'><strong class='x-value'>" + header + "</strong></td></tr></thead>";
                            var bodyhtml = "<tbody>";
                            var series = d.series;
                            series.forEach(function(c) {
                                bodyhtml = bodyhtml + "<tr><td class='legend-color-guide'><div style='background-color: " + c.color + ";'></div></td><td class='key'>" + c.key + "</td><td class='value'>" + c.value + "</td></tr>";
                            });
                            bodyhtml = bodyhtml+"</tbody>";
                            return "<table>"+headerhtml+''+bodyhtml+"</table>";
                        }
                    }
                }

![image](https://cloud.githubusercontent.com/assets/8399630/16716745/9ca77aea-4759-11e6-97ff-b3ca45b8ed9a.png)

**Comment by krispo** [comment]
Thanks, I think we can close this.

**Comment by ariacom** [comment]
Hi, bug does not seem to be solved in the 1.8.5, can you reopen and fix this to avoid the workaround for the multiChart ?

**Comment by mpint** [comment]
+1
