### ISSUE TITLE
Sunburst doesn't works with angular-nvd3 1.0.8 and nvd3 1.8.3

### ISSUE THREAD

**Issue by kirakishin** [krispo/angular-nvd3#477]
Hello,

i want to use your last release (1.0.8) but it doesn't works with nvd3 1.8.3 for a sunburst
the plunker :
http://plnkr.co/edit/iAFOzO

could see why ?

thanks a lot ;)

**Comment by krispo** [comment]
Thanks for pointing to this bug! I've [fixed](https://github.com/krispo/angular-nvd3/commit/0f82c211f631edc075c7f428bbd61cda7721da1a) it. Will be in the coming release.

**Comment by kirakishin** [comment]
thank you !

**Comment by kirakishin** [comment]
Hello,

could you release the 1.0.9 please ?
i would using it if that is possible.

Best regards

**Comment by krispo** [comment]
Yes, will be today.
