### ISSUE TITLE
How to create multiline label for pie chart with arrow mark?

### ISSUE THREAD

**Issue by SeemaXoriant** [krispo/angular-nvd3#480]
Need to create 2 line text for pie labels, which can show key on first line and value in second line.

**Comment by Azbesciak** [comment]
is it possible to get any answer? i also need this feature.
Anyway, is there any way to stylize label? for example add <strong> tag? and following value?

**Comment by SeemaXoriant** [comment]
As there is no response from anyone, I tried the following, got success some extend. I am able to create multiline label only, and not the arrow mark. 
As i am using typescript following code will helps to create multiline label:

I have created component for the pie chart -
In its controller injected the $scope like below:
`static $inject = ['$scope', '$timeout'];
`
and in constructed calling the insertLinebreaks method.

constructor looks like below -

`constructor($scope: ng.IScope, $timeout: ng.ITimeoutService) {
      super($scope);
      $timeout(() => {
        d3.selectAll('.nvd3.nv-pie .nv-label text').each(this.insertLinebreaks);
      }, 500);
    }
`

`private insertLinebreaks(d: any, i: number): void {
      var el = d3.select(this);
      // console.log('el is :' + el);
      var words = [];
      words.push(d.data.key.toUpperCase());
      words.push(d.data.value);

```
  el.text('');
  el.style("fill", d.data.color);

  for (var i = 0; i < words.length; i++) {
    var tspan = el.append('tspan').text(words[i]);
    if (i > 0) {
      tspan.attr('x', 0).attr('dy', '15').style("fill", "black");
    }
  }
}`
```

It helps to create multiline label for pie chart. 

If anyone found better solution then they can comment.

Thanks.

**Comment by SeemaXoriant** [comment]
Created plunker.
http://plnkr.co/edit/ftXnRYd4STfYyitTNMa1?p=preview

**Comment by Azbesciak** [comment]
I just used a custom label (concanated values) but it is of course not inline.. so your solution seems to be much better :)

**Comment by Azbesciak** [comment]
But there is a bug - if you hide or show something on the legend, multiline labels disappear becoming standard

**Comment by SeemaXoriant** [comment]
Didn't get u.

**Comment by Azbesciak** [comment]
Just click on the legend circles
