### ISSUE TITLE
Customizing size of data points on Scatter Chart.

### ISSUE THREAD

**Issue by ktstowell** [krispo/angular-nvd3#49]
I'm sure this is a result of me simply not understanding the API, but I can't see to set/customize the size of my graph data points. 

The only thing that seems to respond is `Math.random()`

Here is my config:

```
chart: {
  type: 'scatterChart',
  height: 250,
  color: [],
  showLegend: false,
  showControls: false,
  scatter: {
    onlyCircles: true
  },
  showDistX: true,
  showDistY: true,
  showMaxMin: true,
  tooltipContent: function(key) {
    return '<h3>' + key + '</h3>';
  },
  transitionDuration: 350,
  xAxis: {
    axisLabel: 'Belief',
    showMaxMin: true,
    tickFormat: function(d){
      return d3.format('.02f')(d);
    }
  },
  yAxis: {
    axisLabel: 'Emphasis',
    showMaxMin: true,
    tickFormat: function(d){
      return d3.format('.02f')(d);
    },
    axisLabelDistance: 30
  }
}
```

Here is the code that builds up the data:

```
      $scope.chart.data.push({
        key: node.title,
        values: [{
          y: yValue,
          x: xValue,
          shape: 'circle',
          size: Math.random()
        }]
      });
```

Is there a way to get every point to be of uniform size?

Thanks! Great Library!

**Comment by raugaral** [comment]
Doesn't work

**Comment by jatin-optimus** [comment]
Hello @krispo and @ktstowell ,

I am working on real time updation of scatterchart.I want to clarify some points as follows:

1. I have few bubbles on 1 chart and each of the bubbles have diiferent size property which gets filled into values array.

Bubble having size:0 is not behaving properly.

Can you please provide something .like i have 5 bubbles each of them having size 10,20,0,40 and 50 respectively

I am unable to produce significant difference among 5 bubbles on the basis of size property.

Please provide the solution/guide how can i produce the significant difference among the bubble size value updation.

Bubble size value updation is on basis of realtime values but i am **unable to see the significant difference among the bubble having size:0 and bubble having size:5.**

**Please guide.**


2. **Unable to display size label on bubble**.i want to display size on the bubble is there any way out for this.Please tell.

3.**On some threshold value want to draw border of some other color over and  around the bubble** or any other alternative way to show some different color over the same bubble.

**Looking forward to your reply.**

Thanks

**Comment by naguibihab** [comment]
Did anyone solve this issue? I want to have a fixed size for all my points.
