### ISSUE TITLE
Draw a vertical line in angular-nvd3 scatter chart

### ISSUE THREAD

**Issue by ganeshran** [krispo/angular-nvd3#508]
Ive got a angular-nvd3 scatter chart (similar to http://krispo.github.io/angular-nvd3/#/scatterChart) with two series of data. There is a requirement to add a few vertical reference lines to this graph to mark key dates.

The multichart works but I would lose the zoom function which is a key requirement.

![example](https://cloud.githubusercontent.com/assets/1933770/17733147/1e74b8c8-646d-11e6-9fc4-a9dd55b280a9.png)

Is there any way to add a vertical reference line in the scatter chart? TIA

**Comment by corina10** [comment]
This might help:
https://fiddle.jshell.net/fwewqc1a/6/

**Comment by ganeshran** [comment]
Thanks @corina10 I'll give this a shot!

**Comment by corina10** [comment]
Please let me know if you get this to work, I'm getting some errors.

**Comment by mahmoud-nb** [comment]
thx @corina10, It allows me to add a vertical line. but, if I have dates for the x axis, how can i initiate the ligen to the current date

**Comment by raghav1784** [comment]
hi, Did you final get this requirement solved in Angular-nvd3. Ability to have scatter and drop lines with Zoom or Focus capability ?
