### ISSUE TITLE
How to wire up resizer?

### ISSUE THREAD

**Issue by pertrai1** [krispo/angular-nvd3#510]
I have seen the issue about resize of a graph in bootstrap tab, but I was not understanding on where I put the resize code? Not only so, but if I have 5 graphs in the tab, where would be the best place to trigger the automatic resize on load?

**Comment by alphatek-pro** [comment]
Hi this how i handle this.
var isResize = false;
nv.utils.windowResize (function  (e){isResize=true;});

dispatch :{ 
renderEnd:function  (e){
 if (isResize){//some code here}else {//something else here}

**Comment by pertrai1** [comment]
@Seyfi1977 This looks good but what I want to do is just automatically do a resize `onEnter` of the state - we are using ui-router.
