### ISSUE TITLE
Can't create an event handler for click event on a focus chart

### ISSUE THREAD

**Issue by alleroux** [krispo/angular-nvd3#513]
I'm attempting to create a click handler for handling clicks on the focus chart.  I tried using lines2: { dispatch: { elementClick: ... } but that doesn't work.  Is there another way to write an event handler for it?

**Comment by alleroux** [comment]
I solved my problem.  It isn't ideal but it works.  

`
callback: function (chart) {

```
 if (chart.focus) {

                        chart.focus.dispatch.on('brush', function (event) {
                             //you can access event.extent to see the current data points that limit the current view
                        });
                    }
                }`
```

**Comment by upeshdesai** [comment]
@alleroux I can't seem to get this to work, what version were you using?
