### ISSUE TITLE
Adding 95% confidence intervals to cumulative line charts

### ISSUE THREAD

**Issue by rafiko1** [krispo/angular-nvd3#534]
I was wondering if it's possible to add 95% confidence intervals (for a mean) to the cumulative line charts, and like a shaded area between the intervals and the mean.

Something on the line of following plots (R, SAS,...)
https://www.google.be/search?q=confidence+interval+cloud&espv=2&biw=1536&bih=709&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjAj4v8t5HPAhXF0RoKHcDKBykQ_AUIBigB#tbm=isch&q=confidence+interval++plot&imgrc=ESNjcevAb0X31M%3A

**Comment by gustavodemari** [comment]
Take a look at novus/nvd3#1032
