### ISSUE TITLE
Property 'ordinal' of undefined

### ISSUE THREAD

**Issue by ghost** [krispo/angular-nvd3#545]
Hi,
I have tried a simple copy-paste example but wouldn't work.
There is this error thrown

`ypeError: Cannot read property 'ordinal' of undefined
    at Object.a.models.discreteBar (nv.d3.min.js:4)
    at Object.a.models.discreteBarChart (nv.d3.min.js:5)
    at Object.updateWithOptions (angular-nvd3.min.js:1)
    at Object.refresh (angular-nvd3.min.js:1)
    at Object.<anonymous> (angular-nvd3.min.js:1)
    at Object.fn (angular-nvd3.min.js:1)
    at n.$digest (angular.min.js:132)
    at n.$apply (angular.min.js:135)`

However, my code 
in html
`<nvd3 options="options" data="data"></nvd3>`

and dependables in my gulpfile;

```
        'lib/moment.min.js',
    'lib/d3.min.js',
    'lib/nv.d3.min.js', 
    'lib/angular-nvd3.min.js', 
```

and the controller looks like

```
         $scope.options = {
            chart: {
                type: 'discreteBarChart',
                height: 450,
                margin : {
                    top: 20,
                    right: 20,
                    bottom: 50,
                    left: 55
                },
                x: function(d){return d.label;},
                y: function(d){return d.value;},
                showValues: true,
                valueFormat: function(d){
                    return d3.format(',.4f')(d);
                },
                duration: 500,
                xAxis: {
                    axisLabel: 'X Axis'
                },
                yAxis: {
                    axisLabel: 'Y Axis',
                    axisLabelDistance: -10
                }
            }
        };

        $scope.data = [
        {
            key: "Cumulative Return",
            values: [
            {
                "label" : "A" ,
                "value" : -29.765957771107
            } ,
            {
                "label" : "B" ,
                "value" : 0
            } ,
            {
                "label" : "C" ,
                "value" : 32.807804682612
            } , 
            ]
        }
        ]
```

**Comment by sudhirbitsgoa** [comment]
Hi seems like you are using d3 version 4. Version of 3 are supported.

**Comment by ghost** [comment]
Thanks @sudhirbitsgoa,  but sorry, I'm not getting you.
Do you mean I should downgrade to supported version 3 ?

**Comment by sudhirbitsgoa** [comment]
yes

**Comment by ghost** [comment]
Thank you very much @sudhirbitsgoa , 
It worked after installing a d3 v3. I will go ahead and close the issue now.

**Comment by nenu235** [comment]
Thank you @sudhirbitsgoa ,
you  save my time

**Comment by pratikthakare777** [comment]
Thanks @sudhirbitsgoa , You really help me ..

**Comment by trungjc** [comment]
thanks
