### ISSUE TITLE
Line chart cut at the top

### ISSUE THREAD

**Issue by cropcrop** [krispo/angular-nvd3#560]
Example: http://krispo.github.io/angular-nvd3/#/lineChart

Screenshot:
![err](https://cloud.githubusercontent.com/assets/5428114/19457051/5ec2a34a-9479-11e6-8c0c-b63d233ffb5e.jpg)

**Comment by girniakolenka** [comment]
I have the same problem, please fix this issue

**Comment by kination** [comment]
I also have this issue. How is it going?

**Comment by imornar** [comment]
![2016-11-16 at 23 37 47](https://cloud.githubusercontent.com/assets/9463015/20368766/b9ab2ec8-ac55-11e6-8571-cf16951acc49.png)

Same issue over here. Is it fixable?

**Comment by girniakolenka** [comment]
The same +1

**Comment by b-ashtiani** [comment]
I had the same problem and got it resolved using a chart property called clipEdge.  You need to set it to false.

![image](https://cloud.githubusercontent.com/assets/1222577/20723557/01cb6e10-b639-11e6-97ba-f70c3c05c1eb.png)

**Comment by cropcrop** [comment]
Hey @b3hrooz, thanks for sharing! I'll close the issue
