### ISSUE TITLE
firing elementClick doesn't update the $scope

### ISSUE THREAD

**Issue by davideoliveri** [krispo/angular-nvd3#58]
see plunker http://plnkr.co/edit/rKY95Eco6poEeOfNo5zW?p=preview

I've set the elementClick function to change the value of a string. 
This doesn't happen until another function is executed.

**Comment by carpiediem** [comment]
In this example, how might I get the color of the element that was clicked on via the e object passed into the function?  I've seen examples that use e.color, but that is never a key in the objects that show up in my experience.

**Comment by krispo** [comment]
Try this way:
```js
var el = d3.selectAll('.nv-bar')[0][e.pointIndex];
var color = d3.select(el).style('fill');
```

**Comment by carpiediem** [comment]
Thanks for the quick response.  Just in case others come here with a similar problem, the code above didn't quite work for me, but this variation (`index` instead of `pointIndex`) did.
```
var el = d3.selectAll('.nv-bar')[0][e.index];
var color = d3.select(el).style('fill');
```
