### ISSUE TITLE
MultiBar chart with time series data, x-ticks are appearing separately for each check box item

### ISSUE THREAD

**Issue by madasuk** [krispo/angular-nvd3#60]
Krispo, Please see my plunker at http://plnkr.co/edit/GX5PH5xI2JZfylobO8M4?p=preview, nvd3 for MultiBar chart with Time Series data. In x-axis, the ticks are appearing separately for check box item. How can I fix this to make appear as normal multibar chart with dates on x-axis.

**Comment by digitalhydra** [comment]
check you data structure, for a multibarchart graph you need 2 sets of data that are the same on the x value (time) but different on Y.
