### ISSUE TITLE
$scope.api returns undefined

### ISSUE THREAD

**Issue by ginna-baker** [krispo/angular-nvd3#63]
When I run the $scope.api functions in my code or in the plunkers, I get a type error:

TypeError: Cannot read property 'refresh' of undefined
    at Object.<anonymous> (http://localhost:9000/app/d3loader/d3loader.controller.js:21:17)

What am I doing wrong?

Here's the code:
HTML excerpt:

```
    <nvd3 options="options" data="data" api="api"></nvd3>

```

JavaScript:

```
var app = angular.module('plunker', ['nvd3']);

app.controller('MainCtrl', function($scope) {

    console.log('scope api:', $scope.api); //undefined
    $scope.api.refresh(); //Cannot read property 'refresh' of undefined

    $scope.options = {
            chart: {
                type: 'pieChart',
                height: 450,
                donut: true,
                x: function(d){return d.key;},
                y: function(d){return d.y;},
                showLabels: true,

                pie: {
                    startAngle: function(d) { return d.startAngle/2 -Math.PI/2 },
                    endAngle: function(d) { return d.endAngle/2 -Math.PI/2 }
                },
                transitionDuration: 500,
                legend: {
                    margin: {
                        top: 5,
                        right: 70,
                        bottom: 5,
                        left: 0
                    }
                }
            }

        };

        $scope.data = [
            {
                key: "One",
                y: 5
            },
            {
                key: "Two",
                y: 2
            },
            {
                key: "Three",
                y: 9
            },
            {
                key: "Four",
                y: 7
            },
            {
                key: "Five",
                y: 4
            },
            {
                key: "Six",
                y: 3
            },
            {
                key: "Seven",
                y: .5
            }
        ];
});

```

**Comment by srujanrouthu** [comment]
I have the same issue. I am calling `console.log($scope.api)` in the callback function. It logs out 'undefined' how much ever time I lag it by. I am using $timeout angular service. Any idea why this might happen?

**Comment by owaaa** [comment]
Having the same issue and this example didn't fix, with "angular-nvd3": "1.0.0-rc.2", "angular": "~1.3". api is always undefined, either from my click handler or elsewhere in my controller. I see the API being set inside the directive in the debugger but it appears the 2-way data binding isn't working.

**Comment by srujanrouthu** [comment]
@owaaa: I kind of figured a work around. Stumbled on it, more like. When you set the api, instead of creating it as $scope.api, define it as $scope.xxx.api. This somehow worked for me. I'm not sure why though.

**Comment by owaaa** [comment]
@srujanrouthu Thanks this worked for me

**Comment by MiloHub** [comment]
@srujanrouthu  @owaaa  Can you provide me an example or more description. I am facing similar issue for $scope.api undefined.

**Comment by srujanrouthu** [comment]
@MiloHub I don't know how to give more specifics. Can you put up a plunkr or give us a snippet of your code where you're calling the API so I can point out the required changes?

**Comment by Andi24** [comment]
The $scope.xxx.api doesn't work for me, although I'm calling it way after the chart is rendered through a mouse-click event.

An example of this working would be very helpful.

**Comment by srujanrouthu** [comment]
Following is a variable I defined in my controller during intialization:
`$scope.rc = {}`

Following is my DOM element
`<nvd3 options="options" data="data" api="rc.api" class="with-3d-shadow with-transitions"></nvd3>`

Following is the code accessing the chart API
`$scope.rc.api.getScope().chart.xAxis.tickValues(function () { return arr });`

or
`$scope.rc.api.refresh();`

**Comment by Andi24** [comment]
Thank you so much! I've finally managed to print the api object. 

If only I could stop there. When I use the api tag in the directive my graph stops displaying, i.e. it keeps displaying the "No data" text field. I'm 100% sure I'm getting data to my graph, so I'm not sure what this could be caused by. Any ideas?

**Comment by srujanrouthu** [comment]
Is the data coming from an HTTP request or some other async call? If it is, try using and ng-if to load the directive in you DOM only after the data comes in.

**Comment by Andi24** [comment]
Yep, an http request. But wouldn't it be better to just call api refresh when the data comes in instead?

**Comment by srujanrouthu** [comment]
Is the data coming from an HTTP request or some other async call? If it is, try using and ng-if to load the directive in you DOM only after the data comes in.

**Comment by srujanrouthu** [comment]
Yeah. I guess you can do that too and it should work. I personally prefer ng-if but do whatever you're comfortable with

**Comment by curtismorte** [comment]
For anyone else who comes here and looks at @srujanrouthu's comment, this could be because you are using "controller as" syntax. @ginna-baker's original issue is using $scope, which should imply that she isn't using "controller as" syntax.

I've fallen trap to the same issue she had, however the trick was taking @srujanrouthu's comment and applying the api attribute to my "controller as" object.

**Comment by maruiz93** [comment]
I had the same problem using controller as syntax. 
I have solved it by adding some time before printing the api with setTimeout but this seems to be a workaround with a disadvantage: maybe you are waiting more than the necessary time.

It would be perfect to have some event fired when the chart is completely loaded including its api.

**Comment by srujanrouthu** [comment]
@maruiz93: maybe you can use a $watch on the chart's API? It's not as good as an pre-built event callback, but if it works it would be much better than a timeout, no?

**Comment by iamdevlinph** [comment]
In my `route.js`. I'm using `angular ui-router`
```javascript
controllerProvider: ['$stateParams', function ($stateParams) {
    return $filter('controller-naming')($stateParams.type) + 'Controller';
},
],
controllerAs: 'vm',
```
Here's what I tried.
`vm.rc = {};` I'm not sure if this is the same as `$scope.rc = {}` but since I'm using `controller as vm` then maybe it is.

Then in the HTML i have `api="vm.rc.api"`

Then I try to `console.log(vm.rc.api)` but returns undefined even with timeout.
``` javascript
dispatch: {
    stateChange: function (e) {
        $timeout(function () {
            console.log(vm.rc.api);
        }, 1000);
    },
},
```

I think this will solve the problem I have [here](https://github.com/krispo/angular-nvd3/issues/675)

**Comment by mariocards** [comment]
@srujanrouthu great suff... still useful...
