### ISSUE TITLE
Can not recive event elementClick in lineChart

### ISSUE THREAD

**Issue by DmitriyKomelkov** [krispo/angular-nvd3#64]
Hi. I want to do some things for click on the line in lineChart. 
I use your example in http://krispo.github.io/angular-nvd3/#/lineChart
I set in 
 options = {
            chart: {  
...............................
lines: {  
                  dispatch: {
                    elementClick:function(t,u){alert('Catch')},
                  },
                }, 
..............................
}

but nothing happens. What is wrong? How can I get a click event on the chart line?

**Comment by MojioMS** [comment]
I came here to find a solution for catching click-events without setting useInteractiveGuideline to false. I tried using interactiveLayer as you suggest and tried 'elementClick' as the event for single click. It works (nowadays!), so I guess others might be helped If i commend that.
