### ISSUE TITLE
Does it work with https://github.com/liquidpele/nvd3

### ISSUE THREAD

**Issue by wiibaa** [krispo/angular-nvd3#66]
Hello active users of angular-nvd3,
does someone already tested this directive against recent development of nvd3 in what would become the new home for nvd3:  https://github.com/liquidpele/nvd3
Thanks.

**Comment by inolasco** [comment]
Update: I tried again adding nvd3-community to my project, and so far I see no issues with angular-nvd3.

The only problem is that angular-nvd3 will still install the original nvd3 via bower, as referenced by @AgDude . Unless this repo is updated, and given that the library itself is just a single, relatively simple/short js file, my best bet is to just fork this repo and include the file directly into our angular projects.

**Comment by liquidpele** [comment]
I tried to register it with bower as "nvd3-community"... you can try that and let me know if there are any issues...

**Comment by krispo** [comment]
Thanks to all for your activity. It's required some fixes to use this directive with nvd3-community. I will make new release in the near future.

**Comment by jsheedy** [comment]
Thanks for being on top of it krispo.  I'm brand new to NVD3 so am still experimenting with it in my app. I was having similar issues to others such as leaflet interaction and a wiredep issue when manually installing NVD3-community.  To tide me over in the experimental phase, I installed [klangfarbe's fork](https://github.com/klangfarbe/angular-nvd3) with bower and am rolling.

**Comment by portante** [comment]
@krispo, FYI, Novus has re-kindled work on the original nvd3 repo, merging in all changes from nvd3-community.

**Comment by wiibaa** [comment]
As 1.0.0-BETA is targetting novus nvd3-1.7.1 that include community updates, 
I suppose we can close this one.
