### ISSUE TITLE
Chart only showing up when opening debugging console in Browser

### ISSUE THREAD

**Issue by matthias-herrmann** [krispo/angular-nvd3#684]
My template is looking like this:
`<nvd3 [options]="options" [data]="data" config="{refreshDataOnly: true}"></nvd3`

I'm setting the data property only after obtaining data asynchronous from an api. So the chart is showing `No Data Available` and when receiving the api data nothing is happening, but when I open the debug console of the Browser the chart is suddenly getting rendered.

When I'm setting the `data` property instantly by using some fake data it is working fine as well.

Do I need to refresh the graph manually after the api request or how does it work? Are there any example/documentation out there on how to refresh the graph?

**Comment by anatoly314** [comment]
Have the same issue, how have you solved it? Thank you!

**Comment by matthias-herrmann** [comment]
@anatoly314 I'm not using `angular-nvd3` anymore. I think I have used the `*ngIf` directive to solve that problem.
