### ISSUE TITLE
d3 is not defined

### ISSUE THREAD

**Issue by markdturner** [krispo/angular-nvd3#7]
I'm trying to use boilerplate system from called mean.io from linnovate. For some reason when I follow the installation instructions and try to create a standard multibar graph I get javascript errors saying d3 is not defined. 

I've ruled out the script to being linked to correctly, the presence of the meta tag for charset and tried multiple different orders of linking to all the scripts, none work. I'm using d3 version 3.4.8

**Comment by cht8687** [comment]
: )
