### ISSUE TITLE
Problem with event handeling

### ISSUE THREAD

**Issue by sadhashivsharma** [krispo/angular-nvd3#70]
I have used the previous version of nvd3 charts and I used Angularjs-nvd3-directives (http://cmaurer.github.io/angularjs-nvd3-directives/events.html) to take care of event handeling. It is not working in this version. I am currently going as per your documentation and using the below code to access the click event of the pie chart : 
html :
nvd3 id="pieChart1" options="options" data="data" events="events"> \nvd3>
javascript :
$scope. events = { 
                "elementClick. directive" : function (angularEvent, event) {
                alert ("Event triggered.");
            },
 };
$scope. $broadcast ('elementClick. directive');

Can you help me out if I am doing something wrong. Or what's the correct way to do this.

**Comment by motionsmith** [comment]
I have a related problem. I need to override the legendClick event so that it no longer toggles the line's visibility and instead does something else.

I can respond for the legendClick event just fine, but I can't remove the toggling functionality. Handling the legendClick event doesn't override the default behaviour. How can I get rid of the default behaviour?

**Comment by magicjj** [comment]
@krispo Can you include this information in the readme or an example? I got it working for my prototype, but I'm considering passing this tool along to our other developers. The event handling will be critical to our projects, and it took me a while to hunt this down.

Thanks for all your work on this, it's a great tool!

Jake

**Comment by tjacks3** [comment]
Hello I am having an issue adding events to the sunburst. I followed the code example you gave above, but they all of the events inside of the dispatch do not seem to get fired.

**Comment by Gerinjo** [comment]
Hi, I have the same problem with the sunburst chart. I want to load statistics based on the selected element in the sunburst chart. Therefore I need an event. But the only event that is fired ist the chartClick event and that is not helpful. 

@tjacks3 
Have you found a solution?

**Comment by chaitanyawagle** [comment]
@tjacks3 @Gerinjo Did you guys find a solution yet for event handling in Sunburst?

**Comment by danagh** [comment]
I stumbled onto the same problem as @tjacks3 and @Gerinjo, i.e. using the code @krispo supplied but for sunburst charts. I managed to fix this by changing the name "pie" to "sunburst" in the chart's options: 
`$scope.options =  { `
     `chart: {`
    `    //chart events`
    `    sunburst: {`
      `    dispatch: {`
         `     chartClick: function(e) {...},`
          `    elementClick: function(e) {...},`
        `      elementDblClick: function(e) {...},`
        `      elementMouseover: function(e) {...},`
         `     elementMouseout: function(e) {...}      `      
     ` }`
 `   } `
