### ISSUE TITLE
Dependency in bower.json causes install error through Composer

### ISSUE THREAD

**Issue by mtutty** [krispo/angular-nvd3#71]
I'm using the fxp/composer-asset-plugin to manage bower assets using composer.  This dependency in the angular-nvd3/bower.json is causing an error:
```
"nvd3": "~v1.1.15-beta"
```
The composer version parser doesn't recognize that as valid semver.  Is there any way to broaden the dependency here, so that it's handled by Composer?  Would 1.1.* be close enough?

**Comment by NameFILIP** [comment]
Shouldn't be an issue anymore.
