### ISSUE TITLE
Labels in bullet chart

### ISSUE THREAD

**Issue by ankit1329** [krispo/angular-nvd3#714]
This maybe a silly question. How can I change the default labels in bullet chart. Is there a way I can show custom labels instead of 'minimum', 'maximum', etc on bullet chart? I am new to charts and cant find any options for this. @krispo

**Comment by keholmbeck** [comment]
[This](https://github.com/krispo/angular-nvd3/issues/31#issuecomment-179935303) might help

**Comment by ankit1329** [comment]
@keholmbeck thanks alot. Works perfectly.
