### ISSUE TITLE
Change "NVD3.js" dep to "NVD3-Community"

### ISSUE THREAD

**Issue by Fationably-Late** [krispo/angular-nvd3#74]
I just wanted to open this issue to make sure you're aware that the original repo for NVD3.js is no longer being maintained (since June of 2014, I believe). There is a 'new' repo [nvd3-community](https://github.com/nvd3-community/nvd3) that has been updated for bug fixes, improvements, and further development.

I don't think you'll have to update angular-nvd3 as it is right now (it seems to be working fine on my end without error), I just wanted you to be aware of this, if you weren't already, in case there is a breaking change and/or you were waiting for updates from the original nvd3 team.

**Comment by d0coat01** [comment]
One issue I'm having since I made the switch: the resize listener seems to be broken. 

 nv.utils.windowResize() is no longer being triggered.

Working on a fix. Is anyone else having this issue?

**Comment by d0coat01** [comment]
After switching over to the latest nvd3-community release, it seems like the chart resizing feature is now broken. Some of the functions in the directive global api are not running when they are suppose to be. Example: update: function(){} is not running on a container resize.   I want to help fix this but I am not exactly sure how the global api works.  How is the update function listening to the container width + height?

**Comment by vankap** [comment]
#66

**Comment by Fationably-Late** [comment]
I don't know how I missed that. Closing issue as duplicate.

**Comment by portante** [comment]
@Fationably-Late, FYI, Novus has re-kindled work on the original nvd3 repo, merging in all changes from nvd3-community.
