### ISSUE TITLE
How to customize interactive tooltip?

### ISSUE THREAD

**Issue by simulot** [krispo/angular-nvd3#77]
I would like to change the content of the interactive tooltip. 

I hadn't success by setting chart option object with following:
```javascript
				...
				useInteractiveGuideline: true,
				interactiveLayer: {
					tooltip: {
				  		gravity: 's',
				  		fixedTop: 65,
				  		contentGenerator: function() {return function(d) {
							d.conseil = conseilLabel[quelConseil(d.series[0].value,d.series[1].value)];	
			  				return '<p>'+p.tooltipContent(d)+'</p>';
			  			}}(),
				  	},
				}
```

Then, I have tried by overriding  chart.interactiveLayer.tooltip.contentGenerator once the chart is created. This works fine until any chart option is changed, then default content generator comes back.

What's the best option to achieve my goal?

TIA

**Comment by simulot** [comment]
Finally, I have found it is possible to place a call back. It's is triggered when  chart creation is done in NVD3. 
 ```javascript
				callback: function(chart) {
					var tooltip = chart.interactiveLayer.tooltip;
					tooltip.gravity('s');
					tooltip.fixedTop(65);
					tooltip.contentGenerator(function(d) {
						d.conseil = conseilLabel[quelConseil(d.series[0].value,d.series[1].value)];	
			  			return '<p>'+p.tooltipContent(d)+'</p>';
			  			});
					return chart;
				},
```
This is the smartest solution I have found. Whenever the chart is rebuilt, the callback is called, and the tool tip is changed.

I hope this solution will help.
++

**Comment by ilariuss** [comment]
Hello, i'm sorry, can you show your whole code? I'm trying to show custom tooltip in mouse over event, but I don't know how.

Thank you

**Comment by Skinner927** [comment]
@ilariuss You can create a graph with an object instead of a function. The object has the properties `generate` (which would be your regular function that you pass into addGraph) and then the `callback` like above. 

See this for an example: https://github.com/novus/nvd3/blob/dbcdc25bd1637cbe5368a8e0f74032c1acafcb0f/examples/historicalBar.html#L30

**Comment by simulot** [comment]
Sorry ilariuss for this late reply. I'm busy with another project.

It's not easy to exctract code because, I'm creating dozen of graph, using
a kind of factory function.

Anyway, the call back function has access to underlaying NVD3 object
accessible via chart variable. Then chart.interactiveLayer.tooltip is the
tooltip object. I provide a function for generating the content.
 tooltip.contentGenerator (function (d)) where d is graph data.

I hope this helps.

JFC






2015-06-10 0:27 GMT+02:00 Skinner927 <notifications@github.com>:

**Comment by kashyap-cliqr** [comment]
tooltip.fixedTop(65); is not working in latest version of nvd3. any work around for this issue? 

I want 2 tooltip for focus chart. one for start anchor point and another at end anchor point when someone use brush in linewithfocus chart. any idea how to achieve with nvd3? can I create 2 tooltip with nvd3 for focus chart and set their position?
