### ISSUE TITLE
Max yAxis on multiChart

### ISSUE THREAD

**Issue by MartinWeb** [krispo/angular-nvd3#81]
Hi,

I'm not able to fix max value on yAxis1 on a multiChart.
I have on my dataset value from 0 to 99.35 for example and i would like to show 100 on that axis no matter what the max value on my dataset.

I try with range, domain, etc ... How can i do that ? 

FWI i'm currently using 0.0.9 version of your plugin. I saw that 0.1.0 version fix some bugs on multiChart. Do i need to switch to that version ? If yes, is this version stable for production application ?

Thanks in advance for the reply.

**Comment by MartinWeb** [comment]
I forget to mention it, but i have two yAxis and i want only one to have maxValue to 100 for example.

**Comment by MartinWeb** [comment]
UP please

**Comment by krispo** [comment]
Please, try to use `yDomain1`, `yDomain2` chart options:
```
chart: {
    yDomain1: [0, 100]
}
```
v0.1.1 is now more stable version for nvd3 v1.1.15b
For the recent nvd3 (1.7.1) version, please, use v1.0.0-beta.

**Comment by MartinWeb** [comment]
Thanks a lot. With v0.1.1 it's now working.

**Comment by zhendong590** [comment]
@krispo i met same problem. i want to change yAxis value range. i saw the demo [line + Bar](http://plnkr.co/edit/f0QET0?p=preview/ "Title"),how to make the y2Axis range to [0 -- max],now it starts at $57.27

**Comment by hunkim** [comment]
Did we fix this problem? I stil have the same problem with  v1.0.4-dev version. They don't get the right  max and min range.

![image](https://cloud.githubusercontent.com/assets/901975/11323598/93f8c59e-9150-11e5-942d-2899341c7346.png)
