### ISSUE TITLE
How do I add range bands to charts?

### ISSUE THREAD

**Issue by ragefuljoe** [krispo/angular-nvd3#88]
Trying to add y-axis range bands, to accomplish something like this: https://www.dropbox.com/s/gvteunsldz87s6r/Screenshot%202015-02-26%2010.11.37.png?dl=0

Is this currently possible without editing source?

thanks!

**Comment by digitalhydra** [comment]
On what chart do you want to add the range?, also the image it's not available so we don't know what you mean. 
If you want to extend the functionality of a chart you can use the callback property and modify the chart using the D3 API.
