### ISSUE TITLE
axisLabelDistance has no effect

### ISSUE THREAD

**Issue by kytwb** [krispo/angular-nvd3#90]
Using `0.1.1`.

**Comment by krispo** [comment]
It's nvd3 core bug. Version 0.1.1 is used with old nvd3 (1.1.15b).
This bug seems to be fixed in newer nvd3 version (1.7.1) with corresponding angular-nvd3 (1.0.0b).

**Comment by kytwb** [comment]
I'm now using `angular-nvd3#master` but `axisLabel` dissappeared and `axisLabelDistance` is still ineffective.

**Comment by krispo** [comment]
what kind of chart are you using?

**Comment by kytwb** [comment]
Using `discreteBarChart`.

**Comment by krispo** [comment]
Y axis? Try to set negative value: `axisLabelDistance: -10`

**Comment by kytwb** [comment]
Did the trick. I still have an issue though with my X axis.
Can't see the label and the value go out of the canvas, so I guess the label is somewhere below, out of the canvas too. I guess it's related to nvd3 directly, should I open a ticket there?

![](http://s3.amazonaws.com/awesome_screenshot/7623441?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1425453810&Signature=Lr3PaYL%2BMMs601yGJWWlKeYx2Eo%3D)

**Comment by kytwb** [comment]
Adding a `chart.margin.bottom` did the trick.

**Comment by wenjiechen** [comment]
axisLabelDistance is ineffective for x axis, because x axis uses a private variable xLabelMargin instead of axisLabelDistance.

**Comment by wenjiechen** [comment]
fast fix:  var xLabelMargin = axisLabelDistance;
