### ISSUE TITLE
yAxis.tickFormat doesn't work on stackedAreaChart

### ISSUE THREAD

**Issue by motionsmith** [krispo/angular-nvd3#91]
Setting `$scope.options.chart.yAxis.tickFormat` doesn't work for the `stackedAreaChart`. We found this through our own code, but it can be reproed on your demo:
http://krispo.github.io/angular-nvd3/#/stackedAreaChart

Thanks for your help!

**Comment by krispo** [comment]
In the newer nvd3 version I found another one option called `yAxisTickFormat` for that, directly in the `chart`:
`$scope.options.chart.yAxisTickFormat = function (d){ return d3.format(',.1f')(d); }`.

**Comment by motionsmith** [comment]
That seems to work, thanks!
