### ISSUE TITLE
pie chart resizing oddities

### ISSUE THREAD

**Issue by maplesap** [krispo/angular-nvd3#92]
My pie chart is acting really oddly. I have it wrapped in some bootstrap element tabs and I noticed:

(1) On page load, click on chart tab and chart is tiny and not resized to parent container
(2) On browser window dimension change, the chart gets resized correctly
(3) On mouseover to a section of the pie chart, the chart section shrinks back to its tiny dimensions in (1)

Here is an image to visually show what is happening:
https://imgur.com/2znRdol

The images correspond to the actions (1) - (3) that I described.

my bower dependencies:

    "d3": "~3.5.5",
    "nvd3": "~1.7.1",
    "angular-nvd3": "~0.1.1"

****UPDATE****
I found a similar bug report:
https://github.com/krispo/angular-nvd3/issues/85

I've created a plnkr based on it:
http://plnkr.co/edit/G1Q8QiFpLnsA9116o2wq?p=preview

My problem (1) is fixed, but (2) and (3) are still problems. In plunkr, click the second tab. If you hover the mouse over the pie sections, they'll shrink. Then, change the browser dimensions and you'll see the pie becomes the correct size again, only to shrink once you mouse over (again!).

**Comment by krispo** [comment]
It seems like a bug with pie chart in the newer nvd3 version (1.7.1).
Try to use v1.1.15-beta of nvd3 like in this example: http://plnkr.co/edit/vtKWU0?p=preview

**Comment by maplesap** [comment]
@krispo Thanks, using v1.1.15-beta fixes it, but `growOnHover` doesn't seem supported in this version.

**Comment by anantagrawal** [comment]
@maplesap ..are you using ng-show anywhere to hide/show chart ? If yes, then replace it with ng-if. It should work.

**Comment by riendaamen** [comment]
@anantagrawal  Thanks, ng-if instead of ng-show solves the sizing of the chart.

**Comment by keymsg** [comment]
@anantagrawal 
thanks. your suggestion fixed my issue.
