### ISSUE TITLE
Detect renderStart and renderEnd?

### ISSUE THREAD

**Issue by Workings** [krispo/angular-nvd3#93]
Is there any way to detect when the chart start and stops? Was thinking alone lines of:

chart: {
       dispatch: {
              renderEnd: function(e)
              {
                  //Do something
              }
       }

**Comment by krispo** [comment]
There is only `renderEnd` event (for stops). It's added in the newer nvd3 versions. Your json schema is right. Actually, one can look through the json-tree (on the website) to find any option for any chart.

**Comment by Workings** [comment]
Thanks. Updated nvd3 and now getting callbacks :-)
