### ISSUE TITLE
LineChart data is being truncated

### ISSUE THREAD

**Issue by Avallach160** [krispo/angular-nvd3#94]
Hi, it seems data is being truncated from my line chart. I was using 0.0.9 but updated to 0.1.1 and still have the same problem. I also switched to a historicalBarChart with the same result. Data after the 10th index is just being dropped. 

![image](https://cloud.githubusercontent.com/assets/6992987/6561003/36b2f308-c64b-11e4-9fcd-5a4c74a86d22.png)

Chart object: 
		var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
		vm.yoyEventsByMonth = {
			options:{
				chart:{
					type: 'lineChart',
					height: 400,
					legend: {
	                	updateState: false
	                },
	                useInteractiveGuideline: true,
	                x: function(d){return d.x;},
	                y: function(d){return d.y;},
	                xAxis: {
	                	tickFormat: function (d){
	                		return months[d];
	                	}
	                }
				},
				title:{
					enable: true,
					text: 'Event Totals by Year',
					class: 'h3'
				}
			},
			data: []
		};
Data: 
[{"key":2014,"values":[{"x":"0","y":0,"series":0},{"x":"1","y":1,"series":0},{"x":"2","y":0,"series":0},{"x":"3","y":0,"series":0},{"x":"4","y":0,"series":0},{"x":"5","y":0,"series":0},{"x":"6","y":0,"series":0},{"x":"7","y":0,"series":0},{"x":"8","y":0,"series":0},{"x":"9","y":1,"series":0},{"x":"10","y":0,"series":0},{"x":"11","y":1,"series":0}]},{"key":2015,"values":[{"x":"0","y":0,"series":1},{"x":"1","y":38,"series":1},{"x":"2","y":8,"series":1},{"x":"3","y":0,"series":1},{"x":"4","y":0,"series":1},{"x":"5","y":0,"series":1},{"x":"6","y":0,"series":1},{"x":"7","y":0,"series":1},{"x":"8","y":0,"series":1},{"x":"9","y":0,"series":1},{"x":"10","y":0,"series":1},{"x":"11","y":0,"series":1}]}]

I was expecting it to go out to December regardless of if y had a value. In the first series, y does have 1 but still no luck. I also pasted this data into the plunker for this chart of it was truncated at October. Thanks for any light you can shed on this.

**Comment by krispo** [comment]
Try to convert x values to numbers: `x: function(d){return +d.x;}`
If don't help, try to extend domain on x axis:
```
chart: {
  xDomain: [0, 11]
}
```

**Comment by Avallach160** [comment]
@krispo The first solution worked. Thank you!
