### ISSUE TITLE
Error with legend chart when resizing the browser: Uncaught TypeError : angular-nvd3.js:148

### ISSUE THREAD

**Issue by PhilFlash** [krispo/angular-nvd3#98]
Hi,
I use a legend chart like this:
http://plnkr.co/edit/34GwmM

When I resize my browser, I have many errors:
Uncaught TypeError: undefined is not a function
  (anonymous function)
angular-nvd3.js:148

To test:
- download the Plunk as a zip file (with plunker, there is no error in the console)
- run the plunk in Chrome for example
- resize the browser
- open the console in Developer Tools

There are many errors:
Uncaught TypeError: undefined is not a function : angular-nvd3.js:148

Philippe

**Comment by krispo** [comment]
hmm... I didn't test it for legend only...
I looked through the source, `legend` model doesn't have `update` method at all. So, just try to ignore this error line with `chart.update` for legend only. The chart will not resize.

**Comment by PhilFlash** [comment]
OK, thanks

**Comment by NameFILIP** [comment]
Added a check if `update` is defined https://github.com/krispo/angular-nvd3/pull/165
