### ISSUE TITLE
No way to set a dynamic yDomain?

### ISSUE THREAD

**Issue by yannh** [krispo/angular-nvd3#99]
Hello, I am trying to force the minimum value of one of my linearCharts to be 0, so I am doing something like this:

yDomain: [0, d3.max(mytable, function(x) { return x.N; } )]

This initially sets a correct yDomain, but the yDomain doesn't get updated as new data come in.

For example if initially mytable's maximum value is 10, the yDomain is correctly set to [0, 10] - but then if mytable changes and the maximum value is only 5, the yDomain will still be [0, 10], instead of changing to [0,5].
Am I missing something?
Thanks!

**Comment by krispo** [comment]
Initially domain stores just two numbers, so if the data changes, domain should be reassigned:
```js
$scope.options.chart.yDomain = [0, d3.max(mytable, function(x) { return x.N; } )];
$scope.$apply(); //this line may not required
```

**Comment by yannh** [comment]
@krispo thank you very much for your help! Is this something that should be patched in angular-nvd3, or that I should add in my code?
The domain changes dynamically with the data if I don't set it manually myself, do you think there would be any way to have it auto-refresh without having me refresh it manually in the controller?

Thanks a lot for your reply! Let me know if I can help!
